"use client";

import { useCallback, useEffect, useRef, useState, type CSSProperties } from "react";
import { ChevronLeft, Minimize2 } from "lucide-react";
import { useEditor } from "@/hooks/use-editor";
import { useInterfaceSettings } from "@/hooks/use-interface-settings";
import { generateFromDesignPlan } from "@/lib/ai/local";
import { createDesignPlan, offlineResearch, researchQueryFor } from "@/lib/design-intelligence/planner";
import { createFrameRecipeElements } from "@/lib/design-intelligence/frame-factory";
import { createPresetTestScene } from "@/lib/design-intelligence/preset-test-scene";
import { validateAndRepairGeneration } from "@/lib/design-intelligence/validator";
import { elementStyle } from "@/lib/editor/render";
import { IMAGE_ACCEPT } from "@/lib/editor/assets";
import { DEFAULT_SNAP_SETTINGS, type PixelSnapMode, type SnapMode, type SnapSettings } from "@/lib/editor/snapping";
import { canConvertToPath, geometryKindForElement, geometryNodesFromElement } from "@/lib/editor/geometry";
import { createVectorElement, exportProjectData, loadProject } from "@/lib/editor/project";
import { applyBooleanBuild, buildBooleanSelection, flattenBoolean, rebuildBooleanElement, releaseBoolean } from "@/lib/editor/boolean";
import { renderCanvasSnapshot } from "@/lib/ai/canvas-snapshot";
import type { AIDebugSummary, AIProgressEvent, AIProviderStatus, CreatorMakeAIPlan, ReferenceDetail } from "@/lib/ai/types";
import { AIDebugPanel } from "./AIDebugPanel";
import { AIDesignPlanDialog } from "./AIDesignPlanDialog";
import { EditorSettingsDialog } from "./EditorSettingsDialog";
import { CanvasStage } from "./CanvasStage";
import { CanvasControls } from "./CanvasControls";
import { CommandPalette } from "./CommandPalette";
import type { EditorCommand } from "./CommandPalette";
import { ContextBar } from "./ContextBar";
import { DesignPlanDialog } from "./DesignPlanDialog";
import { ElementSurface } from "./ElementSurface";
import { EditorContextMenu } from "./EditorContextMenu";
import { Inspector } from "./Inspector";
import { LayersPanel } from "./LayersPanel";
import { ProjectDialog } from "./ProjectDialog";
import { PromptWorkspace } from "./PromptWorkspace";
import type { PlanInput } from "./PromptWorkspace";
import { RobloxExportDialog } from "./RobloxExportDialog";
import type { StudioConnectionSummary } from "./RobloxExportDialog";
import { TopToolbar } from "./TopToolbar";
import type { DesignPlan, FrameRecipe, ResearchRequest, ResearchResult, SystemPreset } from "@/lib/design-intelligence/types";
import { CREATOR_FONTS, loadCreatorFont } from "@/lib/fonts/font-library";
import { CREATORMAKE_BRIDGE_ORIGIN, CREATORMAKE_BRIDGE_VERSION, CREATORMAKE_PROTOCOL_VERSION } from "@/lib/creatormake-version.js";
import { isRobloxNativeFontFamily, suggestRobloxNativeFamily } from "@/lib/roblox/fonts";
import type { CreatorFont } from "@/lib/fonts/font-library";
import type { BooleanOperation, EditorAsset, EditorElement, ElementType, GenerationHistoryEntry, ViewAction } from "@/lib/editor/types";
import type { WorkspaceMode } from "@/lib/ui/interface-themes";

function PreviewElementTree({element,elements,assets,parent}:{element:EditorElement;elements:EditorElement[];assets:EditorAsset[];parent?:EditorElement}){
  const children=elements.filter((child)=>child.parentId===element.id&&!child.hidden),style:CSSProperties={...elementStyle(element),left:element.x-(parent?.x??0),top:element.y-(parent?.y??0),overflow:element.type==="scrolling-frame"||element.clipContent?"hidden":"visible"};
  if(element.type==="scrolling-frame")return <div className={`canvas-element type-${element.type}`} style={style}><ElementSurface element={element}/><PreviewScrollArea element={element} elements={elements} assets={assets}>{children}</PreviewScrollArea></div>;
  const stateAssetId=element.type==="image-button"?(element.imageStateAssetIds[element.imagePreviewState]??element.imageAssetId):element.imageAssetId;
  return <div className={`canvas-element type-${element.type}`} style={style}><ElementSurface element={element} asset={assets.find((asset)=>asset.id===stateAssetId)}/>{children.map((child)=><PreviewElementTree key={child.id} element={child} elements={elements} assets={assets} parent={element}/>)}</div>;
}

function PreviewScrollArea({element,elements,assets,children}:{element:EditorElement;elements:EditorElement[];assets:EditorAsset[];children:EditorElement[]}){
  const ref=useRef<HTMLDivElement>(null);useEffect(()=>{if(ref.current){ref.current.scrollLeft=element.canvasPositionX;ref.current.scrollTop=element.canvasPositionY;}},[element.canvasPositionX,element.canvasPositionY]);
  const contentWidth=Math.max(element.width,...children.map((child)=>child.x-element.x+child.width+element.layoutPadding.right)),contentHeight=Math.max(element.height,...children.map((child)=>child.y-element.y+child.height+element.layoutPadding.bottom)),canvasWidth=element.automaticCanvasSize==="X"||element.automaticCanvasSize==="XY"?contentWidth:element.canvasSizeX,canvasHeight=element.automaticCanvasSize==="Y"||element.automaticCanvasSize==="XY"?contentHeight:element.canvasSizeY,direction=element.scrollingDirection;
  const overflowX=element.scrollingEnabled&&(direction==="X"||direction==="XY")?"auto":"hidden",overflowY=element.scrollingEnabled&&(direction==="Y"||direction==="XY")?"auto":"hidden";
  return <div ref={ref} className="preview-scroll-viewport" data-scroll-direction={direction} style={{overflowX,overflowY,scrollbarColor:`${element.scrollBarImageColor} transparent`,scrollbarWidth:element.scrollBarThickness===0?"none":"auto",touchAction:element.scrollingEnabled?direction==="X"?"pan-x":direction==="Y"?"pan-y":"pan-x pan-y":"none"}}><div className="preview-scroll-canvas" style={{width:Math.max(element.width,canvasWidth),height:Math.max(element.height,canvasHeight)}}>{children.map((child)=><PreviewElementTree key={child.id} element={child} elements={elements} assets={assets} parent={element}/>)}</div></div>;
}

export function CreatorMakeEditor({ aiEnabled = false }: { aiEnabled?: boolean }) {
  const interfaceUi=useInterfaceSettings();
  const [snapMode,setSnapMode]=useState<SnapMode>("smart"),[pixelSnap,setPixelSnap]=useState<PixelSnapMode>("off"),[snapSettings,setSnapSettings]=useState<SnapSettings>(DEFAULT_SNAP_SETTINGS);
  const editor = useEditor(); const [zoom, setZoom] = useState(.75); const [preview, setPreview] = useState(false); const [focus, setFocus] = useState(false); const [projectsOpen, setProjectsOpen] = useState(false); const [exportOpen,setExportOpen]=useState(false); const [settingsOpen,setSettingsOpen]=useState(false); const [studioStatus,setStudioStatus]=useState<StudioConnectionSummary>({status:"disconnected",pluginOnline:false,pendingChanges:0,lastSeenAt:null}); const [commandOpen, setCommandOpen] = useState(false); const [leftOpen, setLeftOpen] = useState(true); const [rightOpen, setRightOpen] = useState(true); const [leftWidth, setLeftWidth] = useState(244); const [rightWidth, setRightWidth] = useState(286); const [gridSize,setGridSize] = useState(8); const [showGrid,setShowGrid] = useState(true); const [snapEnabled,setSnapEnabled]=useState(true); const [smartGuides,setSmartGuides]=useState(true); const [showGuides,setShowGuides]=useState(true); const [lockGuides,setLockGuides]=useState(false); const [toolMode,setToolMode]=useState<"select"|"pen">("select"); const [pathEditId,setPathEditId]=useState<string|null>(null); const [selectedPathNodeId,setSelectedPathNodeId]=useState<string|null>(null); const [viewCommand, setViewCommand] = useState<{ action: ViewAction; token: number } | null>(null); const [notice, setNotice] = useState(""); const [clipboardCount,setClipboardCount]=useState(0); const [prompt,setPrompt] = useState(""); const [plan,setPlan] = useState<DesignPlan|null>(null); const [aiPlan,setAIPlan]=useState<CreatorMakeAIPlan|null>(null); const [aiProviderStatus,setAIProviderStatus]=useState<AIProviderStatus|null>(null);const [aiEvents,setAIEvents]=useState<AIProgressEvent[]>([]);const [aiGenerating,setAIGenerating]=useState(false);const [aiDebug,setAIDebug]=useState<AIDebugSummary|null>(null);const [referenceDetail,setReferenceDetail]=useState<ReferenceDetail>("high");const [generationBadge,setGenerationBadge]=useState(""); const [planning,setPlanning] = useState(false); const [lastPlanInput,setLastPlanInput] = useState<PlanInput|null>(null); const clipboard = useRef<EditorElement[]>([]),imageInput=useRef<HTMLInputElement>(null);const aiAbort=useRef<AbortController|null>(null);
  const [contextMenu,setContextMenu]=useState<{x:number;y:number}|null>(null);
  const [robloxReviewOpen,setRobloxReviewOpen]=useState(false);
  const [assetDrop,setAssetDrop]=useState<{assetId:string;targetId:string;position:{x:number;y:number}}|null>(null);
  const robloxFontIssues=editor.project.elements.filter((item)=>(item.type==="text"||item.type==="button")&&!isRobloxNativeFontFamily(item.fontFamily));
  useEffect(()=>{const receive=(event:Event)=>setAssetDrop((event as CustomEvent<{assetId:string;targetId:string;position:{x:number;y:number}}>).detail);window.addEventListener("creatormake:asset-drop",receive);return()=>window.removeEventListener("creatormake:asset-drop",receive);},[]);
  const importImages=useCallback(async(files:Iterable<File>,position?:{x:number;y:number},placeOnCanvas=true)=>{try{return await editor.importImages(files,position,placeOnCanvas);}catch(error){setNotice(error instanceof Error?error.message:"Image import failed.");window.setTimeout(()=>setNotice(""),5000);return[];}},[editor]);
  const patchOne = (id: string, patch: Partial<EditorElement>) => editor.commit((draft) => { const element = draft.elements.find((item) => item.id === id); if (element) Object.assign(element, patch); });
  const downloadProject = (project:typeof editor.project) => { const blob = new Blob([JSON.stringify(exportProjectData(project), null, 2)], { type: "application/x-creatormake+json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${project.name.replace(/[^a-z0-9]+/gi, "-").toLowerCase()||"creatormake-project"}.creatormake`; anchor.click(); URL.revokeObjectURL(url); };
  const exportJson = () => downloadProject(editor.project);
  const exportStoredProject=async(id:string)=>{const project=id===editor.project.id?editor.project:await loadProject(id);if(project)downloadProject(project);};
  const paste = useCallback(() => editor.commit((draft) => { const sources=clipboard.current,sourceIds=new Set(sources.map((item)=>item.id)),idMap=new Map(sources.map((item)=>[item.id,`${item.type}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,6)}`])),clones=sources.map((item)=>({...structuredClone(item),id:idMap.get(item.id)!,parentId:item.parentId?(idMap.get(item.parentId)??item.parentId):null,x:item.x+20,y:item.y+20,name:sourceIds.has(item.parentId??"")?item.name:`${item.name} Copy`}));draft.elements.push(...clones);draft.selectedIds=sources.filter((item)=>!item.parentId||!sourceIds.has(item.parentId)).map((item)=>idMap.get(item.id)!); }), [editor]);
  const copySelection=useCallback(()=>{const ids=new Set(editor.project.selectedIds);let changed=true;while(changed){changed=false;editor.project.elements.forEach((item)=>{if(item.parentId&&ids.has(item.parentId)&&!ids.has(item.id)){ids.add(item.id);changed=true;}});}clipboard.current=editor.project.elements.filter((item)=>ids.has(item.id)).map((item)=>structuredClone(item));setClipboardCount(clipboard.current.length);setNotice(`Copied ${editor.project.selectedIds.length} object${editor.project.selectedIds.length===1?"":"s"}.`);window.setTimeout(()=>setNotice(""),1800);},[editor.project.elements,editor.project.selectedIds]);
  const add = useCallback((type: ElementType) => {setToolMode("select");setPathEditId(null);setSelectedPathNodeId(null);const robloxText=interfaceUi.settings.workspaceMode==="roblox"&&(type==="text"||type==="button");editor.addElement(type,robloxText?{fontId:"roboto",fontFamily:"Roboto"}:{});}, [editor,interfaceUi.settings.workspaceMode]); const view = (action: ViewAction) => setViewCommand({ action, token: Date.now() });
  const applyWorkspace=useCallback((workspaceMode:WorkspaceMode)=>{interfaceUi.patch({workspaceMode});setFocus(false);if(workspaceMode==="review"||workspaceMode==="deliver"){setLeftOpen(false);setRightOpen(true);}else if(workspaceMode==="prototype"){setLeftOpen(true);setRightOpen(false);}else{setLeftOpen(true);setRightOpen(true);}},[interfaceUi]);
  const changeWorkspace=useCallback((workspaceMode:WorkspaceMode)=>{if(workspaceMode==="roblox"&&interfaceUi.settings.workspaceMode!=="roblox"&&robloxFontIssues.length){setRobloxReviewOpen(true);return;}applyWorkspace(workspaceMode);},[applyWorkspace,interfaceUi.settings.workspaceMode,robloxFontIssues.length]);
  const enterRobloxMode=(replaceFonts:boolean)=>{if(replaceFonts)editor.commit((draft)=>{draft.elements.forEach((item)=>{if((item.type==="text"||item.type==="button")&&!isRobloxNativeFontFamily(item.fontFamily)){const family=suggestRobloxNativeFamily(item.fontFamily);item.fontFamily=family;item.fontId=family.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");}});},"Replace unsupported Roblox fonts");applyWorkspace("roblox");setRobloxReviewOpen(false);setNotice(replaceFonts?`Roblox Mode enabled · replaced ${robloxFontIssues.length} unsupported font${robloxFontIssues.length===1?"":"s"}.`:`Roblox Mode enabled · ${robloxFontIssues.length} font issue${robloxFontIssues.length===1?"":"s"} kept for review.`);window.setTimeout(()=>setNotice(""),5200);};
  const enterPathEdit=useCallback((id:string|null)=>{if(!id){setPathEditId(null);setSelectedPathNodeId(null);setToolMode("select");return;}const element=editor.project.elements.find((item)=>item.id===id);if(!element)return;if(!canConvertToPath(element)){setNotice(element.booleanOperation?"Flatten the Boolean group before editing its final path.":"Multi-contour path node editing is not available.");window.setTimeout(()=>setNotice(""),3600);return;}if(element.geometry.kind!=="custom-path"){editor.commit((draft)=>{const target=draft.elements.find((item)=>item.id===id);if(!target)return;const sourceKind=geometryKindForElement(target);target.geometry={...target.geometry,kind:"custom-path",nodes:geometryNodesFromElement(target),closed:!["line","arc"].includes(sourceKind),pathData:""};draft.selectedIds=[id];});}else editor.select(id);setPathEditId(id);setSelectedPathNodeId(null);setToolMode("select");},[editor]);
  const beginPen=useCallback(()=>{const editingPath=editor.project.elements.find((item)=>item.id===pathEditId&&item.geometry.kind==="custom-path");if(editingPath){setToolMode("pen");return;}const element=createVectorElement("custom-path",editor.project.elements.length);editor.commit((draft)=>{draft.elements.push(element);draft.selectedIds=[element.id];});setPathEditId(element.id);setSelectedPathNodeId(null);setToolMode("pen");},[editor,pathEditId]);
  const runBoolean=(operation:BooleanOperation)=>{try{const build=buildBooleanSelection(editor.project,operation);enterPathEdit(null);editor.commit((draft)=>applyBooleanBuild(draft,build));setNotice(operation==="divide"?`Divide created ${build.elements.length} editable vector regions.`:`Created an editable, non-destructive ${operation} Boolean.`);}catch(error){setNotice(error instanceof Error?error.message:"Boolean operation failed.");}window.setTimeout(()=>setNotice(""),4200);};
  const changeBoolean=(id:string,operation:Exclude<BooleanOperation,"divide">)=>{const element=editor.project.elements.find((item)=>item.id===id);if(!element)return;try{const rebuilt=rebuildBooleanElement(element,operation);editor.commit((draft)=>{const index=draft.elements.findIndex((item)=>item.id===id);if(index>=0)draft.elements[index]=rebuilt;draft.selectedIds=[id];});setNotice(`Boolean changed to ${operation}.`);}catch(error){setNotice(error instanceof Error?error.message:"Boolean operation failed.");}window.setTimeout(()=>setNotice(""),3600);};
  const researchAndPlan = async (input:PlanInput, refresh=false) => { if(!aiEnabled){setNotice("AI generation is temporarily disabled during manual editor development.");return;} setPlanning(true); setLastPlanInput(input); setAIEvents([]); setGenerationBadge(""); if(input.engine==="LOCAL"){const request: ResearchRequest = { prompt:input.prompt,style:input.style,platform:input.platform,referenceCount:editor.project.references.length,selectedCount:editor.project.selectedIds.length,refresh }; const cacheKey=researchQueryFor(request).toLowerCase(); let research:ResearchResult|undefined=!refresh?editor.project.researchCache[cacheKey]:undefined; if(!research){ try { const response=await fetch("/api/research",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(request)}); if(!response.ok)throw new Error("research unavailable"); research=await response.json() as ResearchResult; } catch { research=offlineResearch(request); } editor.cacheResearch(cacheKey,research); } setPlan(createDesignPlan({...request,mode:input.mode,accuracy:"Precise",referenceIds:editor.project.references.map((reference)=>reference.id)},research,editor.project.references));setPlanning(false);return;}const controller=new AbortController();aiAbort.current=controller;try{const canvasImage=await renderCanvasSnapshot(editor.project);const response=await fetch("/api/ai/plan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prompt:input.prompt,mode:input.mode,style:input.style,platform:input.platform,quality:input.engine,referenceDetail,project:editor.project,canvasImage}),signal:controller.signal});const payload=await response.json() as {plan?:CreatorMakeAIPlan;events?:AIProgressEvent[];error?:string};if(!response.ok||!payload.plan)throw new Error(payload.error??"External AI planning failed.");setAIPlan(payload.plan);setAIEvents(payload.events??[]);setAIProviderStatus((current)=>current?{...current,connected:true,message:"OpenAI Responses API connection verified."}:current);}catch(error){if(error instanceof Error&&error.name==="AbortError")setNotice("AI planning cancelled. No project changes were made.");else setNotice(`${error instanceof Error?error.message:"AI planning failed."} No Local Generator fallback was used.`);}finally{if(aiAbort.current===controller)aiAbort.current=null;setPlanning(false);} };
  const generatePlan = () => { if(!plan)return; const before={elements:structuredClone(editor.project.elements),selectedIds:[...editor.project.selectedIds]}; if(plan.layoutKind==="selected-edit"){ const input=plan.prompt.toLowerCase(); editor.commit((draft)=>{ const patch:Partial<EditorElement>={}; if(input.includes("red"))patch.fill="#d9364f"; if(input.includes("blue"))patch.fill="#2d69ff"; if(input.includes("green"))patch.fill="#35b96f"; if(input.includes("thicker")&&input.includes("border")){ const active=draft.elements.find((item)=>draft.selectedIds.includes(item.id)); patch.borderWidth=(active?.borderWidth??1)+2; } draft.elements.forEach((item)=>{if(draft.selectedIds.includes(item.id))Object.assign(item,patch);}); const entry:GenerationHistoryEntry={id:`history_${Date.now()}`,prompt:plan.prompt,researchQuery:plan.research.query,plan,engine:"LOCAL",provider:"local",operations:["applied targeted selected-object delta"],resultIds:[...draft.selectedIds],time:Date.now(),before}; draft.generationHistory.push(entry);}); setNotice("Applied with Local Generator as one undo action."); } else { const result=generateFromDesignPlan(plan,editor.project.references); const validation=validateAndRepairGeneration(result.elements,plan); editor.commit((draft)=>{draft.elements.push(...validation.elements);draft.selectedIds=[validation.elements[0].id];draft.generationHistory.push({id:`history_${Date.now()}`,prompt:plan.prompt,researchQuery:plan.research.query,plan,engine:"LOCAL",provider:"local",operations:[...result.operations,`validated ${validation.elements.length} objects`,...(validation.repaired?[`repaired ${validation.repaired} deterministic issues`]:[])],resultIds:validation.elements.map((item)=>item.id),time:Date.now(),before,validation:{passed:validation.passed,repaired:validation.repaired,issues:validation.issues.map((issue)=>issue.message)}});}); setNotice(`Local Generator created ${validation.elements.length} editable objects · validation ${validation.passed?"passed":"needs review"}.`); } setGenerationBadge("Generated with: LOCAL GENERATOR");setPlan(null); window.setTimeout(()=>setNotice(""),5200); };
  const generateAIPlan=async()=>{if(!aiEnabled)return;if(!aiPlan||!lastPlanInput)return;setAIGenerating(true);setAIEvents([{type:"plan.complete",message:"Approved plan received. Contacting OpenAI tool orchestrator…"}]);const controller=new AbortController();aiAbort.current=controller;const before={elements:structuredClone(editor.project.elements),selectedIds:[...editor.project.selectedIds]};try{const canvasImage=await renderCanvasSnapshot(editor.project);const response=await fetch("/api/ai/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prompt:aiPlan.prompt,mode:aiPlan.mode,style:aiPlan.style,platform:aiPlan.platform,quality:aiPlan.quality,referenceDetail,project:editor.project,canvasImage,plan:aiPlan}),signal:controller.signal});const payload=await response.json() as {result?:import("@/lib/ai/types").AIGenerationResult;events?:AIProgressEvent[];error?:string};if(!response.ok||!payload.result)throw new Error(payload.error??"External AI generation failed.");const result=payload.result;setAIEvents(payload.events??[]);editor.commit((draft)=>{draft.elements=structuredClone(result.elements);draft.selectedIds=[...result.selectedIds];draft.generationHistory.push({id:`history_${Date.now()}`,prompt:aiPlan.prompt,researchQuery:"External AI visual analysis",aiPlan:structuredClone(aiPlan),engine:aiPlan.quality,provider:"openai",model:aiPlan.model,operations:result.operations,resultIds:[...result.selectedIds],time:Date.now(),before,validation:{passed:result.validation.passed,repaired:result.validation.repaired,issues:result.validation.issues.map((issue)=>issue.message)}});});setAIDebug(result.debug);setGenerationBadge(`Generated with: OPENAI AI — ${aiPlan.quality}`);setNotice(result.needsAnotherPass?"CreatorMake needs another AI pass; the operation budget was reached.":`OpenAI ${aiPlan.quality} completed ${result.debug.toolCalls} tool calls · validation ${result.debug.validation}.`);setAIPlan(null);}catch(error){if(error instanceof Error&&error.name==="AbortError")setNotice("AI generation cancelled. The transaction was rolled back and no project changes were committed.");else setNotice(`${error instanceof Error?error.message:"AI generation failed."} No Local Generator fallback was used.`);}finally{if(aiAbort.current===controller)aiAbort.current=null;setAIGenerating(false);}};
  const cancelAI=()=>{aiAbort.current?.abort();aiAbort.current=null;setPlanning(false);setAIGenerating(false);setAIPlan(null);setAIEvents([]);};
  const insertFrame = (recipe:FrameRecipe) => { const items=createFrameRecipeElements(recipe,editor.project.activePresetIds.at(-1)??"digital-system",editor.project.elements.length); editor.commit((draft)=>{draft.elements.push(...items);draft.selectedIds=[items[0].id];}); setNotice(`Inserted ${recipe.name} as ${items.length} editable objects.`); window.setTimeout(()=>setNotice(""),3600); };
  const testPreset = (preset:SystemPreset) => { const items=createPresetTestScene(preset,editor.project.elements.length); editor.commit((draft)=>{draft.elements.push(...items);draft.selectedIds=[items[0].id];}); setNotice(`Inserted the ${preset.name} component sheet for structural inspection.`); window.setTimeout(()=>setNotice(""),4200); };
  const applyFont = (font:CreatorFont,weight:number,style:"normal"|"italic") => { const editable=editor.project.elements.some((item)=>editor.project.selectedIds.includes(item.id)&&(item.type==="text"||item.type==="button")); if(!editable){setNotice("Select a text or button layer before applying a font.");window.setTimeout(()=>setNotice(""),3200);return;} void loadCreatorFont(font,weight,style).then((status)=>{if(status==="loaded"){editor.applyFont(font.id,font.family,weight,style);setNotice(`Applied ${font.family} ${weight} ${style} without changing geometry.`);}else setNotice(`${font.family} could not load and was not applied.`);window.setTimeout(()=>setNotice(""),3600);}); };
  const rerunHistory = (entry:GenerationHistoryEntry) => { setPrompt(entry.prompt);if(entry.aiPlan){setLastPlanInput({prompt:entry.aiPlan.prompt,style:entry.aiPlan.style,mode:entry.aiPlan.mode,platform:entry.aiPlan.platform,accuracy:entry.aiPlan.quality,engine:entry.aiPlan.quality});setAIPlan(structuredClone(entry.aiPlan));}else if(entry.plan){setLastPlanInput({prompt:entry.plan.prompt,style:entry.plan.style,mode:entry.plan.mode,platform:entry.plan.platform,accuracy:entry.plan.accuracy,engine:"LOCAL"}); setPlan(structuredClone(entry.plan));} };
  const startPanelResize = (side: "left" | "right", event: React.PointerEvent) => { const startX = event.clientX, initial = side === "left" ? leftWidth : rightWidth; let finalValue=initial; const move = (next: PointerEvent) => { const delta = next.clientX - startX; const value = Math.min(420, Math.max(180, side === "left" ? initial + delta : initial - delta)); finalValue=value; if(side === "left") setLeftWidth(value); else setRightWidth(value); }; const up = () => { interfaceUi.patch(side==="left"?{leftPanelWidth:finalValue}:{rightPanelWidth:finalValue}); window.removeEventListener("pointermove", move); window.removeEventListener("pointerup", up); }; window.addEventListener("pointermove", move); window.addEventListener("pointerup", up, { once: true }); };

  useEffect(()=>{if(!interfaceUi.hydrated)return;const frame=window.requestAnimationFrame(()=>{setLeftWidth(interfaceUi.settings.leftPanelWidth);setRightWidth(interfaceUi.settings.rightPanelWidth);const mode=interfaceUi.settings.workspaceMode;if(mode==="review"||mode==="deliver"){setLeftOpen(false);setRightOpen(true);}else if(mode==="prototype"){setLeftOpen(true);setRightOpen(false);}});return()=>window.cancelAnimationFrame(frame);},[interfaceUi.hydrated,interfaceUi.settings.leftPanelWidth,interfaceUi.settings.rightPanelWidth,interfaceUi.settings.workspaceMode]);

  useEffect(()=>{const onPathKey=(event:KeyboardEvent)=>{const tag=(event.target as HTMLElement)?.tagName;if(["INPUT","TEXTAREA","SELECT"].includes(tag)||(event.ctrlKey||event.metaKey||event.altKey))return;const lower=event.key.toLowerCase();if(pathEditId&&selectedPathNodeId&&(event.key==="Delete"||event.key==="Backspace")){event.preventDefault();event.stopImmediatePropagation();editor.commit((draft)=>{const element=draft.elements.find((item)=>item.id===pathEditId);if(element)element.geometry.nodes=element.geometry.nodes.filter((node)=>node.id!==selectedPathNodeId);});setSelectedPathNodeId(null);return;}if(lower==="p"){event.preventDefault();event.stopImmediatePropagation();beginPen();return;}if(lower==="v"){event.preventDefault();event.stopImmediatePropagation();setToolMode("select");return;}if(event.key==="Enter"){const active=editor.project.elements.find((item)=>item.id===editor.project.selectedIds.at(-1));if(pathEditId){event.preventDefault();event.stopImmediatePropagation();const path=editor.project.elements.find((item)=>item.id===pathEditId);if(toolMode==="pen"&&path&&path.geometry.nodes.length>=3&&!path.geometry.closed)editor.commit((draft)=>{const element=draft.elements.find((item)=>item.id===pathEditId);if(element)element.geometry.closed=true;});setToolMode("select");}else if(active?.type==="vector"){event.preventDefault();event.stopImmediatePropagation();enterPathEdit(active.id);}return;}if(event.key==="Escape"&&pathEditId){event.preventDefault();event.stopImmediatePropagation();enterPathEdit(null);}};window.addEventListener("keydown",onPathKey);return()=>window.removeEventListener("keydown",onPathKey);},[beginPen,editor,enterPathEdit,pathEditId,selectedPathNodeId,toolMode]);

    useEffect(()=>{const direct=(event:KeyboardEvent)=>{const tag=(event.target as HTMLElement)?.tagName;if(event.key.toLowerCase()!=="a"||event.shiftKey||event.altKey||event.ctrlKey||event.metaKey||["INPUT","TEXTAREA","SELECT"].includes(tag))return;const id=editor.project.selectedIds.at(-1);if(id){event.preventDefault();event.stopImmediatePropagation();enterPathEdit(id);}};window.addEventListener("keydown",direct,true);return()=>window.removeEventListener("keydown",direct,true);},[editor.project.selectedIds,enterPathEdit]);
    useEffect(() => { const onKey = (event: KeyboardEvent) => { const tag = (event.target as HTMLElement)?.tagName; const editing = ["INPUT","TEXTAREA","SELECT"].includes(tag);const lower = event.key.toLowerCase(); if ((event.ctrlKey || event.metaKey) && lower === "s") { event.preventDefault(); void editor.forceSave(); return; } if ((event.ctrlKey || event.metaKey) && lower === "k") { event.preventDefault(); setCommandOpen(true); return; } if (editing) return; if ((event.ctrlKey || event.metaKey) && lower === "z") { event.preventDefault(); if(event.shiftKey) editor.redo(); else editor.undo(); } else if ((event.ctrlKey || event.metaKey) && lower === "y") { event.preventDefault(); editor.redo(); } else if ((event.ctrlKey || event.metaKey) && lower === "d") { event.preventDefault(); editor.duplicateSelected(); } else if ((event.ctrlKey || event.metaKey) && lower === "g") { event.preventDefault(); if(event.shiftKey) editor.ungroup(); else editor.group(); } else if ((event.ctrlKey || event.metaKey) && lower === "c") { const ids=new Set(editor.project.selectedIds);let changed=true;while(changed){changed=false;editor.project.elements.forEach((item)=>{if(item.parentId&&ids.has(item.parentId)&&!ids.has(item.id)){ids.add(item.id);changed=true;}});}clipboard.current=editor.project.elements.filter((item)=>ids.has(item.id)).map((item)=>structuredClone(item)); } else if ((event.ctrlKey || event.metaKey) && lower === "v") { event.preventDefault(); paste(); } else if (event.key === "Delete" || event.key === "Backspace") editor.deleteSelected(); else if (["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(event.key)) { event.preventDefault(); const amount = event.shiftKey ? 10 : 1; editor.nudge(event.key === "ArrowLeft" ? -amount : event.key === "ArrowRight" ? amount : 0, event.key === "ArrowUp" ? -amount : event.key === "ArrowDown" ? amount : 0); } else if (event.shiftKey && lower === "a") { event.preventDefault(); editor.commit((draft)=>{draft.elements.forEach((item)=>{if(draft.selectedIds.includes(item.id)&&(item.type==="frame"||item.type==="container"||item.type==="scrolling-frame")){item.layoutMode="horizontal";item.gap=12;item.layoutPadding={top:16,right:16,bottom:16,left:16};item.crossAlign="center";item.frameType="group";}});}); } else if (lower === "f") add("frame"); else if (lower === "t") add("text"); else if (lower === "r") add("rectangle"); else if (lower === "o") add("ellipse"); else if (event.key === "Enter") { const active=editor.project.selectedIds.at(-1),child=editor.project.elements.find((item)=>item.parentId===active&&!item.locked);if(child){event.preventDefault();editor.select(child.id);} } else if (event.key === "Escape") { const active=editor.project.elements.find((item)=>item.id===editor.project.selectedIds.at(-1)),parent=active?.parentId;if(parent)editor.select(parent);else{setFocus(false);setCommandOpen(false);setPlan(null);} } };
    window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey);
  }, [editor, paste, add]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{const tag=(event.target as HTMLElement)?.tagName,editing=["INPUT","TEXTAREA","SELECT"].includes(tag);if(event.key==="Escape"&&!editing)editor.cancelHistoryTransaction();if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="v"&&!editing&&!clipboard.current.length)event.stopImmediatePropagation();};const pasted=(event:ClipboardEvent)=>{const files=[...(event.clipboardData?.files??[])].filter((file)=>file.type.startsWith("image/"));if(files.length){event.preventDefault();void importImages(files);}};window.addEventListener("keydown",key,true);window.addEventListener("paste",pasted,true);return()=>{window.removeEventListener("keydown",key,true);window.removeEventListener("paste",pasted,true);};},[editor.cancelHistoryTransaction,importImages]);
  useEffect(()=>{const textLayers=editor.project.elements.filter((item)=>item.type==="text"||item.type==="button");const seen=new Set<string>();textLayers.forEach((item)=>{const font=CREATOR_FONTS.find((candidate)=>candidate.family===item.fontFamily);if(font){const key=`${font.id}:${item.fontWeight}:${item.fontStyle}`;if(!seen.has(key)){seen.add(key);void loadCreatorFont(font,item.fontWeight,item.fontStyle);}}});},[editor.project.elements]);
  useEffect(()=>{if(!aiEnabled)return;let active=true;void fetch("/api/ai/status",{cache:"no-store"}).then((response)=>response.json() as Promise<AIProviderStatus>).then((value)=>{if(active)setAIProviderStatus(value);}).catch(()=>undefined);return()=>{active=false;};},[aiEnabled]);
  useEffect(()=>{let cancelled=false;const check=()=>{void fetch(`${CREATORMAKE_BRIDGE_ORIGIN}/health`,{cache:"no-store",signal:AbortSignal.timeout(3500)}).then(async(response)=>{if(!response.ok)throw new Error(`Studio Sync returned HTTP ${response.status}.`);const value=await response.json() as {status?:string;app?:string;bridgeVersion?:string;protocolVersion?:number;connectionState?:string;pluginOnline?:boolean;sync?:{pendingChanges?:number}|null};if(value.status!=="ok"||value.app!=="CreatorMake")throw new Error("Unexpected Studio Sync health response.");const bridgeReady=value.bridgeVersion===CREATORMAKE_BRIDGE_VERSION&&value.protocolVersion===CREATORMAKE_PROTOCOL_VERSION,pluginReady=bridgeReady&&value.connectionState==="STUDIO_CONNECTED"&&value.pluginOnline===true;if(!cancelled)setStudioStatus((current)=>({...current,status:pluginReady?"connected":bridgeReady?"disconnected":"error",pluginOnline:pluginReady,pendingChanges:value.sync?.pendingChanges??current.pendingChanges,lastSeenAt:pluginReady?Date.now():null}));}).catch(()=>{if(!cancelled)setStudioStatus((current)=>({...current,status:"disconnected",pluginOnline:false,lastSeenAt:null}));});};check();const timer=window.setInterval(check,10_000);return()=>{cancelled=true;window.clearInterval(timer);};},[]);
  useEffect(() => { type ToolContext = { registerTool: (tool: { name: string; title: string; description: string; inputSchema: object; annotations: object; execute: (input: unknown) => unknown }, options: { signal: AbortSignal }) => void | Promise<void> }; const context = (document as Document & { modelContext?: ToolContext }).modelContext; if (!context?.registerTool) return; const lifecycle = new AbortController(); void Promise.resolve(context.registerTool({ name: "create_editor_object", title: "Create editor object", description: "Create a real editable object on the active CreatorMake canvas.", inputSchema: { type: "object", properties: { type: { type: "string", enum: ["frame","container","scrolling-frame","text","rectangle","roundRect","ellipse","line","polygon","star","button","vector"] } }, required: ["type"], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute(input) { const type = (input as { type?: ElementType })?.type; const allowed: ElementType[] = ["frame","container","scrolling-frame","text","rectangle","roundRect","ellipse","line","polygon","star","button","vector"]; if (!type || !allowed.includes(type)) throw new Error("Unsupported object type"); editor.addElement(type); return { created: true, type }; } }, { signal: lifecycle.signal })).catch(() => undefined); return () => lifecycle.abort(); }, [editor]);

  const commands:EditorCommand[]=[
    {label:"Import image",category:"Create",keywords:"asset png jpg webp svg media",action:()=>imageInput.current?.click()},{label:"Create Frame",hint:"F",category:"Create",action:()=>add("frame")},{label:"Create ScrollingFrame",category:"Create",keywords:"Roblox scroll inventory",action:()=>add("scrolling-frame")},{label:"Create Text",hint:"T",category:"Create",keywords:"TextLabel label copy",action:()=>add("text")},{label:"Create ImageButton",category:"Create",keywords:"Roblox button image",action:()=>add("image-button")},{label:"Create rectangle",hint:"R",category:"Create",action:()=>add("rectangle")},{label:"Create ellipse",hint:"O",category:"Create",action:()=>add("ellipse")},{label:"Create star",category:"Create",action:()=>add("star")},{label:"Create triangle",category:"Create",action:()=>editor.addGeometry("triangle")},{label:"Create cut-corner rectangle",category:"Create",action:()=>editor.addGeometry("cut-corner-rectangle")},{label:"Create ring",category:"Create",action:()=>editor.addGeometry("ring")},{label:"Create title plaque",category:"Create",action:()=>editor.addGeometry("plaque")},
    {label:"Direct Selection",hint:"A",category:"Edit",keywords:"nodes bezier path handles",action:()=>{const id=editor.project.selectedIds.at(-1);if(id)enterPathEdit(id);}},{label:"Union selected paths",category:"Edit",keywords:"boolean merge",action:()=>runBoolean("union")},{label:"Subtract selected paths",category:"Edit",keywords:"boolean",action:()=>runBoolean("subtract")},{label:"Intersect selected paths",category:"Edit",keywords:"boolean",action:()=>runBoolean("intersect")},{label:"Divide selected paths",category:"Edit",keywords:"boolean split",action:()=>runBoolean("divide")},{label:"Group selection",hint:"Ctrl G",category:"Arrange",action:editor.group},{label:"Ungroup selection",hint:"Ctrl Shift G",category:"Arrange",action:editor.ungroup},{label:"Stack selection vertically",category:"Arrange",keywords:"gap distribute",action:()=>editor.stack("vertical",16,"center")},{label:"Stack selection horizontally",category:"Arrange",keywords:"gap distribute",action:()=>editor.stack("horizontal",16,"center")},{label:"Repeat Grid 5 × 6",category:"Arrange",keywords:"columns rows clone inventory",action:()=>editor.repeatGrid({columns:5,rows:6,gapX:12,gapY:12})},{label:"Align selection left",category:"Arrange",action:()=>editor.align("left","selection")},{label:"Distribute selection vertically",category:"Arrange",action:()=>editor.distribute("vertical")},
    {label:"Movement mode: Free",category:"View",keywords:"snap",action:()=>setSnapMode("free")},{label:"Movement mode: Smart",category:"View",keywords:"snap guides",action:()=>setSnapMode("smart")},{label:"Movement mode: Grid",category:"View",keywords:"snap",action:()=>setSnapMode("grid")},{label:"Fit selection",category:"View",action:()=>view("fit-selection")},{label:"Fit frame",category:"View",action:()=>view("fit-frame")},{label:"100% actual size",category:"View",action:()=>view("actual")},{label:"Preview project",category:"View",action:()=>setPreview(true)},{label:"Focus canvas",category:"View",action:()=>setFocus(true)},
    {label:"Open Roblox Studio Sync",category:"Roblox",keywords:"diagnostics export connection",action:()=>setExportOpen(true)},{label:"Export CreatorMake JSON",category:"Roblox",keywords:"download project",action:exportJson},
    ...(["design","vector","prototype","roblox","review","deliver"] as WorkspaceMode[]).map((workspaceMode)=>({label:`Switch to ${workspaceMode} workspace`,category:"Workspace" as const,keywords:"layout panels",action:()=>changeWorkspace(workspaceMode)})),
    {label:"Open appearance settings",category:"Settings",keywords:"theme color light dark",action:()=>setSettingsOpen(true)},{label:"Appearance: Light",category:"Settings",keywords:"theme",action:()=>interfaceUi.patch({appearance:"light"})},{label:"Appearance: Dark",category:"Settings",keywords:"theme",action:()=>interfaceUi.patch({appearance:"dark"})},{label:"Appearance: System",category:"Settings",keywords:"theme",action:()=>interfaceUi.patch({appearance:"system"})},
  ];
  const selected = editor.project.elements.filter((item) => editor.project.selectedIds.includes(item.id)); const canUngroup = selected.some((item) => item.name === "Group" || editor.project.elements.some((child) => child.parentId === item.id));

  if (preview) {const visible=editor.project.elements.filter((item)=>!item.hidden),visibleIds=new Set(visible.map((item)=>item.id)),roots=visible.filter((item)=>!item.parentId||!visibleIds.has(item.parentId));return <main className="preview-mode" style={{ background: editor.project.screen.background }}><button className="exit-preview" onClick={() => setPreview(false)}><ChevronLeft size={15}/> Exit preview</button><output className="preview-scroll-hint">SCROLL PREVIEW · MOUSE · TRACKPAD · TOUCH</output><div className="preview-canvas" style={{ width: editor.project.screen.width, height: editor.project.screen.height }}>{roots.map((element)=><PreviewElementTree key={element.id} element={element} elements={visible} assets={editor.project.assets}/>)}</div></main>;}
  return <main className={`editor-shell ${focus ? "focus-mode" : ""}`} onPointerDown={()=>setContextMenu(null)} onContextMenu={(event)=>{const target=(event.target as HTMLElement).closest<HTMLElement>("[data-element-id]"),canvas=(event.target as HTMLElement).closest(".canvas-document");if(!target&&!canvas)return;event.preventDefault();const id=target?.dataset.elementId;if(id&&!editor.project.selectedIds.includes(id))editor.select(id);setContextMenu({x:Math.max(8,Math.min(window.innerWidth-230,event.clientX)),y:Math.max(8,Math.min(window.innerHeight-410,event.clientY))});}}>
    <input ref={imageInput} hidden type="file" multiple accept={IMAGE_ACCEPT} onChange={(event)=>{if(event.target.files?.length)void importImages(event.target.files);event.currentTarget.value="";}}/>
    {assetDrop&&<div className="dialog-overlay" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)setAssetDrop(null);}}><section className="project-dialog asset-drop-choice" role="dialog" aria-modal="true" aria-label="Place image asset"><header><h2>Place image</h2><p>Choose how this asset should interact with {editor.project.elements.find((item)=>item.id===assetDrop.targetId)?.name??"the target object"}.</p></header><div className="gradient-actions"><button onClick={()=>{editor.applyAssetToElement(assetDrop.assetId,assetDrop.targetId);setAssetDrop(null);}}>Use as Image Fill</button><button onClick={()=>{editor.placeAsset(assetDrop.assetId,assetDrop.position);setAssetDrop(null);}}>Place Above</button>{["image","image-button"].includes(editor.project.elements.find((item)=>item.id===assetDrop.targetId)?.type??"")&&<button className="primary" onClick={()=>{editor.applyAssetToElement(assetDrop.assetId,assetDrop.targetId);setAssetDrop(null);}}>Replace Source</button>}<button onClick={()=>setAssetDrop(null)}>Cancel</button></div></section></div>}
    {robloxReviewOpen&&<div className="dialog-overlay" role="presentation"><section className="project-dialog roblox-font-review" role="dialog" aria-modal="true" aria-label="Review Roblox fonts"><header><h2>Enter Roblox Mode</h2><p>{robloxFontIssues.length} text layer{robloxFontIssues.length===1?" uses":"s use"} fonts that are not verified Roblox-native. CreatorMake will not silently substitute them.</p></header><div className="roblox-font-issues">{robloxFontIssues.slice(0,8).map((item)=><p key={item.id}><strong>{item.name}</strong><span>{item.fontFamily} → {suggestRobloxNativeFamily(item.fontFamily)}</span></p>)}</div><footer className="gradient-actions"><button onClick={()=>setRobloxReviewOpen(false)}>Cancel</button><button onClick={()=>enterRobloxMode(false)}>Keep Temporarily</button><button onClick={()=>{enterRobloxMode(false);setLeftOpen(true);setNotice("Open Fonts to replace each unsupported family with a verified Roblox font.");}}>Review Fonts</button><button className="primary" onClick={()=>enterRobloxMode(true)}>Replace Automatically</button></footer></section></div>}
    <TopToolbar projectName={editor.project.name} status={editor.status} studioStatus={studioStatus} robloxIssueCount={robloxFontIssues.length} canUndo={editor.past.length > 0} canRedo={editor.future.length > 0} zoom={zoom} appearance={interfaceUi.settings.appearance} themeName={interfaceUi.activeTheme.name} workspaceMode={interfaceUi.settings.workspaceMode} onWorkspaceMode={changeWorkspace} onCycleAppearance={interfaceUi.cycleAppearance} penActive={toolMode==="pen"} directSelectionActive={Boolean(pathEditId)&&toolMode==="select"} onPen={beginPen} onDirectSelect={()=>{const id=editor.project.selectedIds.at(-1);if(id)enterPathEdit(id);else{setNotice("Select a vector object before entering Direct Selection.");window.setTimeout(()=>setNotice(""),2400);}}} onSelectTool={()=>{setToolMode("select");if(pathEditId)enterPathEdit(null);}} onAdd={add} onImportImage={()=>imageInput.current?.click()} onAddGeometry={(kind)=>{setToolMode("select");setPathEditId(null);setSelectedPathNodeId(null);editor.addGeometry(kind);}} onUndo={editor.undo} onRedo={editor.redo} onPreview={() => setPreview(true)} onView={view} onExport={()=>setExportOpen(true)} onProjects={() => setProjectsOpen(true)} onToggleLeft={() => setLeftOpen((value) => !value)} onToggleRight={() => setRightOpen((value) => !value)} onFocus={() => setFocus(true)} onCommand={() => setCommandOpen(true)} onSettings={()=>setSettingsOpen(true)}/>
    {focus && <button className="exit-focus" onClick={() => setFocus(false)}><Minimize2 size={14}/> Exit focus</button>}
    {contextMenu&&<EditorContextMenu x={contextMenu.x} y={contextMenu.y} selected={selected} canPaste={clipboardCount>0} canUngroup={canUngroup} onClose={()=>setContextMenu(null)} onCut={()=>{copySelection();editor.deleteSelected();}} onCopy={copySelection} onPaste={paste} onDuplicate={editor.duplicateSelected} onDelete={editor.deleteSelected} onRename={(name)=>{const item=selected[0];if(item)patchOne(item.id,{name});}} onGroup={editor.group} onUngroup={editor.ungroup} onAutoLayout={()=>editor.autoLayoutSelection("horizontal",12,"start")} onToggleLock={()=>editor.commit((draft)=>{const locked=!selected.every((item)=>item.locked);draft.elements.forEach((item)=>{if(draft.selectedIds.includes(item.id))item.locked=locked;});},"Toggle Lock")} onToggleVisibility={()=>editor.commit((draft)=>{const hidden=!selected.every((item)=>item.hidden);draft.elements.forEach((item)=>{if(draft.selectedIds.includes(item.id))item.hidden=hidden;});},"Toggle Visibility")} onEditPath={()=>{const item=selected[0];if(item)enterPathEdit(item.id);}} onImport={()=>imageInput.current?.click()} onCreateFrame={()=>add("frame")} onRoblox={()=>setExportOpen(true)}/>}
    <section className="workspace" style={{ gridTemplateColumns: `${leftOpen && !focus ? leftWidth : 0}px minmax(320px,1fr) ${rightOpen && !focus ? rightWidth : 0}px` }}>
      {leftOpen && !focus && <><LayersPanel project={editor.project} robloxMode={interfaceUi.settings.workspaceMode==="roblox"} onSelect={(id, additive) => editor.select(id, additive)} onPatch={patchOne} onReorder={editor.reorder} onImportImages={(files)=>importImages(files,undefined,false)} onPlaceAsset={editor.placeAsset} onPlaceSvgVector={editor.placeSvgAsVector} onRenameAsset={editor.renameAsset} onAssetFolder={editor.setAssetFolder} onFavoriteAsset={editor.toggleFavoriteAsset} onCreateAssetFolder={editor.createAssetFolder} onApplyAssetFill={editor.applyAssetToSelection} onTogglePreset={editor.togglePreset} onFavoritePreset={editor.toggleFavoritePreset} onTestPreset={testPreset} onInsertFrame={insertFrame} onSaveFrame={(recipe)=>{editor.saveFrameRecipe(recipe);setNotice(`Saved ${recipe.name} to this project.`);window.setTimeout(()=>setNotice(""),3200);}} onApplyFont={applyFont} onFavoriteFont={editor.toggleFavoriteFont} onRerun={rerunHistory} onRestore={editor.restoreGeneration} onDuplicatePrompt={(entry)=>setPrompt(entry.prompt)}/><i className="panel-resizer left" onPointerDown={(event) => startPanelResize("left", event)}/></>}
      <CanvasStage project={editor.project} zoom={zoom} onZoomChange={setZoom} viewCommand={viewCommand} showGrid={showGrid} gridSize={gridSize} snapMode={snapMode} pixelSnap={pixelSnap} snapSettings={snapSettings} showGuides={showGuides} lockGuides={lockGuides} pathEditId={pathEditId} penActive={toolMode==="pen"} selectedPathNodeId={selectedPathNodeId} onPathEdit={enterPathEdit} onPathNodeSelect={setSelectedPathNodeId} onSelect={editor.select} onSetSelection={editor.setSelection} onBeginGesture={editor.beginHistoryTransaction} onTransient={editor.transient} onFinishGesture={editor.finishGesture} onRememberDuplicateTransform={editor.rememberDuplicateTransform} onImportImages={(files,position)=>importImages(files,position)} onPlaceAsset={editor.placeAsset}/>
      {rightOpen && !focus && <><i className="panel-resizer right" onPointerDown={(event) => startPanelResize("right", event)}/><Inspector project={editor.project} robloxMode={interfaceUi.settings.workspaceMode==="roblox"} inspectorMode={interfaceUi.settings.inspectorMode} inspectorCollapsed={interfaceUi.settings.inspectorCollapsed} inspectorPinned={interfaceUi.settings.inspectorPinned} onInspectorMode={(inspectorMode)=>interfaceUi.patch({inspectorMode})} onInspectorSections={interfaceUi.patch} onUpdate={editor.updateSelected} onScreenUpdate={(patch) => editor.commit((draft) => Object.assign(draft.screen, patch))} onBeginEdit={editor.beginHistoryTransaction} onCommitEdit={editor.finishGesture} onCancelEdit={editor.cancelHistoryTransaction} onEditPath={enterPathEdit} onBooleanOperation={changeBoolean} onFlattenBoolean={(id)=>editor.commit((draft)=>flattenBoolean(draft,id))} onReleaseBoolean={(id)=>editor.commit((draft)=>releaseBoolean(draft,id))}/></>}
      <ContextBar count={editor.project.selectedIds.length} keyObjectName={editor.project.elements.find((item)=>item.id===editor.project.selectedIds.at(-1))?.name} canUngroup={canUngroup} onAlign={editor.align} onDistribute={editor.distribute} onStack={editor.stack} onAutoLayout={editor.autoLayoutSelection} onRepeatGrid={editor.repeatGrid} onGroup={editor.group} onUngroup={editor.ungroup} onBoolean={runBoolean}/>
      <CanvasControls showGrid={showGrid} gridSize={gridSize} snapMode={snapMode} pixelSnap={pixelSnap} snapSettings={snapSettings} showGuides={showGuides} lockGuides={lockGuides} onShowGrid={setShowGrid} onGridSize={setGridSize} onSnapMode={setSnapMode} onPixelSnap={setPixelSnap} onSnapSettings={setSnapSettings} onShowGuides={setShowGuides} onLockGuides={setLockGuides}/>
    </section>
    {aiEnabled && !focus && <PromptWorkspace prompt={prompt} onPromptChange={setPrompt} references={editor.project.references} onAddReferences={editor.addReferences} onUpdateReference={editor.updateReference} onRemoveReference={editor.removeReference} onResearchPlan={(input)=>void researchAndPlan(input)} planning={planning} providerStatus={aiProviderStatus} onOpenAISettings={()=>setSettingsOpen(true)} onCancel={cancelAI}/>} {aiEnabled&&generationBadge&&<output className="generation-badge">{generationBadge}</output>} {notice && <output className="editor-notice">{notice}</output>}{aiEnabled&&<AIDebugPanel debug={aiDebug} onClose={()=>setAIDebug(null)}/>}
    <ProjectDialog open={projectsOpen} onOpenChange={setProjectsOpen} activeId={editor.project.id} currentName={editor.project.name} projects={editor.projects} recoveries={editor.recoveries} onCreate={editor.createNewProject} onOpen={editor.openProject} onRename={editor.renameProject} onDuplicate={editor.duplicateCurrent} onDelete={editor.removeProject} onImport={editor.importProject} onExport={exportStoredProject} onArchive={editor.archiveProject} onRecover={editor.recoverProject} onDiscardRecovery={editor.discardRecovery}/><CommandPalette open={commandOpen} onClose={() => setCommandOpen(false)} commands={commands}/>{aiEnabled&&<><DesignPlanDialog plan={plan} planning={planning} onPlanChange={setPlan} onGenerate={generatePlan} onCancel={()=>setPlan(null)} onResearchMore={()=>{const input=lastPlanInput??(plan?{prompt:plan.prompt,style:plan.style,mode:plan.mode,platform:plan.platform,accuracy:plan.accuracy,engine:"LOCAL"}:null);if(input)void researchAndPlan(input,true);}}/><AIDesignPlanDialog plan={aiPlan} generating={aiGenerating} events={aiEvents} onGenerate={()=>void generateAIPlan()} onCancel={cancelAI}/></>}<EditorSettingsDialog open={settingsOpen} settings={interfaceUi.settings} resolvedAppearance={interfaceUi.resolvedAppearance} themes={interfaceUi.themes} aiEnabled={aiEnabled} aiStatus={aiProviderStatus} referenceDetail={referenceDetail} onReferenceDetail={setReferenceDetail} onPatch={interfaceUi.patch} onSelectTheme={interfaceUi.selectTheme} onToggleFavoriteTheme={interfaceUi.toggleFavoriteTheme} onSaveCustomTheme={interfaceUi.saveCustomTheme} onClose={()=>setSettingsOpen(false)}/><RobloxExportDialog key={editor.project.id} open={exportOpen} project={editor.project} onClose={()=>setExportOpen(false)} onStudioStatusChange={setStudioStatus}/>
  </main>;
}
