"use client";

import { useState } from "react";
import { BookOpen, Check, ExternalLink, FlaskConical, Pencil, RefreshCw, ShieldCheck, X } from "lucide-react";
import { SYSTEM_PRESETS, PRESET_BY_ID } from "@/lib/design-intelligence/system-presets";
import { withResearchSourceExcluded } from "@/lib/design-intelligence/planner";
import type { DesignPlan, PresetRole } from "@/lib/design-intelligence/types";

type Props = { plan:DesignPlan|null; planning:boolean; onPlanChange:(plan:DesignPlan)=>void; onGenerate:()=>void; onResearchMore:()=>void; onCancel:()=>void };
const roles: PresetRole[] = ["structure","geometry","colors","typography","effects","spatial"];
const preserveLabels: [keyof DesignPlan["preservation"],string][] = [["layout","Layout"],["text","Text"],["geometry","Geometry"],["colors","Colors"],["typography","Typography"],["positions","Positions"],["sizes","Sizes"],["hierarchy","Hierarchy"],["effects","Effects"],["perspective","Perspective"]];

export function DesignPlanDialog({plan,planning,onPlanChange,onGenerate,onResearchMore,onCancel}:Props) {
  const [view,setView]=useState<"research"|"plan"|"sources">("plan"),[editing,setEditing]=useState(false); if(!plan)return null; const activeSources=plan.research.sources.filter((source)=>!source.excluded);
  return <div className="dialog-overlay" role="presentation"><section className="design-plan-dialog" role="dialog" aria-modal="true" aria-label="CreatorMake Design Plan">
    <header><div><span className="eyebrow">LOCAL GENERATOR PLAN</span><h2>{plan.prompt}</h2><p>Deterministic CreatorMake rules and templates · no external AI request</p></div><button className="dialog-close" aria-label="Cancel design plan" onClick={onCancel}><X size={18}/></button></header>
    <nav className="plan-tabs"><button className={view==="research"?"active":""} onClick={()=>setView("research")}><BookOpen size={14}/> Research</button><button className={view==="plan"?"active":""} onClick={()=>setView("plan")}><FlaskConical size={14}/> Plan</button><button className={view==="sources"?"active":""} onClick={()=>setView("sources")}><ShieldCheck size={14}/> Sources</button></nav>
    <div className="plan-body">
      {view==="research"&&<><div className={`research-status ${plan.research.status}`}><strong>{plan.research.status==="researched"?"Public research complete":plan.research.status==="bypassed"?"Research not required":"Offline preset fallback"}</strong><span>Searched for: {plan.research.query}</span></div><div className="trait-grid">{Object.entries(plan.research.traits).map(([key,values])=><article key={key}><span>{key}</span>{values.map((value)=><b key={value}>{value}</b>)}</article>)}</div><section className="preset-match"><span>CREATORMAKE PRESET MATCH</span><div>{plan.presetIds.map((id)=><strong key={id}>{PRESET_BY_ID[id]?.name??id}</strong>)}</div></section></>}
      {view==="plan"&&<><div className="plan-metrics"><span><b>{plan.createCount}</b> create</span><span><b>{plan.modifyCount}</b> modify</span><span><b>{activeSources.length}</b> sources</span><span><b>{plan.referenceIds.length}</b> references</span></div><section className="hierarchy-plan"><header><span>1 · HIERARCHY FIRST</span><strong>{plan.layoutKind}</strong></header><div className="hierarchy-tree">{(plan.hierarchy??[]).map((node)=><article key={node.id} style={{paddingLeft:`${Math.max(0,node.parentId?(plan.hierarchy??[]).find((item)=>item.id===node.parentId)?.parentId?24:12:0)}px`}}><b>{node.name}</b><span>{node.type} · {node.layout}</span><small>{node.sizing} · {node.constraints}</small></article>)}</div></section><section className="layout-plan"><header><span>2 · STRUCTURE TO STYLE</span></header>{(plan.layoutPlan??[]).map((step)=><article key={step.order}><b>{step.order}</b><span><strong>{step.stage}</strong><small>{step.detail}</small></span></article>)}</section><div className="decision-list">{plan.decisions.map((decision)=><article key={decision.category}><span>{decision.category}</span><strong>{decision.value}</strong><small>{decision.source}</small></article>)}</div><div className="assignment-grid">{roles.map((role)=><label key={role}><span>{role}</span>{editing?<select value={plan.assignments[role]} onChange={(event)=>onPlanChange({...plan,assignments:{...plan.assignments,[role]:event.target.value},presetIds:[...new Set([...plan.presetIds,event.target.value])]})}>{SYSTEM_PRESETS.map((preset)=><option key={preset.id} value={preset.id}>{preset.name}</option>)}</select>:<strong>{PRESET_BY_ID[plan.assignments[role]]?.name}</strong>}</label>)}</div><section className="preservation"><span>PRESERVE</span><div>{preserveLabels.map(([key,label])=><label key={key}><input type="checkbox" checked={plan.preservation[key]} disabled={!editing} onChange={(event)=>onPlanChange({...plan,preservation:{...plan.preservation,[key]:event.target.checked}})}/>{label}</label>)}</div></section>{plan.warnings.map((warning)=><p className="plan-warning" key={warning}>{warning}</p>)}</>}
      {view==="sources"&&<><section className="source-summary"><article><span>User references</span><strong>{plan.referenceIds.length}</strong></article><article><span>Research references</span><strong>{activeSources.length}</strong></article><article><span>System presets</span><strong>{plan.presetIds.length}</strong></article></section><div className="source-list">{plan.research.sources.length?plan.research.sources.map((source)=><article className={source.excluded?"excluded":""} key={source.id}><div><strong>{source.title}</strong><span>{source.provider}</span><p>{source.excerpt}</p></div><a href={source.url} target="_blank" rel="noreferrer" aria-label={`Open ${source.title}`}><ExternalLink size={13}/></a><button onClick={()=>onPlanChange(withResearchSourceExcluded(plan,source.id))}>{source.excluded?"Include":"Exclude"}</button></article>):<div className="empty-plan">No public sources were available. The plan names its preset fallback explicitly.</div>}</div></>}
    </div>
    <footer className="plan-actions"><button onClick={onCancel}>Cancel</button><button onClick={()=>setEditing((value)=>!value)}><Pencil size={13}/> {editing?"Finish Editing":"Edit Plan"}</button><button onClick={onResearchMore} disabled={planning}><RefreshCw size={13}/> Research More</button><button className="primary" onClick={onGenerate}><Check size={14}/> Generate With Local</button></footer>
  </section></div>;
}
