"use client";

import { useEffect, useState } from "react";
import { ChevronDown, ChevronRight, ChevronsDownUp, Circle, Eye, EyeOff, Filter, Frame, Hexagon, ImageIcon, Lock, LockOpen, Minus, Search, Square, Star, Type } from "lucide-react";
import type { EditorElement, EditorProject } from "@/lib/editor/types";
import type { FrameRecipe, SystemPreset } from "@/lib/design-intelligence/types";
import type { CreatorFont } from "@/lib/fonts/font-library";
import { FontBrowser, FrameBrowser, GenerationHistory, ReferenceBoard, SystemPresetBrowser } from "./IntelligencePanels";
import { AssetsPanel } from "./AssetsPanel";
import { classifyRobloxElement } from "@/lib/roblox/classification";

type Props = { project: EditorProject; robloxMode?:boolean; onSelect: (id: string, additive?: boolean) => void; onPatch: (id: string, patch: Partial<EditorElement>) => void; onReorder: (id: string, direction: -1 | 1) => void; onImportImages:(files:Iterable<File>)=>Promise<unknown>;onPlaceAsset:(assetId:string,position?:{x:number;y:number},asButton?:boolean)=>void;onPlaceSvgVector:(assetId:string)=>void;onRenameAsset:(assetId:string,name:string)=>void;onAssetFolder:(assetId:string,folder:string)=>void;onFavoriteAsset:(assetId:string)=>void;onCreateAssetFolder:(name:string)=>void;onApplyAssetFill:(assetId:string)=>void; onTogglePreset:(id:string)=>void; onFavoritePreset:(id:string)=>void; onTestPreset:(preset:SystemPreset)=>void; onInsertFrame:(recipe:FrameRecipe)=>void; onSaveFrame:(recipe:FrameRecipe)=>void; onApplyFont:(font:CreatorFont,weight:number,style:"normal"|"italic")=>void; onFavoriteFont:(id:string)=>void; onRerun:(entry:EditorProject["generationHistory"][number])=>void; onRestore:(entry:EditorProject["generationHistory"][number])=>void; onDuplicatePrompt:(entry:EditorProject["generationHistory"][number])=>void };
const icons = { frame: Frame, container: Frame, "scrolling-frame": Frame, text: Type, rectangle: Square, roundRect: Square, ellipse: Circle, line: Minus, polygon: Hexagon, star: Star, button: Square, vector: Hexagon, image:ImageIcon,"image-button":ImageIcon };
const ancestorDepth=(elements:EditorElement[],element:EditorElement)=>{let depth=0,parent=element.parentId;while(parent&&depth<8){depth+=1;parent=elements.find((item)=>item.id===parent)?.parentId??null;}return depth;};

export function LayersPanel({ project, robloxMode=false, onSelect, onPatch, onReorder, onImportImages,onPlaceAsset,onPlaceSvgVector,onRenameAsset,onAssetFolder,onFavoriteAsset,onCreateAssetFolder,onApplyAssetFill,onTogglePreset, onFavoritePreset, onTestPreset, onInsertFrame, onSaveFrame, onApplyFont, onFavoriteFont, onRerun, onRestore, onDuplicatePrompt }: Props) {
  const [tab,setTab]=useState("layers"),[query,setQuery]=useState(""),[filter,setFilter]=useState<"all"|"frames"|"text"|"images"|"vectors"|"locked"|"hidden">("all"),[collapsed,setCollapsed]=useState<string[]>([]),[editingId,setEditingId]=useState<string|null>(null);
  useEffect(()=>{const rename=(event:KeyboardEvent)=>{if(event.key!=="F2"||["INPUT","TEXTAREA","SELECT"].includes((event.target as HTMLElement)?.tagName))return;if(project.selectedIds.length===1){event.preventDefault();setEditingId(project.selectedIds[0]);}};window.addEventListener("keydown",rename);return()=>window.removeEventListener("keydown",rename);},[project.selectedIds]);
  const matchesFilter=(item:EditorElement)=>filter==="all"||filter==="frames"&&["frame","container","scrolling-frame"].includes(item.type)||filter==="text"&&item.type==="text"||filter==="images"&&["image","image-button"].includes(item.type)||filter==="vectors"&&["vector","rectangle","roundRect","ellipse","line","polygon","star"].includes(item.type)||filter==="locked"&&item.locked||filter==="hidden"&&item.hidden;
  const belowCollapsed=(item:EditorElement)=>{if(query)return false;let parent=item.parentId;while(parent){if(collapsed.includes(parent))return true;parent=project.elements.find((candidate)=>candidate.id===parent)?.parentId??null;}return false;};
  const visibleLayers=project.elements.filter((item)=>item.name.toLowerCase().includes(query.toLowerCase())&&matchesFilter(item)&&!belowCollapsed(item));
  const parentIds=[...new Set(project.elements.map((item)=>item.parentId).filter((id):id is string=>Boolean(id)))];
  const expandSelection=()=>{const ancestors=new Set<string>();project.selectedIds.forEach((id)=>{let parent=project.elements.find((item)=>item.id===id)?.parentId??null;while(parent){ancestors.add(parent);parent=project.elements.find((item)=>item.id===parent)?.parentId??null;}});setCollapsed((items)=>items.filter((id)=>!ancestors.has(id)));};
  return <aside className="left-panel"><div className="panel-tabs">
      <div className="tabs-list" role="tablist">
        {['Layers','Assets','Frames','Fonts','Components','Templates','Styles','References','History'].map((item) => <button key={item} role="tab" aria-selected={tab === item.toLowerCase()} className={tab === item.toLowerCase() ? "active" : ""} onClick={() => setTab(item.toLowerCase())}>{item}</button>)}
      </div>
      {tab === "layers" ? <div className="layers-content">
        <div className="panel-heading"><span>Layers <small>{visibleLayers.length}/{project.elements.length}</small></span><div><button title="Collapse all groups" aria-label="Collapse all groups" onClick={()=>setCollapsed(parentIds)}><ChevronsDownUp size={14}/></button><button title="Expand selected hierarchy" aria-label="Expand selected hierarchy" onClick={expandSelection}><ChevronDown size={14}/></button></div></div><div className="layer-toolbar"><label className="layer-search"><Search size={12}/><input aria-label="Filter layers" placeholder="Filter layers" value={query} onChange={(event)=>setQuery(event.target.value)}/></label><label className="layer-type-filter"><Filter size={11}/><select aria-label="Layer type filter" value={filter} onChange={(event)=>setFilter(event.target.value as typeof filter)}><option value="all">All</option><option value="frames">Frames</option><option value="text">Text</option><option value="images">Images</option><option value="vectors">Vectors</option><option value="locked">Locked</option><option value="hidden">Hidden</option></select></label></div>
        <div className="screen-row"><ChevronDown size={13}/><Frame size={14}/><span>{project.screen.name}</span></div>
        <div className="layer-list">
          {!visibleLayers.length&&<div className="empty-panel"><span>{project.elements.length?"No matching layers":"Blank canvas"}</span><p>{project.elements.length?"Clear the filter to see your objects.":"Create a frame, text layer, shape, or import an image to begin."}</p></div>}
          {[...visibleLayers].reverse().map((element)=>{const Icon=icons[element.type],selected=project.selectedIds.includes(element.id),hasChildren=project.elements.some((item)=>item.parentId===element.id),isCollapsed=collapsed.includes(element.id),roblox=classifyRobloxElement(element),badge=roblox.classification==="RASTERIZED"?"P":roblox.classification==="HYBRID"?"H":"N";return <div key={element.id} className={`layer ${selected?"selected":""} ${element.parentId?"nested":""}`} style={{paddingLeft:25+ancestorDepth(project.elements,element)*12}} onClick={(event)=>onSelect(element.id,event.shiftKey)} onDoubleClick={()=>setEditingId(element.id)}>
            <button className="disclosure" aria-label={hasChildren?`${isCollapsed?"Expand":"Collapse"} ${element.name}`:`Select ${element.name}`} onClick={(event)=>{if(!hasChildren)return;event.stopPropagation();setCollapsed((items)=>items.includes(element.id)?items.filter((id)=>id!==element.id):[...items,element.id]);}}>{hasChildren?(isCollapsed?<ChevronRight size={11}/>:<ChevronDown size={11}/>):<i/>}</button><Icon size={13}/>{editingId===element.id?<input className="layer-rename" autoFocus defaultValue={element.name} onClick={(event)=>event.stopPropagation()} onBlur={(event)=>{onPatch(element.id,{name:event.target.value.trim()||element.name});setEditingId(null);}} onKeyDown={(event)=>{if(event.key==="Enter")event.currentTarget.blur();if(event.key==="Escape")setEditingId(null);}}/>:<span>{element.name}</span>}<small className={`layer-roblox-badge ${roblox.classification.toLowerCase()}`} title={`${roblox.classification==="RASTERIZED"?"PIXEL ACCURATE":roblox.classification} · ${roblox.intendedRobloxClass}${roblox.reasons[0]?` · ${roblox.reasons[0]}`:""}`}>{badge}</small>
            <div className="layer-actions">
              <button aria-label={element.hidden ? "Show layer" : "Hide layer"} onClick={(event) => { event.stopPropagation(); onPatch(element.id, { hidden: !element.hidden }); }}>{element.hidden ? <EyeOff size={12}/> : <Eye size={12}/>}</button>
              <button aria-label={element.locked ? "Unlock layer" : "Lock layer"} onClick={(event) => { event.stopPropagation(); onPatch(element.id, { locked: !element.locked }); }}>{element.locked ? <Lock size={12}/> : <LockOpen size={12}/>}</button>
            </div>
          </div>;})}
        </div>
        {project.selectedIds.length === 1 && <div className="layer-order"><button onClick={() => onReorder(project.selectedIds[0], 1)}>Bring forward</button><button onClick={() => onReorder(project.selectedIds[0], -1)}>Send backward</button></div>}
      </div> : tab === "assets" ? <AssetsPanel assets={project.assets} folders={project.assetFolders} onImport={onImportImages} onPlace={onPlaceAsset} onPlaceVector={onPlaceSvgVector} onRename={onRenameAsset} onFolder={onAssetFolder} onFavorite={onFavoriteAsset} onCreateFolder={onCreateAssetFolder} onApplyFill={onApplyAssetFill}/> : tab === "frames" ? <FrameBrowser custom={project.customFrameRecipes} onInsert={onInsertFrame} onSave={onSaveFrame}/> : tab === "fonts" ? <FontBrowser robloxMode={robloxMode} favorites={project.favoriteFontIds} recent={project.recentFontIds} projectFonts={[...new Set(project.elements.map((item)=>item.fontFamily))]} selectedText={project.elements.find((item)=>project.selectedIds.includes(item.id))?.text??""} onApply={onApplyFont} onFavorite={onFavoriteFont}/> : tab === "styles" ? <SystemPresetBrowser active={project.activePresetIds} favorites={project.favoritePresetIds} onToggle={onTogglePreset} onFavorite={onFavoritePreset} onTest={onTestPreset}/> : tab === "references" ? <ReferenceBoard references={project.references}/> : tab === "history" ? <GenerationHistory entries={project.generationHistory} onRerun={onRerun} onRestore={onRestore} onDuplicate={onDuplicatePrompt}/> : <div className="empty-panel"><span>{tab}</span><p>Available in a later CreatorMake phase.</p></div>}
    </div>
  </aside>;
}
