"use client";

import { useEffect, useMemo, useRef, useState, type CSSProperties, type DragEvent, type ReactNode } from "react";
import { BoxSelect, ChevronDown, ChevronRight, ChevronsDownUp, Circle, Component, Eye, EyeOff, Filter, Frame, Grid3X3, Hexagon, ImageIcon, ImageUp, IndentIncrease, ListTree, Lock, LockOpen, Minus, MousePointerClick, PanelTop, Search, Square, Star, Type } from "lucide-react";
import type { CommissionBrief, EditorElement, EditorProject } from "@/lib/editor/types";
import type { FrameRecipe, SystemPreset } from "@/lib/design-intelligence/types";
import type { FontSelection } from "./IntelligencePanels";
import type { LayerDropPosition, LayerReparentRequest, LayerReparentResult } from "@/lib/editor/operations";
import { canContainChildren, validateLayerReparent } from "@/lib/editor/operations";
import { CommissionBriefPanel, FontBrowser, FrameBrowser, GenerationHistory, ReferenceBoard, SystemPresetBrowser } from "./IntelligencePanels";
import { AssetsPanel } from "./AssetsPanel";
import { classifyRobloxElement } from "@/lib/roblox/classification";

type LayerFilter="all"|"frames"|"text"|"buttons"|"images"|"vectors"|"locked"|"hidden"|"roblox-native"|"pixel-accurate";
type Props = { project:EditorProject;robloxMode?:boolean;onSelect:(id:string,additive?:boolean)=>void;onPatch:(id:string,patch:Partial<EditorElement>)=>void;onReorder:(id:string,direction:-1|1)=>void;onReparent:(request:LayerReparentRequest)=>LayerReparentResult;onIndent:()=>LayerReparentResult;onOutdent:()=>LayerReparentResult;onCommissionBrief:(patch:Partial<CommissionBrief>)=>void;onImportImages:(files:Iterable<File>)=>Promise<unknown>;onPlaceAsset:(assetId:string,position?:{x:number;y:number},asButton?:boolean)=>void;onPlaceSvgVector:(assetId:string)=>void;onRenameAsset:(assetId:string,name:string)=>void;onAssetFolder:(assetId:string,folder:string)=>void;onFavoriteAsset:(assetId:string)=>void;onCreateAssetFolder:(name:string)=>void;onApplyAssetFill:(assetId:string)=>void;onTogglePreset:(id:string)=>void;onFavoritePreset:(id:string)=>void;onTestPreset:(preset:SystemPreset)=>void;onInsertFrame:(recipe:FrameRecipe)=>void;onSaveFrame:(recipe:FrameRecipe)=>void;onApplyFont:(font:FontSelection,weight:number,style:"normal"|"italic")=>void;onFavoriteFont:(id:string)=>void;onRerun:(entry:EditorProject["generationHistory"][number])=>void;onRestore:(entry:EditorProject["generationHistory"][number])=>void;onDuplicatePrompt:(entry:EditorProject["generationHistory"][number])=>void};

const icons:Record<EditorElement["type"],typeof Frame>={frame:Frame,container:BoxSelect,"scrolling-frame":PanelTop,text:Type,rectangle:Square,roundRect:Square,ellipse:Circle,line:Minus,polygon:Hexagon,star:Star,button:MousePointerClick,vector:Hexagon,image:ImageIcon,"image-button":ImageUp};
const ancestorIds=(elements:EditorElement[],id:string)=>{const result:string[]=[];let parent=elements.find((item)=>item.id===id)?.parentId??null;while(parent&&result.length<64){result.unshift(parent);parent=elements.find((item)=>item.id===parent)?.parentId??null;}return result;};

export function LayersPanel({project,robloxMode=false,onSelect,onPatch,onReorder,onReparent,onIndent,onOutdent,onCommissionBrief,onImportImages,onPlaceAsset,onPlaceSvgVector,onRenameAsset,onAssetFolder,onFavoriteAsset,onCreateAssetFolder,onApplyAssetFill,onTogglePreset,onFavoritePreset,onTestPreset,onInsertFrame,onSaveFrame,onApplyFont,onFavoriteFont,onRerun,onRestore,onDuplicatePrompt}:Props){
  const [tab,setTab]=useState("layers"),[query,setQuery]=useState(""),[filter,setFilter]=useState<LayerFilter>("all"),[collapsed,setCollapsed]=useState<string[]>([]),[editingId,setEditingId]=useState<string|null>(null),[dragIds,setDragIds]=useState<string[]>([]),[drop,setDrop]=useState<{targetId:string|null;position:LayerDropPosition}|null>(null),[message,setMessage]=useState(""),[preserveWorld,setPreserveWorld]=useState(true);
  const listRef=useRef<HTMLDivElement>(null),hoverTimer=useRef<number|null>(null);
  useEffect(()=>{if(project.projectKind!=="commission"&&tab==="brief")setTab("layers");},[project.id,project.projectKind,tab]);
  useEffect(()=>{const rename=(event:KeyboardEvent)=>{if(event.key!=="F2"||["INPUT","TEXTAREA","SELECT"].includes((event.target as HTMLElement)?.tagName))return;if(project.selectedIds.length===1){event.preventDefault();setEditingId(project.selectedIds[0]);}};window.addEventListener("keydown",rename);return()=>window.removeEventListener("keydown",rename);},[project.selectedIds]);
  useEffect(()=>()=>{if(hoverTimer.current!==null)window.clearTimeout(hoverTimer.current);},[]);
  useEffect(()=>{if(tab!=="layers"||!project.selectedIds.length)return;const ancestors=new Set(project.selectedIds.flatMap((id)=>ancestorIds(project.elements,id)));setCollapsed((items)=>{const next=items.filter((id)=>!ancestors.has(id));return next.length===items.length?items:next;});const active=project.selectedIds.at(-1);const frame=window.requestAnimationFrame(()=>{const row=active?listRef.current?.querySelector<HTMLElement>(`[data-layer-id="${CSS.escape(active)}"]`):null;row?.scrollIntoView({block:"nearest"});});return()=>window.cancelAnimationFrame(frame);},[project.elements,project.selectedIds,tab]);
  const order=useMemo(()=>new Map(project.elements.map((item,index)=>[item.id,index])),[project.elements]);
  const sorted=useMemo(()=>[...project.elements].sort((a,b)=>b.zIndex-a.zIndex||(order.get(b.id)??0)-(order.get(a.id)??0)),[project.elements,order]);
  const matchesFilter=(item:EditorElement)=>{const roblox=classifyRobloxElement(item);return filter==="all"||filter==="frames"&&["frame","container","scrolling-frame"].includes(item.type)||filter==="text"&&item.type==="text"||filter==="buttons"&&["button","image-button"].includes(item.type)||filter==="images"&&["image","image-button"].includes(item.type)||filter==="vectors"&&["vector","rectangle","roundRect","ellipse","line","polygon","star"].includes(item.type)||filter==="locked"&&item.locked||filter==="hidden"&&item.hidden||filter==="roblox-native"&&roblox.classification==="NATIVE"||filter==="pixel-accurate"&&roblox.classification==="RASTERIZED";};
  const visibleSet=useMemo(()=>{const direct=project.elements.filter((item)=>item.name.toLowerCase().includes(query.toLowerCase())&&matchesFilter(item)),ids=new Set(direct.map((item)=>item.id));direct.forEach((item)=>ancestorIds(project.elements,item.id).forEach((id)=>ids.add(id)));return ids;},[project.elements,query,filter]); // eslint-disable-line react-hooks/exhaustive-deps
  const parentIds=[...new Set(project.elements.map((item)=>item.parentId).filter((id):id is string=>Boolean(id)))];
  const expandSelection=()=>{const ancestors=new Set(project.selectedIds.flatMap((id)=>ancestorIds(project.elements,id)));setCollapsed((items)=>items.filter((id)=>!ancestors.has(id)));};
  const finishDrop=(request:LayerReparentRequest)=>{const result=onReparent({...request,keepLocalPosition:!preserveWorld});setMessage(result.ok?`${result.movedIds.length} layer${result.movedIds.length===1?"":"s"} moved · ${preserveWorld?"world position preserved":"local coordinates preserved"}.`:result.reason??"The layers could not be moved.");setDrop(null);setDragIds([]);window.setTimeout(()=>setMessage(""),3600);};
  const dragOver=(event:DragEvent,target:EditorElement|null)=>{if(!dragIds.length)return;event.preventDefault();event.dataTransfer.dropEffect="move";const rect=(event.currentTarget as HTMLElement).getBoundingClientRect(),ratio=(event.clientY-rect.top)/Math.max(1,rect.height);let position:LayerDropPosition=target&&canContainChildren(target)&&ratio>=.28&&ratio<=.72?"inside":ratio<.5?"before":"after";if(!target)position="inside";const request={draggedIds:dragIds,targetId:target?.id??null,position},validation=validateLayerReparent(project,request);if(!validation.ok){event.dataTransfer.dropEffect="none";setDrop(null);setMessage(validation.reason??"");return;}setDrop({targetId:target?.id??null,position});if(target&&position==="inside"&&collapsed.includes(target.id)){if(hoverTimer.current!==null)window.clearTimeout(hoverTimer.current);hoverTimer.current=window.setTimeout(()=>setCollapsed((items)=>items.filter((id)=>id!==target.id)),560);}const list=listRef.current;if(list){const bounds=list.getBoundingClientRect(),edge=34;if(event.clientY<bounds.top+edge)list.scrollBy({top:-18});else if(event.clientY>bounds.bottom-edge)list.scrollBy({top:18});}};
  const startDrag=(event:DragEvent,element:EditorElement)=>{if(element.locked){event.preventDefault();setMessage("Unlock this layer before moving it.");return;}const ids=project.selectedIds.includes(element.id)?project.selectedIds:[element.id];if(!project.selectedIds.includes(element.id))onSelect(element.id);setDragIds(ids);event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("application/x-creatormake-layers",ids.join(","));};
  const layoutInstances=(element:EditorElement,depth:number):ReactNode=>{const rows:Array<{name:string;Icon:typeof Frame}>=[];if(element.layoutMode==="grid")rows.push({name:"UIGridLayout",Icon:Grid3X3});else if(element.layoutMode!=="none")rows.push({name:"UIListLayout",Icon:ListTree});if(element.padding>0||Object.values(element.layoutPadding).some((value)=>value>0))rows.push({name:"UIPadding",Icon:PanelTop});return rows.map(({name,Icon})=><div key={`${element.id}:${name}`} className="layer layer-instance" style={{paddingLeft:13+Math.min(depth,12)*14}} title={`${name} is generated as a real Roblox layout child during export.`}><span className="disclosure"><i/></span><Icon size={13}/><span>{name}</span><small>generated</small></div>);};
  const renderRows=(parentId:string|null,depth=0):ReactNode=>sorted.filter((item)=>item.parentId===parentId&&visibleSet.has(item.id)).map((element)=>{const Icon=icons[element.type]??Component,selected=project.selectedIds.includes(element.id),hasElementChildren=project.elements.some((item)=>item.parentId===element.id),hasLayoutChildren=element.layoutMode!=="none"||element.padding>0||Object.values(element.layoutPadding).some((value)=>value>0),hasChildren=hasElementChildren||hasLayoutChildren,isCollapsed=collapsed.includes(element.id),roblox=classifyRobloxElement(element),badge=roblox.classification==="RASTERIZED"?"P":roblox.classification==="HYBRID"?"H":"N",dropPosition=drop?.targetId===element.id?drop.position:null;return <div key={element.id} className="layer-tree-node"><div draggable={!element.locked} data-layer-id={element.id} className={`layer ${selected?"selected":""} ${depth?"nested":""} ${dropPosition?`drop-${dropPosition}`:""}`} style={{paddingLeft:13+Math.min(depth,12)*14,"--layer-indent":`${9+Math.min(depth,12)*14}px`} as CSSProperties} onDragStart={(event)=>startDrag(event,element)} onDragEnd={()=>{setDrop(null);setDragIds([]);}} onDragOver={(event)=>dragOver(event,element)} onDrop={(event)=>{event.preventDefault();event.stopPropagation();if(drop)finishDrop({draggedIds:dragIds,targetId:element.id,position:drop.position});}} onClick={(event)=>onSelect(element.id,event.shiftKey)} onDoubleClick={()=>setEditingId(element.id)}>
    <button className="disclosure" aria-label={hasChildren?`${isCollapsed?"Expand":"Collapse"} ${element.name}`:`Select ${element.name}`} onClick={(event)=>{if(!hasChildren)return;event.stopPropagation();setCollapsed((items)=>items.includes(element.id)?items.filter((id)=>id!==element.id):[...items,element.id]);}}>{hasChildren?(isCollapsed?<ChevronRight size={11}/>:<ChevronDown size={11}/>):<i/>}</button><Icon size={13}/>{editingId===element.id?<input className="layer-rename" autoFocus defaultValue={element.name} onClick={(event)=>event.stopPropagation()} onBlur={(event)=>{onPatch(element.id,{name:event.target.value.trim()||element.name});setEditingId(null);}} onKeyDown={(event)=>{if(event.key==="Enter")event.currentTarget.blur();if(event.key==="Escape")setEditingId(null);}}/>:<span>{element.name}</span>}<small className={`layer-roblox-badge ${roblox.classification.toLowerCase()}`} title={`${roblox.classification==="RASTERIZED"?"PIXEL ACCURATE":roblox.classification} · ${roblox.intendedRobloxClass}`}>{badge}</small><div className="layer-actions"><button aria-label={element.hidden?"Show layer":"Hide layer"} onClick={(event)=>{event.stopPropagation();onPatch(element.id,{hidden:!element.hidden});}}>{element.hidden?<EyeOff size={12}/>:<Eye size={12}/>}</button><button aria-label={element.locked?"Unlock layer":"Lock layer"} onClick={(event)=>{event.stopPropagation();onPatch(element.id,{locked:!element.locked});}}>{element.locked?<Lock size={12}/>:<LockOpen size={12}/>}</button></div>{dropPosition&&<em className="layer-drop-label">Drop {dropPosition}</em>}</div>{hasChildren&&!isCollapsed&&<>{hasElementChildren&&renderRows(element.id,depth+1)}{hasLayoutChildren&&layoutInstances(element,depth+1)}</>}</div>;});
  const selected=project.selectedIds.length===1?project.elements.find((item)=>item.id===project.selectedIds[0]):null,breadcrumb=selected?[project.screen.name,...ancestorIds(project.elements,selected.id).map((id)=>project.elements.find((item)=>item.id===id)?.name??"?"),selected.name]:[];

  return <aside className="left-panel"><div className="panel-tabs"><div className="tabs-list" role="tablist">{["Layers","Assets",...(project.projectKind==="commission"?["Brief"]:[]),"Frames","Fonts","Components","Templates","Styles","References","History"].map((item)=><button key={item} role="tab" aria-selected={tab===item.toLowerCase()} className={tab===item.toLowerCase()?"active":""} onClick={()=>setTab(item.toLowerCase())}>{item}</button>)}</div>
  {tab==="layers"?<div className="layers-content"><div className="panel-heading"><span>Layers <small>{visibleSet.size}/{project.elements.length}</small></span><div><button title="Collapse all groups" aria-label="Collapse all groups" onClick={()=>setCollapsed(parentIds)}><ChevronsDownUp size={14}/></button><button title="Expand selected hierarchy" aria-label="Expand selected hierarchy" onClick={expandSelection}><ChevronDown size={14}/></button></div></div><div className="layer-toolbar"><label className="layer-search"><Search size={12}/><input aria-label="Filter layers" placeholder="Filter layers" value={query} onChange={(event)=>setQuery(event.target.value)}/></label><label className="layer-type-filter"><Filter size={11}/><select aria-label="Layer type filter" value={filter} onChange={(event)=>setFilter(event.target.value as LayerFilter)}><option value="all">All</option><option value="frames">Frames</option><option value="text">Text</option><option value="buttons">Buttons</option><option value="images">Images</option><option value="vectors">Vectors</option><option value="locked">Locked</option><option value="hidden">Hidden</option><option value="roblox-native">Roblox Native</option><option value="pixel-accurate">Pixel Accurate</option></select></label><label className="layer-reparent-mode" title="Choose whether reparenting keeps the canvas position or the child-local X/Y values."><input type="checkbox" checked={preserveWorld} onChange={(event)=>setPreserveWorld(event.target.checked)}/> Preserve world position</label></div>
    {breadcrumb.length>1&&<nav className="layer-breadcrumb" aria-label="Selected layer hierarchy">{breadcrumb.map((name,index)=><span key={`${name}_${index}`}>{index>0&&<b>›</b>}{name}</span>)}</nav>}
    {robloxMode&&<div className="studio-service-row"><ChevronDown size={13}/><BoxSelect size={14}/><span>StarterGui preview</span></div>}<div className={`screen-row ${robloxMode?"studio-screen-gui":""} ${drop?.targetId===null?"drop-inside":""}`} onDragOver={(event)=>dragOver(event,null)} onDrop={(event)=>{event.preventDefault();finishDrop({draggedIds:dragIds,targetId:null,position:"inside"});}}><ChevronDown size={13}/><Frame size={14}/><span>{robloxMode?`${project.name.replace(/[^a-z0-9]+/gi,"")} [ScreenGui]`:project.screen.name}</span>{drop?.targetId===null&&<em>Drop inside screen</em>}</div>
    <div ref={listRef} className="layer-list">{!visibleSet.size&&<div className="empty-panel"><span>{project.elements.length?"No matching layers":"Blank canvas"}</span><p>{project.elements.length?"Clear the filter to see your objects.":"Create a frame, text layer, shape, or import an image to begin."}</p></div>}{renderRows(null)}</div>
    {message&&<output className="layer-message">{message}</output>}<div className="layer-order"><button disabled={!project.selectedIds.length} onClick={()=>{const result=onIndent();setMessage(result.reason??"Moved into the previous container.");}}><IndentIncrease size={11}/> Move Into</button><button disabled={!project.selectedIds.length} onClick={()=>{const result=onOutdent();setMessage(result.reason??"Moved out one level.");}}><IndentIncrease size={11} style={{transform:"scaleX(-1)"}}/> Move Out</button>{project.selectedIds.length===1&&<><button onClick={()=>onReorder(project.selectedIds[0],1)}>Bring forward</button><button onClick={()=>onReorder(project.selectedIds[0],-1)}>Send backward</button></>}</div>
  </div>:tab==="assets"?<AssetsPanel assets={project.assets} folders={project.assetFolders} onImport={onImportImages} onPlace={onPlaceAsset} onPlaceVector={onPlaceSvgVector} onRename={onRenameAsset} onFolder={onAssetFolder} onFavorite={onFavoriteAsset} onCreateFolder={onCreateAssetFolder} onApplyFill={onApplyAssetFill}/>:tab==="brief"?<CommissionBriefPanel projectName={project.name} brief={project.commissionBrief} onChange={onCommissionBrief}/>:tab==="frames"?<FrameBrowser custom={project.customFrameRecipes} onInsert={onInsertFrame} onSave={onSaveFrame}/>:tab==="fonts"?<FontBrowser robloxMode={robloxMode} favorites={project.favoriteFontIds} recent={project.recentFontIds} projectFonts={[...new Set(project.elements.map((item)=>item.fontFamily))]} selectedText={project.elements.find((item)=>project.selectedIds.includes(item.id))?.text??""} onApply={onApplyFont} onFavorite={onFavoriteFont}/>:tab==="styles"?<SystemPresetBrowser active={project.activePresetIds} favorites={project.favoritePresetIds} onToggle={onTogglePreset} onFavorite={onFavoritePreset} onTest={onTestPreset}/>:tab==="references"?<ReferenceBoard references={project.references}/>:tab==="history"?<GenerationHistory entries={project.generationHistory} onRerun={onRerun} onRestore={onRestore} onDuplicate={onDuplicatePrompt}/>:<div className="empty-panel"><span>{tab}</span><p>Available in a later CreatorMake phase.</p></div>}</div></aside>;
}
