"use client";

import { useCallback, useMemo, useState } from "react";
import { RotateCcw, Search, Star, Zap } from "lucide-react";
import type { EditorElement, ProjectExportOptions } from "@/lib/editor/types";
import { applyProjectOptionPreset, DEFAULT_PROJECT_EXPORT_OPTIONS } from "@/lib/editor/options";
import { isDirectionalCaptionGeometry } from "@/lib/editor/geometry";
import { CheckboxField, NumberField, SelectField } from "./PropertyControls";

type EditorOptions={previewQuality:"PERFORMANCE"|"BALANCED"|"HIGH";showGeneratedObjects:boolean;smartGuideDetail:"MINIMAL"|"NORMAL"|"DETAILED";optionFavorites:string[]};
type Props={selected:EditorElement;projectOptions:ProjectExportOptions;editorOptions:EditorOptions;onObject:(patch:Partial<EditorElement>)=>void;onProject:(patch:Partial<ProjectExportOptions>)=>void;onEditor:(patch:Partial<EditorOptions>)=>void};
type Scope="OBJECT"|"PROJECT"|"EDITOR";
type OptionDefinition={id:string;label:string;group:"EXPORT"|"TEXT"|"IMAGES"|"ROBLOX"|"LAYOUT"|"EDITOR"|"PERFORMANCE"|"DEBUG / ADVANCED";scope:Scope;keywords:string;render:()=>React.ReactNode};
const labelize=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/(^|\s)\w/g,(letter)=>letter.toUpperCase());

export function OptionsSection({selected,projectOptions,editorOptions,onObject,onProject,onEditor}:Props){
  const [query,setQuery]=useState("");
  const [recentIds,setRecentIds]=useState<string[]>([]);
  const recordRecent=useCallback((id:string)=>setRecentIds((current)=>[id,...current.filter((entry)=>entry!==id)].slice(0,5)),[]);
  const projectPatch=useCallback((patch:Partial<ProjectExportOptions>)=>onProject({...patch,preset:"CUSTOM"}),[onProject]);
  const toggleFavorite=(id:string)=>onEditor({optionFavorites:editorOptions.optionFavorites.includes(id)?editorOptions.optionFavorites.filter((entry)=>entry!==id):[...editorOptions.optionFavorites,id]});
  const definitions=useMemo<OptionDefinition[]>(()=>{
    const select=(id:string,label:string,group:OptionDefinition["group"],scope:Scope,value:string,values:string[],change:(value:string)=>void,hint:string,keywords="")=>({id,label,group,scope,keywords:`${label} ${hint} ${keywords}`,render:()=> <SelectField label={label} value={value} options={values.map((entry)=>({value:entry,label:labelize(entry)}))} scope={scope} hint={hint} onChange={(next)=>{recordRecent(id);change(next);}}/>});
    const toggle=(id:string,label:string,group:OptionDefinition["group"],scope:Scope,value:boolean,change:(value:boolean)=>void,hint:string,keywords="")=>({id,label,group,scope,keywords:`${label} ${hint} ${keywords}`,render:()=> <CheckboxField label={label} checked={value} scope={scope} hint={hint} onChange={(next)=>{recordRecent(id);change(next);}}/>});
    return[
      toggle("nativeTextLabelExport","Native TextLabel Export","TEXT","PROJECT",projectOptions.nativeTextLabelExport,(nativeTextLabelExport)=>projectPatch({nativeTextLabelExport}),"Keeps visible captions editable and excludes glyphs from rendered backgrounds.","text caption button"),
      select("renderedVisualQuality","Rendered Visual Quality","EXPORT","PROJECT",projectOptions.renderedVisualQuality,["DRAFT","STANDARD","HIGH","ULTRA","MAXIMUM_SAFE"],(renderedVisualQuality)=>projectPatch({renderedVisualQuality:renderedVisualQuality as ProjectExportOptions["renderedVisualQuality"]}),"Controls real background supersampling. Ultra renders at 4×; Maximum Safe requests up to 8×.","quality button texture"),
      select("pixelAccurateBackgrounds","Pixel Accurate Backgrounds","EXPORT","PROJECT",projectOptions.pixelAccurateBackgrounds,["AUTO","ON","OFF"],(pixelAccurateBackgrounds)=>projectPatch({pixelAccurateBackgrounds:pixelAccurateBackgrounds as ProjectExportOptions["pixelAccurateBackgrounds"]}),"Uses pixel visuals only where geometry or effects require them.","raster native"),
      select("internalRenderScale","Internal Render Scale","PERFORMANCE","PROJECT",projectOptions.internalRenderScale,["AUTO","1","2","3","4","6","8"],(internalRenderScale)=>projectPatch({internalRenderScale:internalRenderScale as ProjectExportOptions["internalRenderScale"]}),"Overrides quality supersampling. Unsafe sizes are clamped with a visible warning.","scale supersampling"),
      select("imageResampling","Image Resampling","IMAGES","PROJECT",projectOptions.imageResampling,["PERFORMANCE","BALANCED","BEST_QUALITY"],(imageResampling)=>projectPatch({imageResampling:imageResampling as ProjectExportOptions["imageResampling"]}),"Selects export filtering for transparent visual assets.","quality filter"),
      select("backgroundExport","Background Export","EXPORT","PROJECT",projectOptions.backgroundExport,["AUTO","PREFER_NATIVE","PREFER_PIXEL","FORCE_PIXEL"],(backgroundExport)=>projectPatch({backgroundExport:backgroundExport as ProjectExportOptions["backgroundExport"]}),"Chooses native or pixel backgrounds without changing native text captions.","visual image"),
      select("robloxImages","Roblox Images","ROBLOX","PROJECT",projectOptions.robloxImages,["AUTO","LOCAL_PREVIEW","PUBLISHABLE"],(robloxImages)=>projectPatch({robloxImages:robloxImages as ProjectExportOptions["robloxImages"]}),"Controls local preview versus publishable cloud assets.","publishing cloud"),
      toggle("clipContent","Clip Child Contents","LAYOUT","OBJECT",selected.clipContent,(clipContent)=>onObject({clipContent}),"Maps to Roblox ClipsDescendants for this container.","overflow clipping"),
      select("textOrientation","Text Orientation","TEXT","OBJECT",selected.textOrientation,["auto","horizontal","follow-shape","custom"],(textOrientation)=>onObject({textOrientation:textOrientation as EditorElement["textOrientation"],followObjectAngle:textOrientation==="auto"||textOrientation==="follow-shape"}),"Controls caption orientation in the shape's local coordinate system.","geometry caption"),
      select("textSizingMode","Text Sizing","TEXT","OBJECT",selected.textSizingMode,["fixed","fit-geometry","responsive"],(textSizingMode)=>onObject({textSizingMode:textSizingMode as EditorElement["textSizingMode"],autoFit:textSizingMode==="responsive"}),"Design size, geometry fit, or responsive native text sizing.","font fit"),
      toggle("sharedCaptionSize","Shared Caption Size","TEXT","OBJECT",selected.sharedCaptionSize,(sharedCaptionSize)=>onObject({sharedCaptionSize,sharedCaptionGroup:sharedCaptionSize?(selected.sharedCaptionGroup||"menu-captions"):""}),"Uses one safe native TextSize for a related menu group.","menu text"),
      select("captionSafePadding","Caption Safe Padding","TEXT","OBJECT",Object.values(selected.captionInsets).some(Boolean)?"CUSTOM":"AUTO",["AUTO","CUSTOM"],(value)=>onObject({captionInsets:value==="AUTO"?{top:0,right:0,bottom:0,left:0}:Object.values(selected.captionInsets).some(Boolean)?selected.captionInsets:{top:8,right:12,bottom:8,left:12}}),"Measures caption padding along geometry-local axes.","inset"),
      select("robloxScreenScaling","Roblox Screen Scaling","ROBLOX","PROJECT",projectOptions.robloxScreenScaling,["FIT","FILL","RESPONSIVE","ORIGINAL","STRETCH"],(robloxScreenScaling)=>projectPatch({robloxScreenScaling:robloxScreenScaling as ProjectExportOptions["robloxScreenScaling"]}),"Controls reference-screen behavior in Studio.","responsive device"),
      select("referenceResolution","Reference Resolution","ROBLOX","PROJECT",projectOptions.referenceResolution,["1920x1080","2560x1440","1366x768","CUSTOM"],(referenceResolution)=>projectPatch({referenceResolution:referenceResolution as ProjectExportOptions["referenceResolution"]}),"Sets the project reference resolution for Roblox layout conversion.","screen viewport"),
      select("imageExportScaling","Image Export Scaling","IMAGES","PROJECT",projectOptions.imageExportScaling,["PRESERVE","FIT","FILL","STRETCH","ORIGINAL"],(imageExportScaling)=>projectPatch({imageExportScaling:imageExportScaling as ProjectExportOptions["imageExportScaling"]}),"Defines exported image aspect behavior.","aspect ratio"),
      select("hierarchyExport","Hierarchy Export","LAYOUT","PROJECT",projectOptions.hierarchyExport,["PRESERVE","FLATTEN_HELPERS","ADVANCED"],(hierarchyExport)=>projectPatch({hierarchyExport:hierarchyExport as ProjectExportOptions["hierarchyExport"]}),"Preserves user-created parent/child relationships by default.","layers parent"),
      toggle("showGeneratedObjects","Show Generated Objects","EDITOR","EDITOR",editorOptions.showGeneratedObjects,(showGeneratedObjects)=>onEditor({showGeneratedObjects}),"Shows UIPadding, constraints, and generated helpers in Layers.","layers helpers"),
      select("robloxNaming","Roblox Naming","ROBLOX","PROJECT",projectOptions.robloxNaming,["LAYER_NAMES","CLEAN_NAMES","TECHNICAL_NAMES"],(robloxNaming)=>projectPatch({robloxNaming:robloxNaming as ProjectExportOptions["robloxNaming"]}),"Controls Studio instance names.","instances layers"),
      select("multiplayerSafeAssets","Multiplayer Safe Assets","ROBLOX","PROJECT",projectOptions.multiplayerSafeAssets,["OFF","WARN","REQUIRE"],(multiplayerSafeAssets)=>projectPatch({multiplayerSafeAssets:multiplayerSafeAssets as ProjectExportOptions["multiplayerSafeAssets"]}),"Checks StarterGui, cloud assets, native captions, and final references.","publishable safety"),
      select("studioSync","Studio Sync","ROBLOX","PROJECT",projectOptions.studioSync,["UPDATE_EXISTING","REPLACE_MANAGED","ASK"],(studioSync)=>projectPatch({studioSync:studioSync as ProjectExportOptions["studioSync"]}),"Only manages CreatorMake-owned GUI instances.","update replace"),
      toggle("incrementalSync","Incremental Sync","ROBLOX","PROJECT",projectOptions.incrementalSync,(incrementalSync)=>projectPatch({incrementalSync}),"Only updates changed CreatorMake-managed objects and assets.","performance changes"),
      select("compatibilityWarnings","Compatibility Warnings","DEBUG / ADVANCED","PROJECT",projectOptions.compatibilityWarnings,["ALL","IMPORTANT","OFF"],(compatibilityWarnings)=>projectPatch({compatibilityWarnings:compatibilityWarnings as ProjectExportOptions["compatibilityWarnings"]}),"Fatal export failures are always shown.","roblox diagnostics"),
      select("previewQuality","Editor Preview Quality","EDITOR","EDITOR",editorOptions.previewQuality,["PERFORMANCE","BALANCED","HIGH"],(previewQuality)=>onEditor({previewQuality:previewQuality as EditorOptions["previewQuality"]}),"Changes the CreatorMake canvas preview only, never final export.","quality canvas"),
      select("smartGuideDetail","Smart Guide Detail","EDITOR","EDITOR",editorOptions.smartGuideDetail,["MINIMAL","NORMAL","DETAILED"],(smartGuideDetail)=>onEditor({smartGuideDetail:smartGuideDetail as EditorOptions["smartGuideDetail"]}),"Controls guide visualization without changing snap precision.","alignment measurements"),
      toggle("exportDiagnostics","Export Diagnostics","DEBUG / ADVANCED","PROJECT",projectOptions.exportDiagnostics,(exportDiagnostics)=>projectPatch({exportDiagnostics}),"Shows strategy, hashes, asset IDs, mapping, and hierarchy diagnostics.","debug metadata"),
      select("safeExportCheck","Before Final Export","DEBUG / ADVANCED","PROJECT",projectOptions.safeExportCheck,["NEVER","WARN","REQUIRE"],(safeExportCheck)=>projectPatch({safeExportCheck:safeExportCheck as ProjectExportOptions["safeExportCheck"]}),"Checks fonts, images, overflow, hierarchy, compatibility, and multiplayer safety.","validation"),
      select("autoUploadChangedVisuals","Auto Upload Changed Visuals","ROBLOX","PROJECT",projectOptions.autoUploadChangedVisuals,["OFF","ASK","ON"],(autoUploadChangedVisuals)=>projectPatch({autoUploadChangedVisuals:autoUploadChangedVisuals as ProjectExportOptions["autoUploadChangedVisuals"]}),"Uploads only changed visuals used by the project.","asset publishing"),
      select("renderedVisualBounds","Rendered Visual Bounds","DEBUG / ADVANCED","PROJECT",projectOptions.renderedVisualBounds,["PRESERVE","TRIM","SMART"],(renderedVisualBounds)=>projectPatch({renderedVisualBounds:renderedVisualBounds as ProjectExportOptions["renderedVisualBounds"]}),"Smart trimming preserves slants, shadows, and negative visual offsets.","transparent margin"),
      select("strokeRendering","Stroke Rendering","EXPORT","PROJECT",projectOptions.strokeRendering,["NATIVE","PIXEL","AUTO"],(strokeRendering)=>projectPatch({strokeRendering:strokeRendering as ProjectExportOptions["strokeRendering"]}),"Uses native strokes where exact, otherwise pixel-accurate output.","outline quality"),
      select("effectsQuality","Effects Quality","EXPORT","PROJECT",projectOptions.effectsQuality,["PERFORMANCE","HIGH","ULTRA"],(effectsQuality)=>projectPatch({effectsQuality:effectsQuality as ProjectExportOptions["effectsQuality"]}),"Controls shadow, glow, blur, and gradient sampling for rendered visuals only.","quality glow shadow"),
    ];
  },[selected,projectOptions,editorOptions,onObject,onEditor,projectPatch,recordRecent]);
  const normalized=query.trim().toLowerCase(),matches=(definition:OptionDefinition)=>!normalized||`${definition.label} ${definition.keywords} ${definition.group} ${definition.scope}`.toLowerCase().includes(normalized),visible=definitions.filter(matches),groups=["EXPORT","TEXT","IMAGES","ROBLOX","LAYOUT","EDITOR","PERFORMANCE","DEBUG / ADVANCED"] as const;
  const renderEntry=(definition:OptionDefinition,pinned=false)=><div key={`${pinned?"pinned-":""}${definition.id}`} className={`option-entry ${pinned?"pinned":""}`} data-option-id={definition.id}>{definition.render()}<button className={`option-favorite ${editorOptions.optionFavorites.includes(definition.id)?"active":""}`} title={editorOptions.optionFavorites.includes(definition.id)?"Unpin option":"Pin option"} aria-label={`${editorOptions.optionFavorites.includes(definition.id)?"Unpin":"Pin"} ${definition.label}`} onClick={()=>toggleFavorite(definition.id)}><Star size={12}/></button></div>;
  const pinned=editorOptions.optionFavorites.map((id)=>definitions.find((definition)=>definition.id===id)).filter((definition):definition is OptionDefinition=>Boolean(definition)).filter(matches);
  const recent=recentIds.map((id)=>definitions.find((definition)=>definition.id===id)).filter((definition):definition is OptionDefinition=>Boolean(definition)).filter(matches);
  const presets:ProjectExportOptions["preset"][]=["FAST_PREVIEW","BALANCED","ROBLOX_FINAL","COMMISSION_FINAL","MAX_QUALITY","CUSTOM"];
  const applyPreset=(preset:string)=>{if(preset==="CUSTOM")return;recordRecent("preset");onProject(applyProjectOptionPreset(preset as Exclude<ProjectExportOptions["preset"],"CUSTOM">));};
  const renderGroup=(group:typeof groups[number])=>{const entries=visible.filter((definition)=>definition.group===group);if(!entries.length)return null;const content=<>{entries.map((definition)=>renderEntry(definition))}{group==="TEXT"&&Object.values(selected.captionInsets).some(Boolean)&&<div className="caption-padding-grid"><NumberField label="Left" value={selected.captionInsets.left} min={0} max={selected.width/2} scope="OBJECT" onChange={(left)=>onObject({captionInsets:{...selected.captionInsets,left}})}/><NumberField label="Right" value={selected.captionInsets.right} min={0} max={selected.width/2} scope="OBJECT" onChange={(right)=>onObject({captionInsets:{...selected.captionInsets,right}})}/><NumberField label="Top" value={selected.captionInsets.top} min={0} max={selected.height/2} scope="OBJECT" onChange={(top)=>onObject({captionInsets:{...selected.captionInsets,top}})}/><NumberField label="Bottom" value={selected.captionInsets.bottom} min={0} max={selected.height/2} scope="OBJECT" onChange={(bottom)=>onObject({captionInsets:{...selected.captionInsets,bottom}})}/></div>}{group==="ROBLOX"&&projectOptions.referenceResolution==="CUSTOM"&&<div className="custom-resolution-grid"><NumberField label="Width" value={projectOptions.customReferenceWidth} min={320} max={7680} unit="px" scope="PROJECT" onChange={(customReferenceWidth)=>projectPatch({customReferenceWidth})}/><NumberField label="Height" value={projectOptions.customReferenceHeight} min={240} max={4320} unit="px" scope="PROJECT" onChange={(customReferenceHeight)=>projectPatch({customReferenceHeight})}/></div>}</>;return group==="DEBUG / ADVANCED"?<details className="option-group advanced-options" key={group}><summary>ADVANCED</summary>{content}</details>:<section className="option-group" key={group}><h4>{group}</h4>{content}</section>;};
  return <div className="inspector-section options-panel">
    <section className="quick-options" aria-label="Quick Options"><header><strong>QUICK OPTIONS</strong><small>Changes apply immediately</small></header><div className="quick-options-grid"><SelectField label="Preset" value={projectOptions.preset} options={presets.map((value)=>({value,label:labelize(value)}))} scope="PROJECT" onChange={applyPreset}/><SelectField label="Quality" value={projectOptions.renderedVisualQuality} options={["DRAFT","STANDARD","HIGH","ULTRA","MAXIMUM_SAFE"].map((value)=>({value,label:value==="MAXIMUM_SAFE"?"Max Safe":labelize(value)}))} scope="PROJECT" onChange={(value)=>{recordRecent("renderedVisualQuality");projectPatch({renderedVisualQuality:value as ProjectExportOptions["renderedVisualQuality"]});}}/><SelectField label="Text" value={projectOptions.nativeTextLabelExport?"NATIVE":"AUTO"} options={[{value:"NATIVE",label:"Native"},{value:"AUTO",label:"Auto"}]} scope="PROJECT" onChange={(value)=>{recordRecent("nativeTextLabelExport");projectPatch({nativeTextLabelExport:value==="NATIVE"});}}/><SelectField label="Roblox" value={projectOptions.robloxImages} options={["LOCAL_PREVIEW","AUTO","PUBLISHABLE"].map((value)=>({value,label:labelize(value)}))} scope="PROJECT" onChange={(value)=>{recordRecent("robloxImages");projectPatch({robloxImages:value as ProjectExportOptions["robloxImages"]});}}/></div><button className="max-quality-export" onClick={()=>applyPreset("MAX_QUALITY")}><Zap size={12}/> MAX QUALITY EXPORT</button></section>
    <label className="options-search"><Search size={13}/><input aria-label="Search options" placeholder="Search options…" value={query} onChange={(event)=>setQuery(event.target.value)}/></label>
    {pinned.length>0&&<section className="option-group pinned-options"><h4><Star size={12}/> PINNED</h4>{pinned.map((definition)=>renderEntry(definition,true))}</section>}
    {recent.length>0&&<section className="option-group recent-options"><h4>RECENTLY CHANGED</h4>{recent.map((definition)=>renderEntry(definition))}</section>}
    {groups.map(renderGroup)}
    {visible.length===0&&<p className="options-empty">No options match “{query}”.</p>}
    <div className="options-reset"><button onClick={()=>onObject({clipContent:selected.type==="scrolling-frame",textOrientation:isDirectionalCaptionGeometry(selected.geometry.kind)?"follow-shape":"auto",followObjectAngle:true,textSizingMode:"fixed",autoFit:false,sharedCaptionSize:false,sharedCaptionGroup:"",captionInsets:{top:0,right:0,bottom:0,left:0}})}><RotateCcw size={11}/> Object</button><button onClick={()=>onProject(DEFAULT_PROJECT_EXPORT_OPTIONS)}><RotateCcw size={11}/> Project</button><button onClick={()=>onEditor({previewQuality:"BALANCED",showGeneratedObjects:false,smartGuideDetail:"NORMAL",optionFavorites:[]})}><RotateCcw size={11}/> Editor</button></div>
  </div>;
}
