"use client";

import { useEffect, useRef, useState } from "react";
import { FlaskConical, ImagePlus, X } from "lucide-react";
import type { EditorReference, ReferenceRole } from "@/lib/design-intelligence/types";
import type { AIProviderStatus, GenerationEngine } from "@/lib/ai/types";

export type PlanInput = { prompt:string; style:string; mode:string; platform:string; accuracy:string;engine:GenerationEngine };
type Props = { prompt:string; onPromptChange:(value:string)=>void; references:EditorReference[]; onAddReferences:(items:EditorReference[])=>void; onUpdateReference:(id:string,patch:Partial<EditorReference>)=>void; onRemoveReference:(id:string)=>void; onResearchPlan:(input:PlanInput)=>void; planning:boolean;providerStatus:AIProviderStatus|null;onOpenAISettings:()=>void;onCancel:()=>void };
export const REFERENCE_ROLES: ReferenceRole[] = ["Layout","Proportions","Geometry","Frame Construction","Visual Style","Colors","Typography","Buttons","Borders","Icons","Components","Background","Effects","Animation","Perspective","Depth","Lighting","Inspiration","Custom"];

const readFile = (file: File) => new Promise<string>((resolve,reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); });
const analyzeImage = (dataUrl:string) => new Promise<EditorReference["measurements"]>((resolve) => { const image = new Image(); image.onload = () => { const canvas = document.createElement("canvas"); canvas.width = 32; canvas.height = 32; const context = canvas.getContext("2d"); if (!context) return resolve({aspectRatio:image.width/image.height,dominantColors:[],contrast:"unknown",density:"unknown"}); context.drawImage(image,0,0,32,32); const pixels = context.getImageData(0,0,32,32).data; const buckets = new Map<string,number>(); let luminanceMin = 255,luminanceMax = 0; for (let index=0;index<pixels.length;index+=16) { const r=Math.round(pixels[index]/32)*32,g=Math.round(pixels[index+1]/32)*32,b=Math.round(pixels[index+2]/32)*32; const color=`#${[r,g,b].map((value)=>Math.min(255,value).toString(16).padStart(2,"0")).join("")}`; buckets.set(color,(buckets.get(color)??0)+1); const l=.2126*r+.7152*g+.0722*b; luminanceMin=Math.min(luminanceMin,l); luminanceMax=Math.max(luminanceMax,l); } const dominantColors=[...buckets.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4).map(([color])=>color); resolve({aspectRatio:Math.round(image.width/image.height*100)/100,dominantColors,contrast:luminanceMax-luminanceMin>145?"high":luminanceMax-luminanceMin>75?"medium":"low",density:dominantColors.length>3?"dense":"focused"}); }; image.onerror=()=>resolve({aspectRatio:1,dominantColors:[],contrast:"unknown",density:"unknown"}); image.src=dataUrl; });

export function PromptWorkspace(props: Props) {
  const [dragging,setDragging] = useState(false), [mode,setMode] = useState("New design"), [style,setStyle] = useState("Auto detect"), [platform,setPlatform] = useState("Generic"), [engine,setEngine] = useState<GenerationEngine>("LOCAL"); const inputRef=useRef<HTMLInputElement>(null);
  const addFiles = async (files: FileList|File[]) => { const images=Array.from(files).filter((file)=>/^image\/(png|jpeg|webp)/.test(file.type) && file.size<6_000_000); const items=await Promise.all(images.map(async(file,index)=>{ const dataUrl=await readFile(file); return { id:`reference_${Date.now()}_${index}`, name:`@${file.name.replace(/\.[^.]+$/,"").replace(/\W+/g,"")||`Reference${props.references.length+index+1}`}`, dataUrl, role:"Visual Style" as ReferenceRole, influence:75, createdAt:Date.now(), notes:"", measurements:await analyzeImage(dataUrl), regions:[] }; })); if(items.length) props.onAddReferences(items); };
  useEffect(()=>{ const paste=(event:ClipboardEvent)=>{ const files=Array.from(event.clipboardData?.files??[]); if(files.some((file)=>file.type.startsWith("image/"))){event.preventDefault();void addFiles(files);} }; window.addEventListener("paste",paste); return()=>window.removeEventListener("paste",paste); });
  const submit=()=>{if(props.prompt.trim())props.onResearchPlan({prompt:props.prompt,style,mode,platform,accuracy:engine==="LOCAL"?"Local":engine.charAt(0)+engine.slice(1).toLowerCase(),engine});};
  return <footer className={`prompt-workspace ${dragging?"is-dragging":""}`} onDragOver={(event)=>{event.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={(event)=>{event.preventDefault();setDragging(false);void addFiles(event.dataTransfer.files);}}>
    {dragging&&<div className="drop-message">DROP REFERENCES HERE</div>}
    {!!props.references.length&&<div className="reference-tray">{props.references.map((reference)=><article key={reference.id} className="reference-chip"><img src={reference.dataUrl} alt=""/><div><input value={reference.name} aria-label="Reference name" onChange={(event)=>props.onUpdateReference(reference.id,{name:event.target.value})}/><select value={reference.role} aria-label={`${reference.name} role`} onChange={(event)=>props.onUpdateReference(reference.id,{role:event.target.value as ReferenceRole})}>{REFERENCE_ROLES.map((role)=><option key={role}>{role}</option>)}</select></div><label>Influence<input aria-label={`${reference.name} influence`} type="range" min="0" max="100" value={reference.influence} onChange={(event)=>props.onUpdateReference(reference.id,{influence:Number(event.target.value)})}/></label><button aria-label={`Remove ${reference.name}`} onClick={()=>props.onRemoveReference(reference.id)}><X size={12}/></button></article>)}</div>}
    <div className="engine-row"><button className={`engine-status ${engine==="LOCAL"?"local":props.providerStatus?.connected?"connected":"not-configured"}`} onClick={props.onOpenAISettings}><strong>{engine==="LOCAL"?"LOCAL GENERATOR":`${engine} AI`}</strong><span>{engine==="LOCAL"?"Deterministic · offline":props.providerStatus?.connected?`OpenAI · ${props.providerStatus.model}`:"OpenAI · Not configured"}</span></button><p>{engine==="LOCAL"?"Templates and preset rules are used explicitly. No external AI request will occur.":"External multimodal planning. Failure will not fall back to Local Generator."}</p></div>
    <div className="prompt-row"><button onClick={()=>inputRef.current?.click()}><ImagePlus size={14}/> Add references</button><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" multiple hidden onChange={(event)=>{if(event.target.files)void addFiles(event.target.files);event.currentTarget.value="";}}/><textarea aria-label="Design prompt" value={props.prompt} onChange={(event)=>props.onPromptChange(event.target.value)} onKeyDown={(event)=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();submit();}}} placeholder="Describe what to create or modify. Quote only text that should appear in the UI."/><select aria-label="Generation mode" value={mode} onChange={(event)=>setMode(event.target.value)}><option>New design</option><option>Selected objects</option><option>Current screen</option><option>Refine</option><option>Restyle</option><option>Fix</option><option>3D style transformation</option></select><select aria-label="Starting preset" value={style} onChange={(event)=>setStyle(event.target.value)}>{["Windows 98","Holographic","CRT Terminal","Arcade","Cyberpunk","Game Show","Forest","Roblox Classic","Auto detect"].map((item)=><option key={item}>{item}</option>)}</select><select aria-label="Platform" value={platform} onChange={(event)=>setPlatform(event.target.value)}><option>Generic</option><option>Web</option><option>Desktop</option><option>Mobile</option><option>Roblox</option></select><select aria-label="Generation engine" value={engine} onChange={(event)=>setEngine(event.target.value as GenerationEngine)}><option value="LOCAL">Local Generator</option><option value="FAST">Fast AI</option><option value="BALANCED">Balanced AI</option><option value="PRECISE">Precise AI</option></select>{props.planning?<button className="generate cancel" onClick={props.onCancel}><X size={14}/> Cancel</button>:<button className="generate" onClick={submit} disabled={!props.prompt.trim()}><FlaskConical size={14}/> {engine==="LOCAL"?"Local Plan":"AI Plan"}</button>}</div>
  </footer>;
}
