"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { CheckCircle2, Clipboard, Download, FileJson, ImageIcon, PlugZap, RefreshCw, ShieldCheck, X } from "lucide-react";
import {
  CREATORMAKE_APP_VERSION,
  CREATORMAKE_BRIDGE_ORIGIN,
  CREATORMAKE_BRIDGE_VERSION,
  CREATORMAKE_PLUGIN_VERSION,
  CREATORMAKE_PRODUCTION_ORIGIN,
  CREATORMAKE_PROTOCOL_VERSION,
} from "@/lib/creatormake-version.js";
import { verifyGeneratedLua } from "@/lib/roblox/exporter";
import { buildActiveProjectRobloxManifest } from "@/lib/roblox/active-project-manifest";
import { SYSTEM_PRESETS } from "@/lib/design-intelligence/system-presets";
import { classifyRobloxElement, classifyTextExport, hasVisibleTextBackground } from "@/lib/roblox/classification";
import { assetMappingKey, normalizeRobloxAssetId, planPixelAccurateAssets, renderPixelAccurateAssets } from "@/lib/roblox/render-assets";
import { createRobloxPluginModel, creatorMakePluginFilename } from "@/lib/roblox/plugin";
import { DEFAULT_ROBLOX_EXPORT_OPTIONS, ROBLOX_RESOLUTIONS } from "@/lib/roblox/types";
import type { EditorElement, EditorProject } from "@/lib/editor/types";
import type { RobloxAssetMappings } from "@/lib/roblox/render-assets";
import type { RobloxExportOptions, RobloxRenderAsset, RobloxRenderScale, RobloxSizingMode, RobloxVisualMode } from "@/lib/roblox/types";
import { resolveProjectRenderScale, resolveProjectResolution, resolveProjectVisualMode } from "@/lib/editor/options";

export type StudioConnectionSummary={status:"disconnected"|"pairing"|"connected"|"error";pluginOnline:boolean;pendingChanges:number;lastSeenAt:number|null};
type Props={open:boolean;project:EditorProject;onClose:()=>void;onStudioStatusChange?:(summary:StudioConnectionSummary)=>void;quickSyncToken?:number;onQuickSyncFeedback?:(message:string)=>void};
type SyncState={id:string;mode?:"preview"|"install-starter-gui"|"apply-published";status:"pending"|"running"|"completed"|"failed";message?:string;error?:string|null;plan?:{nodes:number;totalAssets:number;uniqueVisuals:number;previewAssets:number;changedVisuals:number;publishAssets:number;publishedAssets:number;reusedAssets:number;changedNodes:number;deletedNodes:number};result?:{projectId?:string;projectName?:string;manifestVersion?:string;created?:number;reused?:number;nodes?:number;screenGuiName?:string;previewImages?:number;permanent?:boolean;localAssetImport?:boolean;deployTarget?:"StarterGui"|"PlayerGuiPreview";multiPlayerReady?:boolean}|null};
type PublishingJob={id:string;status:"pending"|"running"|"completed"|"failed";message:string;error:string|null;total:number;completed:number;published:number;reused:number;requestedAt:string;completedAt:string|null};
type PublishingStatus={status?:string;config:{configured:boolean;authMode:"api-key"|"oauth"|"not-configured";creatorType:string|null;creatorId:string|null;missing:string[];oauth?:{status:string;scopes:string[]}};totalAssets:number;uniqueVisuals:number;needsPublish:number;publishedVisuals:number;previewOnlyAssets:number;job:PublishingJob|null};
type ConnectionState="WAITING_FOR_STUDIO"|"STUDIO_CONNECTED"|"PLUGIN_OUTDATED"|"CREATORMAKE_UPDATE_REQUIRED"|"SYNC_ERROR";
type LocalDiagnostics={webApp:string;syncServer:string;appVersion?:string;bridgeVersion?:string;port:number;studio:string;pluginVersion:number|null;pluginProtocol:number|null;pluginAppVersion?:string|null;protocol:number;manifest:string;pixelTransport:string;studioPreview?:string;deployTarget?:string;managedScreenGui?:string|null;runtime?:string;multiPlayerReady?:boolean;previewClient?:string;assetUpload:string;lastError:string|null};
type LocalHealth={ok?:boolean;status:string;app:string;service?:string;appVersion?:string;bridgeVersion?:string;protocolVersion?:number;connectionState?:ConnectionState;pluginOnline?:boolean;pluginVersionRequired?:number;plugins?:Array<{lastSeenAt:string;appVersion?:string|null;pluginVersion:number;protocolVersion:number|null;status:string}>;manifestReady?:boolean;currentProjectId?:string|null;currentProjectName?:string|null;currentManifestVersion?:string|null;currentManifestRevision?:number;currentManifestEndpoint?:string;previewReady?:boolean;lastUpdatedAt?:string|null;lastSuccessfulSyncAt?:string|null;renderedAssets?:number;unmappedAssets?:number;uploadReady?:number;diagnostics?:LocalDiagnostics;publishing?:PublishingStatus;sync?:SyncState|null};
type View="studio"|"preview"|"assets"|"hierarchy"|"lua"|"compatibility";

const LOCAL_SYNC_ORIGIN=CREATORMAKE_BRIDGE_ORIGIN;
const safeName=(value:string)=>value.trim().replace(/[^a-zA-Z0-9_ -]/g,"")||"CreatorMakeGui";
const download=(content:string,name:string,type:string)=>{const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);};
const downloadUrl=(url:string,name:string)=>{const anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();};
const responseError=async(response:Response)=>{try{const value=await response.json() as{error?:string};return value.error||`Request failed (${response.status})`;}catch{return`Request failed (${response.status})`;}};
const mappingStorageKey=(projectId:string)=>`creatormake:roblox-asset-mappings:${projectId}`;
const loadMappings=(projectId:string):RobloxAssetMappings=>{if(typeof window==="undefined")return{};try{return JSON.parse(localStorage.getItem(mappingStorageKey(projectId))??"{}");}catch{return{};}};
const displayStatus=(asset:RobloxRenderAsset)=>asset.status==="needs-render"?"Needs Render":asset.status==="needs-publish"||asset.status==="needs-mapping"?"Preview Ready · Needs Publish":asset.status==="preview-ready"?"Preview Ready":asset.status==="rendering"?"Rendering":asset.status==="mapped"?"Published ID Ready":asset.status==="dirty"?"Dirty":asset.status==="error"?"Error":"Ready";
const renderAssetElementId=(asset:RobloxRenderAsset)=>asset.sourceElementId??asset.sourceId;
const exportMapping=(element:EditorElement,mode:RobloxVisualMode)=>{if(mode==="NATIVE")return element.type==="scrolling-frame"?"Native ScrollingFrame + layout instances":"Native Roblox object";if(element.type==="text"||element.type==="button"){const decision=classifyTextExport(element),background=hasVisibleTextBackground(element);if(element.type==="text"&&!background&&decision.mode==="NATIVE")return decision.className;const root=element.type==="button"?"ImageButton":"Frame",nativeName=element.textInput?"TextBox":"TextLabel",parts=[background?"_Background ImageLabel (no glyphs)":null,decision.mode==="NATIVE"?`${nativeName} [${nativeName}]`:"_PixelText [ImageLabel]"].filter(Boolean);return`${root} + ${parts.join(" + ")}`;}if(mode==="PIXEL_ACCURATE")return element.type==="scrolling-frame"?"Frame + _Visual + ScrollingFrame + layout instances":element.type==="frame"||element.type==="container"?"Frame + _Visual ImageLabel":"ImageLabel";const result=classifyRobloxElement(element);return result.classification==="NATIVE"?result.intendedRobloxClass:result.classification==="HYBRID"?`${result.intendedRobloxClass} + transparent background PNG`:`${result.intendedRobloxClass} container + transparent PNG`;};

export function RobloxExportDialog({open,project,onClose,onStudioStatusChange,quickSyncToken=0,onQuickSyncFeedback}:Props){
  const [options,setOptions]=useState<RobloxExportOptions>(()=>({...DEFAULT_ROBLOX_EXPORT_OPTIONS,screenGuiName:`${project.name.replace(/[^a-z0-9]+/gi,"")}Gui`||"CreatorMakeGui",visualMode:resolveProjectVisualMode(project.exportOptions),renderScale:resolveProjectRenderScale(project.exportOptions),imageResampling:project.exportOptions.imageResampling,effectsQuality:project.exportOptions.effectsQuality,resolution:resolveProjectResolution(project.exportOptions),sizingMode:project.exportOptions.robloxScreenScaling==="ORIGINAL"?"OFFSET":project.exportOptions.robloxScreenScaling==="RESPONSIVE"?"SCALE":"AUTO"}));
  const [view,setView]=useState<View>("studio"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[rendering,setRendering]=useState(false),[syncPhase,setSyncPhase]=useState("");
  const [compareGeometry,setCompareGeometry]=useState(false),[compareOpacity,setCompareOpacity]=useState(50),[showDifference,setShowDifference]=useState(false);
  const [localStatus,setLocalStatus]=useState<"disconnected"|"connecting"|"connected"|"error">("disconnected"),[health,setHealth]=useState<LocalHealth|null>(null),[publishing,setPublishing]=useState<PublishingStatus|null>(null),[lastSeenAt,setLastSeenAt]=useState<number|null>(null);
  const [mappings,setMappings]=useState<RobloxAssetMappings>(()=>loadMappings(project.id)),[renderAssets,setRenderAssets]=useState<RobloxRenderAsset[]>([]);
  const assetsRef=useRef<RobloxRenderAsset[]>([]),renderToken=useRef(0),lastCompletedSync=useRef<string|null>(null),lastCompletedPublish=useRef<string|null>(null),lastQuickSyncToken=useRef(0);
  const updateAssets=(assets:RobloxRenderAsset[])=>{assetsRef.current=assets;setRenderAssets(assets);};
  const renderCurrent=async()=>{
    if(options.visualMode==="NATIVE")return[];
    const token=++renderToken.current,planned=planPixelAccurateAssets(project,options,mappings,assetsRef.current);updateAssets(planned);setRendering(true);
    try{const result=await renderPixelAccurateAssets(project,options,mappings,assetsRef.current,(progress)=>{if(renderToken.current===token)updateAssets(progress);});if(renderToken.current===token)updateAssets(result);return result;}
    finally{if(renderToken.current===token)setRendering(false);}
  };
  useEffect(()=>{if(!open||options.visualMode==="NATIVE")return;let active=true;const token=++renderToken.current,renderOptions={renderScale:options.renderScale,visualMode:options.visualMode,imageResampling:options.imageResampling,effectsQuality:options.effectsQuality},planned=planPixelAccurateAssets(project,renderOptions,mappings,assetsRef.current);queueMicrotask(()=>{if(active){updateAssets(planned);setRendering(true);}});void renderPixelAccurateAssets(project,renderOptions,mappings,assetsRef.current,(progress)=>{if(active&&renderToken.current===token)updateAssets(progress);}).then((result)=>{if(active&&renderToken.current===token)updateAssets(result);}).finally(()=>{if(active&&renderToken.current===token)setRendering(false);});return()=>{active=false;};},[open,project,options.visualMode,options.renderScale,options.imageResampling,options.effectsQuality,mappings]);

  const output=buildActiveProjectRobloxManifest(project,options,renderAssets),verification=verifyGeneratedLua(output.lua);
  const classifications=project.elements.filter((element)=>!element.hidden).map(classifyRobloxElement),counts={native:classifications.filter((item)=>item.classification==="NATIVE").length,approximation:classifications.filter((item)=>item.classification==="HYBRID").length,unsupported:classifications.filter((item)=>item.classification==="RASTERIZED").length};
  const assetCounts={total:renderAssets.length,published:renderAssets.filter((asset)=>asset.status==="mapped").length,needsPublish:renderAssets.filter((asset)=>!asset.robloxAssetId&&asset.status!=="error").length,errors:renderAssets.filter((asset)=>asset.status==="error").length},pendingChanges=renderAssets.filter((asset)=>asset.dirty||asset.status==="needs-render").length;
  const pluginOnline=health?.pluginOnline===true;
  const bridgeCurrent=health?.bridgeVersion===CREATORMAKE_BRIDGE_VERSION&&health?.protocolVersion===CREATORMAKE_PROTOCOL_VERSION;
  const studioStateText=!health?"BRIDGE MISSING":!bridgeCurrent?(health.protocolVersion&&health.protocolVersion>CREATORMAKE_PROTOCOL_VERSION?"CREATORMAKE UPDATE REQUIRED":"BRIDGE OUTDATED"):health.connectionState==="STUDIO_CONNECTED"?"STUDIO CONNECTED":health.connectionState==="PLUGIN_OUTDATED"?"PLUGIN OUTDATED":health.connectionState==="CREATORMAKE_UPDATE_REQUIRED"?"CREATORMAKE UPDATE REQUIRED":health.connectionState==="SYNC_ERROR"?"SYNC ERROR":"BRIDGE RUNNING · WAITING FOR STUDIO";
  const environment=typeof window!=="undefined"&&window.location.origin===CREATORMAKE_PRODUCTION_ORIGIN?"Production":"Development";
  const productionStatus=environment==="Production"?`Current · ${CREATORMAKE_APP_VERSION}`:"Not checked from development";
  const summary:StudioConnectionSummary={status:localStatus==="connecting"?"pairing":localStatus,pluginOnline,pendingChanges,lastSeenAt};
  useEffect(()=>{if(open)onStudioStatusChange?.({status:localStatus==="connecting"?"pairing":localStatus,pluginOnline,pendingChanges,lastSeenAt});},[open,localStatus,pluginOnline,pendingChanges,lastSeenAt,onStudioStatusChange]);

  const acceptHealth=useCallback((value:LocalHealth)=>{setHealth(value);if(value.publishing)setPublishing(value.publishing);const seen=value.plugins?.[0]?.lastSeenAt;setLastSeenAt(seen?Date.parse(seen):null);const compatible=value.bridgeVersion===CREATORMAKE_BRIDGE_VERSION&&value.protocolVersion===CREATORMAKE_PROTOCOL_VERSION;setLocalStatus(compatible&&value.connectionState==="STUDIO_CONNECTED"&&value.pluginOnline?"connected":!compatible||value.connectionState==="PLUGIN_OUTDATED"||value.connectionState==="CREATORMAKE_UPDATE_REQUIRED"||value.connectionState==="SYNC_ERROR"?"error":"disconnected");},[]);
  const refreshHealth=useCallback(async(showSuccess=false)=>{try{const response=await fetch(`${LOCAL_SYNC_ORIGIN}/health`,{cache:"no-store",signal:AbortSignal.timeout(3500)});if(!response.ok)throw new Error(await responseError(response));const value=await response.json()as LocalHealth;if(value.status!=="ok"||value.app!=="CreatorMake"||value.service!=="CreatorMake Studio Sync"||typeof value.protocolVersion!=="number")throw new Error("Unexpected /health identity or missing protocolVersion.");acceptHealth(value);if(showSuccess)setNotice(value.bridgeVersion!==CREATORMAKE_BRIDGE_VERSION?`Bridge update required. Web ${CREATORMAKE_APP_VERSION} expects bridge ${CREATORMAKE_BRIDGE_VERSION}; received ${value.bridgeVersion??"unknown"}.`:value.protocolVersion!==CREATORMAKE_PROTOCOL_VERSION?`Protocol mismatch. Web ${CREATORMAKE_PROTOCOL_VERSION}; bridge ${value.protocolVersion}.`:value.connectionState==="STUDIO_CONNECTED"?`Studio connected · web ${CREATORMAKE_APP_VERSION} · bridge ${value.bridgeVersion} · plugin ${value.plugins?.[0]?.pluginVersion??"unknown"} · protocol ${value.protocolVersion}.`:value.connectionState==="PLUGIN_OUTDATED"?`Plugin update required. Installed build ${value.plugins?.[0]?.pluginVersion??"unknown"}; CreatorMake requires ${value.pluginVersionRequired??CREATORMAKE_PLUGIN_VERSION}.`:value.connectionState==="CREATORMAKE_UPDATE_REQUIRED"?`CreatorMake update required. Studio protocol ${value.plugins?.[0]?.protocolVersion??"unknown"}; bridge protocol ${value.protocolVersion}.`:value.connectionState==="SYNC_ERROR"?`Sync error: ${value.diagnostics?.lastError??"Check Studio Output and retry."}`:`Bridge ${value.bridgeVersion} is running on protocol ${value.protocolVersion}; waiting for Studio plugin v${value.pluginVersionRequired??CREATORMAKE_PLUGIN_VERSION}.`);return value;}catch(error){setHealth(null);setLastSeenAt(null);setLocalStatus("error");if(showSuccess)setNotice(`${error instanceof Error?error.message:"Could not reach Studio Sync."} Start the CreatorMake bridge, then test ${LOCAL_SYNC_ORIGIN}/health.`);return null;}},[acceptHealth]);
  const refreshPublishing=useCallback(async()=>{try{const response=await fetch(`${LOCAL_SYNC_ORIGIN}/publishing/status`,{cache:"no-store"});if(response.ok)setPublishing(await response.json()as PublishingStatus);}catch{/* health polling reports the local service error */}},[]);
  const testLocal=async()=>{setBusy(true);setLocalStatus("connecting");await refreshHealth(true);setBusy(false);};

  useEffect(()=>{let active=true;void (async()=>{try{const response=await fetch(`${LOCAL_SYNC_ORIGIN}/health`,{cache:"no-store",signal:AbortSignal.timeout(3500)});if(!response.ok)return;const value=await response.json()as LocalHealth;if(value.currentProjectId&&value.currentProjectId!==project.id){const cleared=await fetch(`${LOCAL_SYNC_ORIGIN}/project/current/manifest?unlessProjectId=${encodeURIComponent(project.id)}`,{method:"DELETE"});if(!cleared.ok)throw new Error(await responseError(cleared));if(active&&open)setNotice(`Cleared stale Studio manifest for ${value.currentProjectName??value.currentProjectId}. Sync ${project.name} when ready.`);}}catch(error){if(active&&open)setNotice(`Active-project bridge check failed: ${error instanceof Error?error.message:"unknown error"}`);}})();return()=>{active=false;};},[project.id,project.name,open]);

  const stageManifest=async()=>{
    setSyncPhase("Preparing project...");setNotice(`Preparing project ${project.name}...`);
    const assets=options.visualMode!=="NATIVE"?await renderCurrent():[],failed=assets.filter((asset)=>asset.status==="error");
    if(failed.length){setView("assets");throw new Error(`${failed.length} visual asset(s) failed to render.`);}
    setSyncPhase("Building manifest...");setNotice("Building active-project manifest...");
    const current=buildActiveProjectRobloxManifest(project,options,assets),diagnostics=current.manifest.exportDiagnostics;
    console.groupCollapsed(`[CreatorMake] PROJECT_MANIFEST · ${project.name}`);console.log("Project:",project.name);console.log("Project id:",project.id);console.log("Project object count:",diagnostics.projectObjectCount);console.log("Export object count:",diagnostics.exportedProjectObjectCount);console.log("Preset count:",SYSTEM_PRESETS.length);console.log("Presets exported:",diagnostics.presetsExported);console.log("Exact manifest payload:",current.manifest);console.groupEnd();
    setSyncPhase("Sending to bridge...");setNotice(`Sending ${diagnostics.exportedProjectObjectCount} active-project object(s) to ${LOCAL_SYNC_ORIGIN}...`);
    const response=await fetch(`${LOCAL_SYNC_ORIGIN}/project/current/manifest`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(current.manifest)});
    if(!response.ok)throw new Error(await responseError(response));
    const result=await response.json()as{projectId:string;projectName:string;manifestVersion:string;projectObjectCount:number;exportedProjectObjectCount:number;presetsExported:0;nodes:number;assets:number;mappedAssets:number;lastUpdatedAt:string;renderedAssets?:RobloxRenderAsset[]};
    if(result.projectId!==project.id||result.presetsExported!==0)throw new Error(`Bridge stored the wrong project payload: expected ${project.id}, received ${result.projectId}.`);
    if(result.renderedAssets)updateAssets(result.renderedAssets.map((asset)=>{const local=assets.find((item)=>item.sourceId===asset.sourceId&&item.visualHash===asset.visualHash);return{...asset,dataUrl:local?.dataUrl,sourceDataUrl:local?.sourceDataUrl,differenceDataUrl:local?.differenceDataUrl,fidelity:local?.fidelity??asset.fidelity};}));
    return result;
  };
  const syncPreview=async(quick=false)=>{setBusy(true);if(quick)onQuickSyncFeedback?.(`Preparing ${project.name} for Studio...`);try{const currentHealth=await refreshHealth(false);if(!currentHealth)throw new Error(`CreatorMake local sync is unavailable at ${LOCAL_SYNC_ORIGIN}.`);if(currentHealth.connectionState==="PLUGIN_OUTDATED")throw new Error(`Install and reload CreatorMake Studio Sync v${currentHealth.pluginVersionRequired??CREATORMAKE_PLUGIN_VERSION}.`);if(currentHealth.connectionState==="CREATORMAKE_UPDATE_REQUIRED")throw new Error("The running Studio plugin is newer than the CreatorMake sync server.");const staged=await stageManifest();setSyncPhase("Waiting for Studio...");setNotice(`Waiting for Studio to preview ${staged.projectName}...`);const response=await fetch(`${LOCAL_SYNC_ORIGIN}/sync/request`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messageType:"PROJECT_SYNC_REQUEST",kind:"project",projectId:staged.projectId,manifestVersion:staged.manifestVersion,mode:"preview"})});if(!response.ok)throw new Error(await responseError(response));const queued=await response.json()as{sync:SyncState};const queuedMessage=currentHealth.pluginOnline?`Studio sync queued · ${queued.sync.plan?.changedNodes??staged.nodes} current-project GUI object(s).`:`Current project staged. Reload Studio plugin v${currentHealth.pluginVersionRequired??CREATORMAKE_PLUGIN_VERSION}; it will claim the job automatically.`;setHealth((value)=>value?{...value,manifestReady:true,previewReady:true,lastUpdatedAt:staged.lastUpdatedAt,sync:queued.sync}:value);setNotice(queuedMessage);if(quick)onQuickSyncFeedback?.(queuedMessage);}catch(error){setSyncPhase("");const message=`Sync failed during ${syncPhase||"preparation"}: ${error instanceof Error?error.message:"Could not sync Studio preview."}`;setNotice(message);if(quick)onQuickSyncFeedback?.(message);}finally{setBusy(false);}};
  const syncStarterGui=async()=>{setBusy(true);try{const currentHealth=await refreshHealth(false);if(!currentHealth)throw new Error(`CreatorMake local sync is unavailable at ${LOCAL_SYNC_ORIGIN}.`);if(currentHealth.connectionState==="PLUGIN_OUTDATED")throw new Error(`Install and reload CreatorMake Studio Sync v${currentHealth.pluginVersionRequired??CREATORMAKE_PLUGIN_VERSION}.`);if(currentHealth.connectionState==="CREATORMAKE_UPDATE_REQUIRED")throw new Error("The running Studio plugin is newer than the CreatorMake sync server.");const staged=await stageManifest(),localVisuals=staged.assets-staged.mappedAssets;setSyncPhase("Waiting for Studio...");setNotice(`Waiting for Studio to import current project ${staged.projectName}...`);const response=await fetch(`${LOCAL_SYNC_ORIGIN}/sync/request`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({messageType:"PROJECT_SYNC_REQUEST",kind:"project",projectId:staged.projectId,manifestVersion:staged.manifestVersion,mode:"install-starter-gui"})});if(!response.ok)throw new Error(await responseError(response));const queued=await response.json()as{sync:SyncState};setHealth((value)=>value?{...value,manifestReady:true,currentProjectId:staged.projectId,currentProjectName:staged.projectName,currentManifestVersion:staged.manifestVersion,lastUpdatedAt:staged.lastUpdatedAt,sync:queued.sync}:value);setNotice(currentHealth.pluginOnline?`Waiting for Studio: ${queued.sync.plan?.changedNodes??staged.nodes} current-project GUI object(s), ${localVisuals} RGBA visual(s).`:`Current project staged. Reload Studio plugin v${currentHealth.pluginVersionRequired??CREATORMAKE_PLUGIN_VERSION}; it will claim the job automatically.`);}catch(error){setSyncPhase("");setNotice(`Sync failed during ${syncPhase||"preparation"}: ${error instanceof Error?error.message:"Could not sync the managed ScreenGui to StarterGui."}`);}finally{setBusy(false);}};
  const publishAssets=async()=>{setBusy(true);try{const currentHealth=await refreshHealth(false);if(!currentHealth)throw new Error(`CreatorMake local sync is unavailable at ${LOCAL_SYNC_ORIGIN}.`);await stageManifest();const response=await fetch(`${LOCAL_SYNC_ORIGIN}/publish`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});if(!response.ok)throw new Error(await responseError(response));const result=await response.json()as{publishing:PublishingStatus};setPublishing(result.publishing);setNotice(result.publishing.job?.message??"Roblox Open Cloud publishing started.");}catch(error){setNotice(error instanceof Error?error.message:"Could not publish Roblox assets.");}finally{setBusy(false);}};
  const stageBasicConnectionTest=async()=>{setBusy(true);try{const currentHealth=await refreshHealth(false);if(!currentHealth)throw new Error(`CreatorMake local sync is unavailable at ${LOCAL_SYNC_ORIGIN}.`);const response=await fetch(`${LOCAL_SYNC_ORIGIN}/basic-test`,{cache:"no-store"});if(!response.ok)throw new Error(await responseError(response));const diagnostic=await response.json()as{kind?:string;projectId?:string};if(diagnostic.kind!=="project"||diagnostic.projectId!=="creatormake-connection-test")throw new Error("Basic test endpoint returned the wrong payload kind.");setNotice("Basic project manifest validated without replacing the current project. In Studio, click TEST BASIC FRAME IMPORT.");}catch(error){setNotice(error instanceof Error?error.message:"Could not validate the basic connection manifest.");}finally{setBusy(false);}};
  const clearCurrentManifest=async()=>{setBusy(true);try{const response=await fetch(`${LOCAL_SYNC_ORIGIN}/project/current/manifest`,{method:"DELETE"});if(!response.ok)throw new Error(await responseError(response));setHealth((value)=>value?{...value,manifestReady:false,currentProjectId:null,currentProjectName:null,currentManifestVersion:null,sync:null}:value);setSyncPhase("");setNotice("Current Studio manifest cleared. Studio will import nothing until CreatorMake sends an active project.");}catch(error){setNotice(error instanceof Error?error.message:"Could not clear the current project manifest.");}finally{setBusy(false);}};

  useEffect(()=>{if(!open)return;let active=true;const poll=async()=>{const value=await refreshHealth(false);await refreshPublishing();if(!active)return;const sync=value?.sync;if(sync?.status==="running"){setSyncPhase("Importing...");setNotice(sync.message??"Studio is importing the current project...");}if(sync&&(sync.status==="completed"||sync.status==="failed")&&lastCompletedSync.current!==`${sync.id}:${sync.status}`){lastCompletedSync.current=`${sync.id}:${sync.status}`;setSyncPhase(sync.status==="completed"?"Sync complete.":"");setNotice(sync.status==="completed"?(sync.message??"Sync complete."):`Studio sync failed: ${sync.error??sync.message??"Unknown error."}`);}const job=value?.publishing?.job;if(job&&(job.status==="completed"||job.status==="failed")&&lastCompletedPublish.current!==`${job.id}:${job.status}`){lastCompletedPublish.current=`${job.id}:${job.status}`;setNotice(job.status==="completed"?`${job.message} Studio will apply the permanent IDs when connected.`:`Publish failed: ${job.error??job.message}`);}};void poll();const timer=window.setInterval(()=>void poll(),2000);return()=>{active=false;window.clearInterval(timer);};},[open,refreshHealth,refreshPublishing]);

  useEffect(()=>{if(!quickSyncToken||quickSyncToken===lastQuickSyncToken.current)return;lastQuickSyncToken.current=quickSyncToken;void syncPreview(true);},[quickSyncToken]);

  if(!open)return null;
  const copyLua=async()=>{try{await navigator.clipboard.writeText(output.lua);setNotice("Lua copied to the clipboard.");}catch{setNotice("Clipboard access was unavailable.");}};
  const update=<K extends keyof RobloxExportOptions>(key:K,value:RobloxExportOptions[K])=>setOptions((current)=>({...current,[key]:value}));
  const updateMapping=(asset:RobloxRenderAsset,value:string)=>{const normalized=normalizeRobloxAssetId(value),key=assetMappingKey(asset.sourceId,asset.visualHash),next={...mappings,[key]:normalized||value.trim()};if(!next[key])delete next[key];setMappings(next);localStorage.setItem(mappingStorageKey(project.id),JSON.stringify(next));};
  const downloadPlugin=()=>{try{const model=createRobloxPluginModel(CREATORMAKE_PRODUCTION_ORIGIN);download(model,creatorMakePluginFilename(CREATORMAKE_PRODUCTION_ORIGIN),"application/xml");setNotice(`CreatorMake Studio plugin v${health?.pluginVersionRequired??CREATORMAKE_PLUGIN_VERSION} downloaded for ${CREATORMAKE_PRODUCTION_ORIGIN}/. Replace the local copy, then reload it in Studio.`);}catch(error){setNotice(error instanceof Error?error.message:"Plugin generation failed.");}};
  const publishConfigured=publishing?.config.configured===true,publishBusy=publishing?.job?.status==="pending"||publishing?.job?.status==="running";
  const connectionHelp=!health?{level:"error",what:"Local Studio Sync is not reachable.",why:`CreatorMake could not validate ${LOCAL_SYNC_ORIGIN}/health.`,next:"Start the CreatorMake bridge, then recheck the connection."}:!bridgeCurrent?{level:"error",what:"CreatorMake and the local bridge do not match.",why:`Web expects bridge ${CREATORMAKE_BRIDGE_VERSION} / protocol ${CREATORMAKE_PROTOCOL_VERSION}; received ${health.bridgeVersion??"unknown"} / ${health.protocolVersion??"unknown"}.`,next:"Restart this repository’s current development environment so its bridge replaces the outdated process."}:health.connectionState==="PLUGIN_OUTDATED"?{level:"error",what:"The Studio plugin is outdated.",why:`Installed build ${health.plugins?.[0]?.pluginVersion??"unknown"}; CreatorMake requires ${health.pluginVersionRequired??CREATORMAKE_PLUGIN_VERSION}.`,next:"Download the current plugin, replace the old copy, and reload Studio."}:health.connectionState!=="STUDIO_CONNECTED"||!pluginOnline?{level:"warning",what:"The bridge is ready, but Studio is offline.",why:"No compatible plugin heartbeat has reached the bridge yet.",next:"Open Roblox Studio, enable HTTP requests, and reload CreatorMake Studio Sync."}:{level:"success",what:"CreatorMake is connected to Roblox Studio.",why:`Web, bridge, plugin, and protocol ${health.protocolVersion} are compatible.`,next:"Preview in PlayerGui or deploy the managed ScreenGui to StarterGui."};

  return <div className="dialog-overlay" role="presentation"><section className="roblox-export-dialog" role="dialog" aria-modal="true" aria-label="Roblox Studio Sync">
    <header><div><span className="eyebrow">ROBLOX STUDIO</span><h2>Preview locally. Deploy to every player.</h2><p>PlayerGui is a temporary preview. Permanent CreatorMake projects install into StarterGui, which Roblox copies to each player.</p></div><button className="dialog-close" aria-label="Close Roblox export" onClick={onClose}><X size={18}/></button></header>
    <aside className="roblox-export-settings">
      <label><span>ScreenGui</span><input value={options.screenGuiName} onChange={(event)=>update("screenGuiName",safeName(event.target.value))}/></label>
      <label><span>Deploy Target</span><input value="StarterGui — Every Player" readOnly aria-label="Deploy Target"/></label>
      <label><span>Reset On Spawn</span><input type="checkbox" checked={options.resetOnSpawn} onChange={(event)=>update("resetOnSpawn",event.target.checked)}/></label>
      <label><span>Visual Mode</span><select value={options.visualMode} onChange={(event)=>update("visualMode",event.target.value as RobloxVisualMode)}><option value="ADAPTIVE">ADAPTIVE · Native + exact shapes</option><option value="PIXEL_ACCURATE">PIXEL ACCURATE · Exact all-raster</option><option value="NATIVE">NATIVE · Editable approximation</option></select></label>
      <label><span>Sizing</span><select value={options.sizingMode} onChange={(event)=>update("sizingMode",event.target.value as RobloxSizingMode)}>{["AUTO","SCALE","OFFSET","HYBRID"].map((mode)=><option key={mode}>{mode}</option>)}</select></label>
      <label><span>Reference Resolution</span><select value={options.resolution.label} onChange={(event)=>{const resolution=ROBLOX_RESOLUTIONS.find((item)=>item.label===event.target.value);if(resolution)update("resolution",resolution);}}>{ROBLOX_RESOLUTIONS.map((resolution)=><option key={resolution.label}>{resolution.label}</option>)}</select></label>
      {options.visualMode!=="NATIVE"?<label><span>Render Quality · {project.exportOptions.renderedVisualQuality.replaceAll("_"," ")}</span><select value={options.renderScale} onChange={(event)=>update("renderScale",Number(event.target.value)as RobloxRenderScale)}>{([1,2,3,4,6,8]as const).map((scale)=><option key={scale} value={scale}>{scale}x{scale===resolveProjectRenderScale(project.exportOptions)?" · Project setting":""}</option>)}</select></label>:<div className="export-checks"><span>Native reconstruction</span>{([["includeStroke","UIStroke"],["includeCorners","UICorner"],["includeGradients","UIGradient"],["includeLayouts","Layouts"],["includeConstraints","Constraints"]]as const).map(([key,label])=><label key={key}><input type="checkbox" checked={options[key]} onChange={(event)=>update(key,event.target.checked)}/>{label}</label>)}</div>}
      {options.visualMode!=="NATIVE"?<><div className="compatibility-summary"><span className="native"><b>{counts.native}</b> native</span><span className="approximation"><b>{counts.approximation}</b> hybrid</span><span className="unsupported"><b>{counts.unsupported}</b> rasterized</span></div><div className="pixel-asset-summary"><span><b>{assetCounts.total}</b> PNGs</span><span><b>{assetCounts.published}</b> published</span><span><b>{assetCounts.needsPublish}</b> preview-only</span><span className={assetCounts.errors?"error":""}><b>{assetCounts.errors}</b> errors</span></div></>:<div className="compatibility-summary"><span className="native"><b>{counts.native}</b> native-ready</span><span className="approximation"><b>{counts.approximation}</b> approximated</span><span className="unsupported"><b>{counts.unsupported}</b> unsupported</span></div>}
      <section className="export-directions"><strong>Preview vs deployment</strong><ol><li>Preview builds a temporary current-player copy.</li><li>Publish or map permanent visual assets.</li><li>Sync to StarterGui for every player.</li></ol><button onClick={downloadPlugin}><Download size={13}/> Download Plugin v{health?.pluginVersionRequired??CREATORMAKE_PLUGIN_VERSION}</button></section>
    </aside>
    <main className="roblox-export-main">
      <nav>{view!=="studio"&&<button onClick={()=>setView("studio")}>studio</button>}{view!=="studio"&&(["preview","assets","hierarchy","lua","compatibility"]as const).map((item)=><button key={item} className={view===item?"active":""} onClick={()=>setView(item)}>{item}</button>)}</nav>
      {view==="studio"&&<div className="studio-sync-panel">
        <section className={`studio-connection ${summary.status}`}><span className="status-dot"/><div><strong>{localStatus==="connecting"?"TESTING CONNECTION…":studioStateText}</strong><small>{health?.service??LOCAL_SYNC_ORIGIN}{health?.protocolVersion?` · Protocol ${health.protocolVersion}`:""}</small></div></section><section className={`connection-guidance ${connectionHelp.level}`}><dl><div><dt>WHAT</dt><dd>{connectionHelp.what}</dd></div><div><dt>WHY</dt><dd>{connectionHelp.why}</dd></div><div><dt>NEXT</dt><dd>{connectionHelp.next}</dd></div></dl><div><button onClick={()=>void testLocal()} disabled={busy}><RefreshCw size={12}/> Recheck</button>{health?.connectionState==="PLUGIN_OUTDATED"&&<button onClick={downloadPlugin}><Download size={12}/> Update Plugin</button>}</div></section>
        <section className="sync-preview"><header><div><span>CURRENT PROJECT</span><strong>{syncPhase||health?.sync?.message||"Ready to send the active document only"}</strong></div><ImageIcon size={18}/></header><div><span>Project<b>{project.name}</b></span><span>Project ID<b>{project.id}</b></span><span>Objects<b>{project.elements.length}</b></span><span>Presets exported<b>0</b></span></div><div className="pixel-preview-list">{project.elements.filter((element)=>!element.hidden).slice(0,5).map((element)=><p key={element.id}><strong>{element.name}</strong><span>{exportMapping(element,options.visualMode)}</span></p>)}</div></section>
        <button className="studio-primary sync-to-studio" onClick={()=>void syncPreview()} disabled={busy||rendering}><PlugZap size={15}/> {rendering?"RENDERING CHANGED VISUALS…":busy?(syncPhase.toUpperCase()||"SYNC IN PROGRESS…"):"SYNC CURRENT PROJECT · PLAYERGUI"}</button>
        <section className="sync-preview"><header><div><span>DEPLOY TARGET</span><strong>{assetCounts.needsPublish>0?"StarterGui — Local Studio Import":"StarterGui — Every Player · Published"}</strong></div><ShieldCheck size={18}/></header><div><span>Managed ScreenGui<b>{options.screenGuiName}</b></span><span>Runtime<b>Client</b></span><span>Reset On Spawn<b>{options.resetOnSpawn?"Yes":"No"}</b></span><span>Multi-player ready<b>{assetCounts.needsPublish>0?"After publishing":"Yes"}</b></span></div><small>{assetCounts.needsPublish>0?"Local import writes the full hierarchy and RGBA visuals into StarterGui now. Publish or map the same visual hashes before shipping the experience.":"Published sync updates only the matching CreatorMake-managed StarterGui source."}</small></section>
        <button className="studio-primary" onClick={()=>void syncStarterGui()} disabled={busy||rendering}><ShieldCheck size={15}/> {busy?(syncPhase.toUpperCase()||"SYNC IN PROGRESS…"):"SYNC CURRENT PROJECT TO STARTERGUI"}</button>
        <section className="sync-preview publishing-card"><header><div><span>PUBLISHING</span><strong>{publishConfigured?`${publishing?.needsPublish??assetCounts.needsPublish} unique visual(s) need publishing`:"NOT CONFIGURED · Preview remains available"}</strong></div><ShieldCheck size={18}/></header><div><span>Preview-only<b>{publishing?.previewOnlyAssets??assetCounts.needsPublish}</b></span><span>Needs publish<b>{publishing?.needsPublish??assetCounts.needsPublish}</b></span><span>Published<b>{publishing?.publishedVisuals??assetCounts.published}</b></span><span>Status<b>{publishBusy?`${publishing?.job?.completed??0}/${publishing?.job?.total??0}`:publishConfigured?"Ready":"Off"}</b></span></div>{!publishConfigured&&<small>Set ROBLOX_OPEN_CLOUD_API_KEY, ROBLOX_CREATOR_TYPE, and ROBLOX_CREATOR_ID in the CreatorMake server environment. Credentials never enter the browser or Studio.</small>}</section>
        <button className="studio-primary" onClick={()=>void publishAssets()} disabled={busy||rendering||publishBusy||!publishConfigured}><ShieldCheck size={15}/> {publishBusy?publishing?.job?.message:"PUBLISH ASSETS TO ROBLOX"}</button>
        <details className="studio-sync-advanced"><summary>Settings → Roblox → Diagnostics</summary><div className="studio-diagnostics"><header><strong>CreatorMake Health Diagnostics</strong><button onClick={()=>void testLocal()} disabled={busy}><RefreshCw size={12}/> RECHECK CONNECTION</button></header><dl><div><dt>CreatorMake Web</dt><dd>{CREATORMAKE_APP_VERSION}</dd></div><div><dt>Environment</dt><dd>{environment}</dd></div><div><dt>Bridge</dt><dd>{health?(bridgeCurrent?"Running":"Outdated"):"Missing"}</dd></div><div><dt>Bridge Version</dt><dd>{health?.bridgeVersion??"—"}</dd></div><div><dt>Bridge Protocol</dt><dd>{health?.protocolVersion??"—"}</dd></div><div><dt>Current Project</dt><dd>{health?.currentProjectName??"None staged"}</dd></div><div><dt>Current Project ID</dt><dd>{health?.currentProjectId??"—"}</dd></div><div><dt>Manifest Endpoint</dt><dd>{health?.currentManifestEndpoint??"/project/current/manifest"}</dd></div><div><dt>Studio Plugin</dt><dd>{health?.connectionState??"Missing"}</dd></div><div><dt>Plugin Version</dt><dd>{health?.diagnostics?.pluginVersion??"—"} / required {health?.pluginVersionRequired??CREATORMAKE_PLUGIN_VERSION}</dd></div><div><dt>Plugin Protocol</dt><dd>{health?.diagnostics?.pluginProtocol??"—"}</dd></div><div><dt>Production Site</dt><dd><a href={`${CREATORMAKE_PRODUCTION_ORIGIN}/`} target="_blank" rel="noreferrer">{productionStatus} · {CREATORMAKE_PRODUCTION_ORIGIN}/</a></dd></div><div><dt>Last Successful Sync</dt><dd>{health?.lastSuccessfulSyncAt?new Date(health.lastSuccessfulSyncAt).toLocaleString():"—"}</dd></div><div><dt>Deploy Target</dt><dd>{health?.diagnostics?.deployTarget??"StarterGui — Every Player"}</dd></div><div><dt>Managed ScreenGui</dt><dd>{health?.diagnostics?.managedScreenGui??options.screenGuiName}</dd></div><div><dt>Multi-player Ready</dt><dd>{health?.diagnostics?.multiPlayerReady===false?"No":"Yes"}</dd></div><div><dt>RGBA Transfer</dt><dd>{health?.diagnostics?.pixelTransport??"Not staged"}</dd></div>{health?.diagnostics?.lastError&&<div className="diagnostic-error"><dt>Last Error</dt><dd>{health.diagnostics.lastError}</dd></div>}</dl></div><div className="studio-sync-actions"><button onClick={()=>void stageBasicConnectionTest()} disabled={busy}>Validate Basic Test</button><button onClick={()=>void clearCurrentManifest()} disabled={busy}>Clear Current Manifest</button><button onClick={()=>setView("preview")}>Export Preview</button><button onClick={()=>setView("assets")}>Visual Hashes / Mappings</button><button onClick={()=>setView("hierarchy")}>Manifest Hierarchy</button><button onClick={()=>setView("lua")}>Generated Lua</button><button onClick={()=>setView("compatibility")}>Compatibility</button><button onClick={downloadPlugin}><Download size={14}/> Download Plugin</button></div></details>
        <p className="sync-security"><ShieldCheck size={14}/> PlayerGui preview is temporary and local. StarterGui is the permanent every-player source. Publishing uses original staged PNG bytes through Roblox Open Cloud only when you click Publish.</p>
      </div>}
      {view==="preview"&&<div className="roblox-export-preview"><header><div><strong>CREATORMAKE VIEW <span>→</span> ROBLOX EXPORT VIEW</strong><small>Each layer remains separate. Rasterized pixels come from the same canvas renderer used by CreatorMake.</small></div><section className="geometry-compare-controls"><button className={compareGeometry?"active":""} onClick={()=>setCompareGeometry((value)=>!value)}>Compare Geometry</button>{compareGeometry&&<><label>Overlay <input aria-label="Geometry overlay opacity" type="range" min="0" max="100" value={compareOpacity} onChange={(event)=>setCompareOpacity(Number(event.target.value))}/><b>{compareOpacity}%</b></label><button className={showDifference?"active":""} onClick={()=>setShowDifference((value)=>!value)}>Difference</button></>}</section></header>{project.elements.filter((element)=>!element.hidden).map((element)=>{const result=classifyRobloxElement(element),asset=renderAssets.find((item)=>renderAssetElementId(item)===element.id&&(item.visualPart==="background"||item.visualPart==="full"))??renderAssets.find((item)=>renderAssetElementId(item)===element.id);return <article className={compareGeometry?"comparing":""} key={element.id}><div><strong>{element.name}</strong><small>{element.type} · {element.width} × {element.height}</small>{asset?.fidelity&&<small className={asset.fidelity.passed?"fidelity-pass":"fidelity-fail"}>{asset.fidelity.matchPercent}% match · bounds {asset.fidelity.boundsMatch?"PASS":"FAIL"} · transform {asset.fidelity.transformMatch?"PASS":"FAIL"} · alpha edges {asset.fidelity.alphaEdgeSafety?"PASS":"FAIL"}</small>}</div><span className={`export-classification ${result.classification.toLowerCase()}`}>{options.visualMode==="PIXEL_ACCURATE"?"RASTERIZED":options.visualMode==="NATIVE"?"NATIVE":result.classification}</span><div className="export-preview-result">{compareGeometry&&asset?.dataUrl?<div className="geometry-compare-canvas">{showDifference&&asset.differenceDataUrl?<img className="geometry-difference" src={asset.differenceDataUrl} alt={`${element.name} pixel difference`} width={220} height={150}/>:<><img className="geometry-source" src={asset.sourceDataUrl??asset.dataUrl} alt={`${element.name} CreatorMake source render`} width={220} height={150}/><img className="geometry-export" style={{opacity:compareOpacity/100}} src={asset.dataUrl} alt={`${element.name} Roblox export overlay`} width={220} height={150}/></>}</div>:asset?.dataUrl?<img src={asset.dataUrl} alt={`${element.name} exported visual`} width={72} height={52}/>:<ImageIcon size={20}/>}<span>{exportMapping(element,options.visualMode)}<small>{result.reasons.join(" · ")||"Direct native match"}</small>{compareGeometry&&asset?.fidelity&&<small>Source: {asset.fidelity.source==="live-canvas"?"mounted CreatorMake canvas":"isolated CreatorMake renderer"} · threshold {asset.fidelity.thresholdPercent}%</small>}</span></div></article>;})}</div>}
      {view==="assets"&&<div className="pixel-assets"><header><div><strong>Advanced · layout, visual, raster bounds and mappings</strong><small>Layout-only changes reuse the current hash. Open Cloud publishes one PNG per unique dirty hash.</small></div><button onClick={()=>void renderCurrent()} disabled={rendering||options.visualMode==="NATIVE"}><RefreshCw size={13}/>{rendering?" Rendering…":" Render / Refresh"}</button></header>{options.visualMode==="NATIVE"?<div className="compatibility-clear"><strong>Switch to Adaptive or Pixel Accurate mode to render transparent per-object visuals.</strong></div>:renderAssets.map((asset)=><article key={`${asset.sourceId}-${asset.visualHash}`} className={asset.status}><div className="asset-thumb">{asset.dataUrl?<img src={asset.dataUrl} alt="" width={52} height={42}/>:<ImageIcon size={20}/>}</div><div className="asset-info"><strong>{asset.elementName}</strong><small>{asset.classification??"RASTERIZED"} · {asset.visualPart??"full"} · layout {asset.layoutWidth}×{asset.layoutHeight} · visual {Number(asset.visualBounds.width.toFixed(3))}×{Number(asset.visualBounds.height.toFixed(3))} @ {Number(asset.visualBounds.x.toFixed(3))},{Number(asset.visualBounds.y.toFixed(3))} · raster {asset.renderPixelWidth}×{asset.renderPixelHeight}px · {Number(asset.scale.toFixed(3))}x</small><code>{asset.visualHash}</code>{asset.scaleWarning&&<em className="quality-warning">{asset.scaleWarning}</em>}{asset.localPath&&<small>{asset.localPath}</small>}{asset.error&&<em>{asset.error}</em>}</div><span className="asset-status">{displayStatus(asset)}</span><div className="asset-actions"><input aria-label={`${asset.elementName} Roblox asset ID`} title="Advanced manual mapping override" placeholder="Optional rbxassetid:// mapping" value={mappings[assetMappingKey(asset.sourceId,asset.visualHash)]??asset.robloxAssetId??""} onChange={(event)=>updateMapping(asset,event.target.value)}/><button disabled={!asset.dataUrl&&!asset.localUrl} onClick={()=>{const filename=`${safeName(asset.elementName)}-${asset.visualHash}.png`;if(asset.dataUrl)downloadUrl(asset.dataUrl,filename);else if(asset.localUrl)downloadUrl(`${LOCAL_SYNC_ORIGIN}${asset.localUrl}`,filename);}}><Download size={12}/> PNG</button></div></article>)}</div>}
      {view==="hierarchy"&&<pre className="roblox-hierarchy">{output.hierarchy}</pre>}
      {view==="lua"&&<><div className={`lua-status ${verification.valid?"valid":"invalid"}`}><CheckCircle2 size={13}/>{verification.valid?"Structural syntax checks passed":verification.errors.join(" ")}</div><textarea className="lua-output" readOnly value={output.lua} aria-label="Generated Roblox Lua"/></>}
      {view==="compatibility"&&<div className="compatibility-list">{output.compatibility.length?output.compatibility.map((issue,index)=><article key={`${issue.elementId}-${issue.feature}-${index}`} className={issue.level}><span>{issue.level}</span><div><strong>{issue.elementName} · {issue.feature}</strong><p>{issue.message}</p></div></article>):<div className="compatibility-clear"><ShieldCheck size={28}/><strong>All inspected features are ready.</strong></div>}<section className="unsupported-options"><strong>{options.visualMode==="PIXEL_ACCURATE"?"Studio Preview truth":options.visualMode==="ADAPTIVE"?"Adaptive export plan":"Native compatibility"}</strong><p>{options.visualMode==="PIXEL_ACCURATE"?"CreatorMake preserves every element as a retained EditableImage. Permanent asset IDs are only created by explicit Open Cloud publishing.":options.visualMode==="ADAPTIVE"?"Native-safe layers stay editable. Unsupported geometry is rendered as a cropped transparent PNG inside a responsive Roblox container.":"Native export remains an editable approximation for complex visuals."}</p></section></div>}
    </main>
    <footer><output>{notice}</output><button onClick={()=>void copyLua()}><Clipboard size={13}/> Copy Lua</button><button onClick={()=>download(output.lua,`${safeName(options.screenGuiName)}.lua`,"text/plain")}><Download size={13}/> Lua</button><button onClick={()=>download(JSON.stringify(project,null,2),`${project.name.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}.creatormake.json`,"application/json")}><FileJson size={13}/> Project JSON</button></footer>
  </section></div>;
}
