"use client";

import { Box, BoxSelect, ChevronDown, Circle, Component, Eye, Frame, Hexagon, ImageIcon, Maximize2, Minus, MousePointer2, PanelLeftClose, PanelRightClose, PenTool, PlugZap, Redo2, Search, Settings, Square, Star, Type, Undo2 } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { GEOMETRY_OPTIONS } from "@/lib/editor/geometry";
import type { ElementType, GeometryKind, ViewAction } from "@/lib/editor/types";
import type { StudioConnectionSummary } from "./RobloxExportDialog";
import { CREATORMAKE_BRIDGE_ORIGIN } from "@/lib/creatormake-version.js";

type Props = { projectName: string; status: "saving" | "saved" | "unsaved" | "error"; studioStatus:StudioConnectionSummary; canUndo: boolean; canRedo: boolean; zoom: number; penActive:boolean; onPen:()=>void; onSelectTool:()=>void; onAdd: (type: ElementType) => void; onImportImage:()=>void; onAddGeometry:(kind:GeometryKind)=>void; onUndo: () => void; onRedo: () => void; onPreview: () => void; onView: (action: ViewAction) => void; onExport: () => void; onProjects: () => void; onToggleLeft: () => void; onToggleRight: () => void; onFocus: () => void; onCommand: () => void;onSettings:()=>void };

export function TopToolbar(props: Props) {
  const tools: { label: string; type?: ElementType; icon: LucideIcon; disabled?: boolean; shortcut?: string }[] = [
    { label: "Select", icon: MousePointer2, shortcut: "V" }, { label: "Pen", icon: PenTool, shortcut: "P" }, { label: "Frame", type: "frame", icon: Frame, shortcut: "F" }, { label: "Container", type: "container", icon: BoxSelect }, { label: "Scroll", type: "scrolling-frame", icon: BoxSelect },
    { label: "Text", type: "text", icon: Type, shortcut: "T" }, { label: "Rectangle", type: "rectangle", icon: Square, shortcut: "R" }, { label: "Rounded", type: "roundRect", icon: Box },
    { label: "Ellipse", type: "ellipse", icon: Circle, shortcut: "O" }, { label: "Line", type: "line", icon: Minus, shortcut: "L" }, { label: "Polygon", type: "polygon", icon: Hexagon }, { label: "Star", type: "star", icon: Star },
    { label: "Button", type: "button", icon: Box }, { label: "Image", icon: ImageIcon }, { label: "Component", icon: Component, disabled: true },
  ];
  return <header className="topbar">
    <button className="brand" onClick={props.onProjects} title="Manage projects"><span className="brand-mark">CM</span><strong>CREATORMAKE</strong></button>
    <button className={`project-chip save-${props.status}`} onClick={props.onProjects}><span>{props.projectName}</span><small>{props.status === "saving" ? "Saving…" : props.status === "unsaved" ? "● Unsaved changes" : props.status === "error" ? "Save failed" : "✓ Saved locally"}</small></button>
    <nav className="toolstrip" aria-label="Editor tools">{tools.map(({ label, type, icon: Icon, disabled, shortcut }) => <button key={label} className={`tool ${(label==="Select"&&!props.penActive)||(label==="Pen"&&props.penActive)?"active":""}`} onClick={() => label==="Select"?props.onSelectTool():label==="Pen"?props.onPen():label==="Image"?props.onImportImage():type&&props.onAdd(type)} disabled={disabled} title={disabled ? `${label} is not implemented yet` : `${label}${shortcut ? ` (${shortcut})` : ""}`}><Icon size={15}/><span>{label}</span></button>)}<label className="tool shape-tool" title="Insert an editable vector shape"><Hexagon size={15}/><span>Shapes</span><select aria-label="Advanced shape" defaultValue="" onChange={(event)=>{if(event.target.value)props.onAddGeometry(event.target.value as GeometryKind);event.currentTarget.value="";}}><option value="" disabled>Choose shape</option>{GEOMETRY_OPTIONS.map((item)=><option key={item.kind} value={item.kind}>{item.label}</option>)}</select></label><span className="divider"/><button className="icon-button" aria-label="Undo" onClick={props.onUndo} disabled={!props.canUndo}><Undo2 size={16}/></button><button className="icon-button" aria-label="Redo" onClick={props.onRedo} disabled={!props.canRedo}><Redo2 size={16}/></button></nav>
    <div className="top-actions"><button className="icon-button" aria-label="Toggle left panel" onClick={props.onToggleLeft}><PanelLeftClose size={15}/></button><button className="icon-button" aria-label="Toggle right panel" onClick={props.onToggleRight}><PanelRightClose size={15}/></button><button className="icon-button" aria-label="Command palette" onClick={props.onCommand}><Search size={15}/></button><button onClick={props.onPreview}><Eye size={14}/> Preview</button><label className="zoom-control">{formatZoom(props.zoom)} <ChevronDown size={13}/><select aria-label="Canvas view" defaultValue="" onChange={(event) => { if (event.target.value) props.onView(event.target.value as ViewAction); event.currentTarget.value = ""; }}><option value="" disabled>Canvas view</option><option value="zoom-in">Zoom in</option><option value="zoom-out">Zoom out</option><option value="actual">100% actual size</option><option value="fit-selection">Fit selection</option><option value="fit-frame">Fit frame</option><option value="fit-all">Fit all</option></select></label><button className="icon-button" aria-label="Focus mode" onClick={props.onFocus} title="Focus mode"><Maximize2 size={15}/></button><button className={`export studio-toolbar-status ${props.studioStatus.status} ${props.studioStatus.pluginOnline?"online":""}`} onClick={props.onExport} title={props.studioStatus.status==="connected"?`Local Studio Sync is ready at ${CREATORMAKE_BRIDGE_ORIGIN}`:"Open local Studio Sync setup"}><span className="status-dot"/><PlugZap size={14}/> {props.studioStatus.status==="connected"?"Studio":props.studioStatus.status==="pairing"?"Testing":"Roblox"}</button><button className="icon-button" title="CreatorMake settings" aria-label="Settings" onClick={props.onSettings}><Settings size={15}/></button></div>
  </header>;
}

const formatZoom = (zoom: number) => zoom < .1 ? `${Math.round(zoom * 1000) / 10}%` : `${Math.round(zoom * 100)}%`;
