"use client";

import { ChevronDown, Download, Eye, Hexagon, Laptop, Layers3, Maximize2, Moon, MousePointer2, PanelLeftClose, PanelRightClose, PenTool, PlugZap, Plus, Redo2, Search, Settings, ShieldCheck, Sun, Undo2, Upload } from "lucide-react";
import type { ElementType, GeometryKind, ViewAction } from "@/lib/editor/types";
import { WORKSPACE_MODES, type WorkspaceMode } from "@/lib/ui/interface-themes";
import type { StudioConnectionSummary } from "./RobloxExportDialog";
import { CREATORMAKE_BRIDGE_ORIGIN } from "@/lib/creatormake-version.js";

type Props={projectName:string;status:"saving"|"saved"|"unsaved"|"error";studioStatus:StudioConnectionSummary;robloxIssueCount?:number;canUndo:boolean;canRedo:boolean;canGroup:boolean;zoom:number;penActive:boolean;directSelectionActive:boolean;appearance:"light"|"dark"|"system";themeName:string;workspaceMode:WorkspaceMode;onCycleAppearance:()=>void;onWorkspaceMode:(mode:WorkspaceMode)=>void;onPen:()=>void;onDirectSelect:()=>void;onSelectTool:()=>void;onAdd:(type:ElementType)=>void;onAddTextBox:()=>void;onGroup:()=>void;onImportImage:()=>void;onAddGeometry:(kind:GeometryKind)=>void;onUndo:()=>void;onRedo:()=>void;onPreview:()=>void;onView:(action:ViewAction)=>void;onExport:()=>void;onSync:()=>void;onProjects:()=>void;onToggleLeft:()=>void;onToggleRight:()=>void;onFocus:()=>void;onCommand:()=>void;onSettings:()=>void};

const SHAPES:{label:string;kind:GeometryKind}[]=[{label:"Rectangle",kind:"rectangle"},{label:"Rounded Rectangle",kind:"rounded-rectangle"},{label:"Ellipse",kind:"ellipse"},{label:"Line",kind:"line"},{label:"Polygon",kind:"polygon"},{label:"Star",kind:"star"},{label:"Custom Path",kind:"custom-path"}];
const CREATE_TOOLS:{label:string;value:ElementType|"textbox"|"group"|"image"}[]=[{label:"Frame",value:"frame"},{label:"Text",value:"text"},{label:"Button",value:"button"},{label:"Image",value:"image"},{label:"ScrollingFrame",value:"scrolling-frame"},{label:"TextBox",value:"textbox"},{label:"Group",value:"group"}];

export function TopToolbar(props:Props){
  const AppearanceIcon=props.appearance==="light"?Sun:props.appearance==="dark"?Moon:Laptop;
  const create=(value:string)=>{if(value==="image")props.onImportImage();else if(value==="textbox")props.onAddTextBox();else if(value==="group")props.onGroup();else props.onAdd(value as ElementType);};
  const importItem=(value:string)=>{if(value==="project")props.onProjects();else props.onImportImage();};
  return <header className="topbar">
    <button className="brand" onClick={props.onProjects} title="Manage projects"><span className="brand-mark">CM</span><strong>CREATORMAKE</strong></button>
    <button className={`project-chip save-${props.status}`} onClick={props.onProjects}><span>{props.projectName}</span><small>{props.status==="saving"?"Saving…":props.status==="unsaved"?"● Unsaved changes":props.status==="error"?"Save failed":"✓ Saved locally"}</small></button>
    <nav className="toolstrip grouped" aria-label="Editor tools">
      <ToolGroup label="SELECT"><button className={`tool icon-tool ${!props.penActive?"active":""}`} onClick={props.onSelectTool} data-tooltip="Select objects · V" aria-label="Select tool"><MousePointer2 size={15}/></button></ToolGroup>
      <ToolGroup label="CREATE"><label className="tool flyout-tool workflow-menu" data-tooltip="Create a Roblox UI object"><Plus size={15}/><span>+ Create</span><ChevronDown size={11}/><select aria-label="Create object" defaultValue="" onChange={(event)=>{if(event.target.value)create(event.target.value);event.currentTarget.value="";}}><option value="" disabled>Create object</option>{CREATE_TOOLS.map((item)=><option key={item.value} value={item.value} disabled={item.value==="group"&&!props.canGroup}>{item.label}</option>)}</select></label></ToolGroup>
      <ToolGroup label="IMPORT"><label className="tool flyout-tool workflow-menu" data-tooltip="Import an image, SVG, reference, or CreatorMake project"><Upload size={14}/><span>Import</span><ChevronDown size={11}/><select aria-label="Import" defaultValue="" onChange={(event)=>{if(event.target.value)importItem(event.target.value);event.currentTarget.value="";}}><option value="" disabled>Import</option><option value="image">Image</option><option value="svg">SVG</option><option value="reference">Reference</option><option value="project">Project</option></select></label></ToolGroup>
      <ToolGroup label="VECTOR"><button className={`tool icon-tool ${props.penActive?"active":""}`} onClick={props.onPen} data-tooltip="Pen · click for corners, drag for curves · P" aria-label="Pen tool"><PenTool size={15}/></button><button className={`tool icon-tool ${props.directSelectionActive?"active":""}`} onClick={props.onDirectSelect} data-tooltip="Direct Selection · edit nodes and Bezier handles · A" aria-label="Direct selection"><MousePointer2 size={14}/><i className="direct-node-dot"/></button><label className="tool flyout-tool" data-tooltip="Shapes · editable vector geometry"><Hexagon size={15}/><span>Shapes</span><ChevronDown size={11}/><select aria-label="Shape tools" defaultValue="" onChange={(event)=>{if(event.target.value)props.onAddGeometry(event.target.value as GeometryKind);event.currentTarget.value="";}}><option value="" disabled>Choose shape</option>{SHAPES.map((item)=><option key={item.kind} value={item.kind}>{item.label}</option>)}</select></label></ToolGroup>
      <span className="divider"/><button className="icon-button" aria-label="Undo" data-tooltip="Undo · Ctrl Z" onClick={props.onUndo} disabled={!props.canUndo}><Undo2 size={16}/></button><button className="icon-button" aria-label="Redo" data-tooltip="Redo · Ctrl Shift Z" onClick={props.onRedo} disabled={!props.canRedo}><Redo2 size={16}/></button>
    </nav>
    <div className="top-actions"><button className="icon-button" aria-label="Toggle left panel" data-tooltip="Toggle library panel" onClick={props.onToggleLeft}><PanelLeftClose size={15}/></button><button className="icon-button" aria-label="Toggle right panel" data-tooltip="Toggle properties panel" onClick={props.onToggleRight}><PanelRightClose size={15}/></button><button className="icon-button" aria-label="Command palette" data-tooltip="Search commands · Ctrl K" onClick={props.onCommand}><Search size={15}/></button><label className="workspace-switcher" data-tooltip="Task-focused workspace"><Layers3 size={13}/><select aria-label="Workspace mode" value={props.workspaceMode} onChange={(event)=>props.onWorkspaceMode(event.target.value as WorkspaceMode)}>{WORKSPACE_MODES.map((item)=><option key={item} value={item}>{item.toUpperCase()}</option>)}</select></label><button onClick={props.onPreview}><Eye size={14}/> Preview</button>{props.workspaceMode==="roblox"&&<button className={`roblox-check ${props.robloxIssueCount?"issues":"ready"}`} onClick={props.onExport} data-tooltip="Show only Roblox export issues that need attention"><ShieldCheck size={14}/> Roblox Check · {props.robloxIssueCount||"Ready"}</button>}<label className="zoom-control">{formatZoom(props.zoom)} <ChevronDown size={13}/><select aria-label="Canvas view" defaultValue="" onChange={(event)=>{if(event.target.value)props.onView(event.target.value as ViewAction);event.currentTarget.value="";}}><option value="" disabled>Canvas view</option><option value="zoom-in">Zoom in</option><option value="zoom-out">Zoom out</option><option value="actual">100% actual size</option><option value="fit-selection">Fit selection</option><option value="fit-frame">Fit frame</option><option value="fit-all">Fit all</option></select></label><button className="icon-button" aria-label="Focus mode" data-tooltip="Focus canvas" onClick={props.onFocus}><Maximize2 size={15}/></button><button className="icon-button appearance-quick-toggle" aria-label={`Appearance: ${props.appearance}. Activate to cycle.`} data-tooltip={`${props.themeName} · ${props.appearance}`} onClick={props.onCycleAppearance}><AppearanceIcon size={15}/></button><button onClick={props.onExport} data-tooltip="Open Roblox export"><Download size={14}/> Export</button><button className={`export studio-toolbar-status ${props.studioStatus.status} ${props.studioStatus.pluginOnline?"online":""}`} onClick={props.onSync} data-tooltip={props.studioStatus.status==="connected"?`Sync current project · ${CREATORMAKE_BRIDGE_ORIGIN}`:"Open Studio Sync and connection diagnostics"}><span className="status-dot"/><PlugZap size={14}/> SYNC · {props.studioStatus.status==="connected"?"CONNECTED":props.studioStatus.status==="pairing"?"TESTING":"OFFLINE"}</button><button className="icon-button" data-tooltip="CreatorMake settings" aria-label="Settings" onClick={props.onSettings}><Settings size={15}/></button></div>
  </header>;
}

function ToolGroup({label,children}:{label:string;children:React.ReactNode}){return <div className="toolbar-group" data-group={label}><span>{label}</span><div>{children}</div></div>;}
const formatZoom=(zoom:number)=>zoom<.1?`${Math.round(zoom*1000)/10}%`:`${Math.round(zoom*100)}%`;
