"use client";

import { BoxSelect, ChevronDown, Eye, Hexagon, ImageIcon, Laptop, Layers3, Maximize2, Moon, MousePointer2, PanelLeftClose, PanelRightClose, PenTool, PlugZap, Redo2, Search, Settings, Sun, Type, Undo2 } from "lucide-react";
import type { ElementType, GeometryKind, ViewAction } from "@/lib/editor/types";
import { WORKSPACE_MODES, type WorkspaceMode } from "@/lib/ui/interface-themes";
import type { StudioConnectionSummary } from "./RobloxExportDialog";
import { CREATORMAKE_BRIDGE_ORIGIN } from "@/lib/creatormake-version.js";

type Props={projectName:string;status:"saving"|"saved"|"unsaved"|"error";studioStatus:StudioConnectionSummary;robloxIssueCount?:number;canUndo:boolean;canRedo:boolean;zoom:number;penActive:boolean;directSelectionActive:boolean;appearance:"light"|"dark"|"system";themeName:string;workspaceMode:WorkspaceMode;onCycleAppearance:()=>void;onWorkspaceMode:(mode:WorkspaceMode)=>void;onPen:()=>void;onDirectSelect:()=>void;onSelectTool:()=>void;onAdd:(type:ElementType)=>void;onImportImage:()=>void;onAddGeometry:(kind:GeometryKind)=>void;onUndo:()=>void;onRedo:()=>void;onPreview:()=>void;onView:(action:ViewAction)=>void;onExport:()=>void;onProjects:()=>void;onToggleLeft:()=>void;onToggleRight:()=>void;onFocus:()=>void;onCommand:()=>void;onSettings:()=>void};

const SHAPES:{label:string;kind:GeometryKind}[]=[{label:"Rectangle",kind:"rectangle"},{label:"Rounded Rectangle",kind:"rounded-rectangle"},{label:"Ellipse",kind:"ellipse"},{label:"Line",kind:"line"},{label:"Polygon",kind:"polygon"},{label:"Star",kind:"star"},{label:"Custom Path",kind:"custom-path"}];
const LAYOUT_TOOLS:{label:string;type:ElementType}[]=[{label:"Frame",type:"frame"},{label:"Container",type:"container"},{label:"ScrollingFrame",type:"scrolling-frame"},{label:"Button",type:"button"},{label:"ImageButton",type:"image-button"}];

export function TopToolbar(props:Props){
  const AppearanceIcon=props.appearance==="light"?Sun:props.appearance==="dark"?Moon:Laptop;
  return <header className="topbar">
    <button className="brand" onClick={props.onProjects} title="Manage projects"><span className="brand-mark">CM</span><strong>CREATORMAKE</strong></button>
    <button className={`project-chip save-${props.status}`} onClick={props.onProjects}><span>{props.projectName}</span><small>{props.status==="saving"?"Saving…":props.status==="unsaved"?"● Unsaved changes":props.status==="error"?"Save failed":"✓ Saved locally"}</small></button>
    <nav className="toolstrip grouped" aria-label="Editor tools">
      <ToolGroup label="SELECT"><button className={`tool icon-tool ${!props.penActive?"active":""}`} onClick={props.onSelectTool} data-tooltip="Select objects · V" aria-label="Select tool"><MousePointer2 size={15}/></button></ToolGroup>
      <ToolGroup label="DRAW"><button className={`tool icon-tool ${props.penActive?"active":""}`} onClick={props.onPen} data-tooltip="Pen · click for corners, drag for curves · P" aria-label="Pen tool"><PenTool size={15}/></button><button className={`tool icon-tool ${props.directSelectionActive?"active":""}`} onClick={props.onDirectSelect} data-tooltip="Direct Selection · edit nodes and Bezier handles · A" aria-label="Direct selection"><MousePointer2 size={14}/><i className="direct-node-dot"/></button><label className="tool flyout-tool" data-tooltip="Shapes · editable vector geometry"><Hexagon size={15}/><span>Shapes</span><ChevronDown size={11}/><select aria-label="Shape tools" defaultValue="" onChange={(event)=>{if(event.target.value)props.onAddGeometry(event.target.value as GeometryKind);event.currentTarget.value="";}}><option value="" disabled>Choose shape</option>{SHAPES.map((item)=><option key={item.kind} value={item.kind}>{item.label}</option>)}</select></label></ToolGroup>
      <ToolGroup label="TEXT"><button className="tool icon-tool" onClick={()=>props.onAdd("text")} data-tooltip="Text layer · T" aria-label="Text tool"><Type size={15}/></button></ToolGroup>
      <ToolGroup label="MEDIA"><button className="tool icon-tool" onClick={props.onImportImage} data-tooltip="Import PNG, JPG, WEBP, GIF, or SVG" aria-label="Import image"><ImageIcon size={15}/></button></ToolGroup>
      <ToolGroup label="LAYOUT"><label className="tool flyout-tool" data-tooltip="Frames, scrolling, and controls"><BoxSelect size={15}/><span>Insert</span><ChevronDown size={11}/><select aria-label="Layout tools" defaultValue="" onChange={(event)=>{if(event.target.value)props.onAdd(event.target.value as ElementType);event.currentTarget.value="";}}><option value="" disabled>Choose layout object</option>{LAYOUT_TOOLS.map((item)=><option key={item.type} value={item.type}>{item.label}</option>)}</select></label></ToolGroup>
      <span className="divider"/><button className="icon-button" aria-label="Undo" data-tooltip="Undo · Ctrl Z" onClick={props.onUndo} disabled={!props.canUndo}><Undo2 size={16}/></button><button className="icon-button" aria-label="Redo" data-tooltip="Redo · Ctrl Shift Z" onClick={props.onRedo} disabled={!props.canRedo}><Redo2 size={16}/></button>
    </nav>
    {props.workspaceMode==="roblox"&&<output className={`roblox-mode-status ${props.robloxIssueCount?"issues":"ready"}`}>{props.robloxIssueCount?`ROBLOX MODE · ${props.robloxIssueCount} ISSUE${props.robloxIssueCount===1?"":"S"}`:"ROBLOX MODE ✓"}</output>}
    <div className="top-actions"><button className="icon-button" aria-label="Toggle left panel" data-tooltip="Toggle library panel" onClick={props.onToggleLeft}><PanelLeftClose size={15}/></button><button className="icon-button" aria-label="Toggle right panel" data-tooltip="Toggle properties panel" onClick={props.onToggleRight}><PanelRightClose size={15}/></button><button className="icon-button" aria-label="Command palette" data-tooltip="Search commands · Ctrl K" onClick={props.onCommand}><Search size={15}/></button><label className="workspace-switcher" data-tooltip="Task-focused workspace"><Layers3 size={13}/><select aria-label="Workspace mode" value={props.workspaceMode} onChange={(event)=>props.onWorkspaceMode(event.target.value as WorkspaceMode)}>{WORKSPACE_MODES.map((item)=><option key={item} value={item}>{item.toUpperCase()}</option>)}</select></label><button onClick={props.onPreview}><Eye size={14}/> Preview</button><label className="zoom-control">{formatZoom(props.zoom)} <ChevronDown size={13}/><select aria-label="Canvas view" defaultValue="" onChange={(event)=>{if(event.target.value)props.onView(event.target.value as ViewAction);event.currentTarget.value="";}}><option value="" disabled>Canvas view</option><option value="zoom-in">Zoom in</option><option value="zoom-out">Zoom out</option><option value="actual">100% actual size</option><option value="fit-selection">Fit selection</option><option value="fit-frame">Fit frame</option><option value="fit-all">Fit all</option></select></label><button className="icon-button" aria-label="Focus mode" data-tooltip="Focus canvas" onClick={props.onFocus}><Maximize2 size={15}/></button><button className="icon-button appearance-quick-toggle" aria-label={`Appearance: ${props.appearance}. Activate to cycle.`} data-tooltip={`${props.themeName} · ${props.appearance}`} onClick={props.onCycleAppearance}><AppearanceIcon size={15}/></button><button className={`export studio-toolbar-status ${props.studioStatus.status} ${props.studioStatus.pluginOnline?"online":""}`} onClick={props.onExport} data-tooltip={props.studioStatus.status==="connected"?`Studio Sync ready · ${CREATORMAKE_BRIDGE_ORIGIN}`:"Open Studio Sync and diagnostics"}><span className="status-dot"/><PlugZap size={14}/> {props.studioStatus.status==="connected"?"Studio":props.studioStatus.status==="pairing"?"Testing":"Roblox"}</button><button className="icon-button" data-tooltip="CreatorMake settings" aria-label="Settings" onClick={props.onSettings}><Settings size={15}/></button></div>
  </header>;
}

function ToolGroup({label,children}:{label:string;children:React.ReactNode}){return <div className="toolbar-group" data-group={label}><span>{label}</span><div>{children}</div></div>;}
const formatZoom=(zoom:number)=>zoom<.1?`${Math.round(zoom*1000)/10}%`:`${Math.round(zoom*100)}%`;
