import { createElement, createId } from "@/lib/editor/project";
import { PRESET_BY_ID } from "./system-presets";
import type { FrameRecipe } from "./types";
import type { EditorElement } from "@/lib/editor/types";

export function createFrameRecipeElements(recipe: FrameRecipe, presetId: string, index = 0): EditorElement[] {
  const preset = PRESET_BY_ID[presetId] ?? PRESET_BY_ID["digital-system"]; const offset = (index % 5) * 18;
  const root = createElement("frame",index); root.id = createId("recipe-frame"); root.name = recipe.name; root.x = 175 + offset; root.y = 90 + offset; root.width = 610; root.height = 420; root.fill = preset.colors.surface; root.borderColor = preset.colors.highlight; root.borderWidth = Math.max(recipe.borderStack.length,preset.borders.width); root.cornerRadius = recipe.radius; root.corners = {tl:recipe.radius,tr:recipe.radius,br:recipe.radius,bl:recipe.radius}; root.shadow = preset.effects.shadow; root.padding = recipe.contentInset;
  if (recipe.corner === "chamfer") root.type = "polygon";
  const elements: EditorElement[] = [root];
  if (recipe.header !== "none") { const header = createElement("rectangle",index); header.name = `${recipe.name} Header`; header.parentId = root.id; header.x = root.x + recipe.contentInset; header.y = root.y + recipe.contentInset; header.width = root.width - recipe.contentInset * 2; header.height = 42; header.fill = preset.colors.accent; header.borderColor = preset.colors.highlight; header.borderWidth = preset.borders.width; header.cornerRadius = Math.min(recipe.radius,6); header.corners = {tl:Math.min(recipe.radius,6),tr:Math.min(recipe.radius,6),br:0,bl:0}; elements.push(header); const title = createElement("text",index); title.name = `${recipe.name} Title`; title.parentId = header.id; title.x = header.x + 16; title.y = header.y + 8; title.width = 330; title.height = 28; title.text = recipe.name.toUpperCase(); title.fill = "transparent"; title.borderWidth = 0; title.borderColor = "transparent"; title.shadow = "none"; title.padding = 0; title.fontFamily = preset.typography.family; title.fontSize = preset.typography.scale === "display" ? 18 : 14; title.fontWeight = preset.typography.weight; elements.push(title); for (let i=0;i<recipe.controls;i++) { const control = createElement("button",i); control.name = `Window Control ${i+1}`; control.parentId = header.id; control.x = header.x + header.width - 30 - i * 30; control.y = header.y + 8; control.width = 23; control.height = 23; control.text = i === 0 ? "×" : i === 1 ? "□" : "_"; control.fill = preset.colors.surfaceAlt; control.borderColor = preset.colors.shadow; control.borderWidth = preset.borders.width; control.cornerRadius = preset.geometry.radius; control.corners = {tl:preset.geometry.radius,tr:preset.geometry.radius,br:preset.geometry.radius,bl:preset.geometry.radius}; control.padding = 0; control.fontSize = 11; elements.push(control); } }
  const content = createElement("container",index); content.name = `${recipe.name} Content`; content.parentId = root.id; content.x = root.x + recipe.contentInset + 4; content.y = root.y + (recipe.header === "none" ? recipe.contentInset : 62); content.width = root.width - (recipe.contentInset + 4) * 2; content.height = root.height - (recipe.header === "none" ? recipe.contentInset * 2 : 78); content.fill = preset.colors.surfaceAlt; content.borderColor = preset.colors.shadow; content.borderWidth = Math.max(1,preset.borders.width-1); content.cornerRadius = Math.max(0,recipe.radius-2); content.corners = {tl:content.cornerRadius,tr:content.cornerRadius,br:content.cornerRadius,bl:content.cornerRadius}; content.shadow = recipe.depth === "recessed" || recipe.depth.includes("bezel") ? "inset 3px 3px 0 rgba(0,0,0,.45)" : "none"; elements.push(content);
  elements.filter((element)=>element.type==="text"||element.type==="button").forEach((element)=>{element.fontSizeDesign=element.fontSize;element.responsiveMaxTextSize=Math.max(element.responsiveMinTextSize,element.fontSize);element.textPadding={top:element.padding,right:element.padding,bottom:element.padding,left:element.padding};});
  return elements;
}
