import type { PresetCategory, SystemPreset } from "./types";

type Seed = [name: string, category: PresetCategory, shape: string, border: string, type: string, spacing: "compact"|"balanced"|"spacious", gradient: "off"|"subtle"|"active", depth: string, surface: string, accent: string, decoration: string, platforms: string[]];
const seeds: Seed[] = [
  ["Windows 95","OS","square","raised-bevel","compact-system","compact","off","hard-bevel","#c0c0c0","#000080","pixel-controls",["Desktop"]],
  ["Windows 98","OS","square","four-edge-bevel","compact-system","compact","off","hard-bevel","#c0c0c0","#000080","raised-controls",["Desktop"]],
  ["Windows ME","OS","square","soft-bevel","compact-system","compact","subtle","layered","#d4d0c8","#3a6ea5","small-icons",["Desktop"]],
  ["Windows 2000","OS","square","precision-bevel","compact-system","compact","off","recessed","#d4d0c8","#0a246a","dense-controls",["Desktop"]],
  ["Windows XP","OS","soft-rectangle","colored-edge","friendly-system","balanced","subtle","rounded-bevel","#ece9d8","#245edb","luna-tabs",["Desktop"]],
  ["Windows Vista","OS","glass-rectangle","glass-edge","humanist-sans","balanced","active","glass-depth","#202936","#55a7e9","aero-glow",["Desktop"]],
  ["Windows 7","OS","soft-rectangle","glass-edge","humanist-sans","balanced","subtle","glass-depth","#d9edf7","#2a75c5","aero-tabs",["Desktop"]],
  ["Classic Macintosh","OS","square","one-bit-double","chicago-system","compact","off","flat","#ffffff","#000000","striped-title",["Desktop"]],
  ["Mac OS 9","OS","soft-square","platinum-ridge","charcoal-system","compact","subtle","embossed","#dddddd","#3366cc","platinum-tabs",["Desktop"]],
  ["DOS","OS","square","single-line","mono-terminal","compact","off","flat","#000000","#aaaaaa","text-grid",["Desktop"]],
  ["BIOS","OS","square","double-line","mono-terminal","compact","off","flat","#0000aa","#ffffff","keyboard-hints",["Desktop"]],
  ["CRT Terminal","Technology","square","scanline-edge","mono-terminal","compact","off","screen-depth","#06130b","#55ff88","scanlines",["Desktop","Roblox"]],
  ["Green Terminal","Technology","square","phosphor-edge","mono-terminal","compact","off","screen-depth","#001107","#41ff75","phosphor",["Desktop","Roblox"]],
  ["Amber Terminal","Technology","square","phosphor-edge","mono-terminal","compact","off","screen-depth","#160e00","#ffb629","amber-glow",["Desktop"]],
  ["Early Internet","OS","square","html-rule","serif-web","compact","off","flat","#ffffff","#0000ee","link-underlines",["Web"]],
  ["GeoCities","OS","mixed","table-border","decorative-web","compact","active","flat","#05002e","#ffea00","stars-tiles",["Web"]],
  ["Webcore","OS","mixed","browser-chrome","pixel-sans","compact","subtle","recessed","#d6d6d6","#3056d3","toolbar-icons",["Web"]],
  ["Y2K Computer","OS","capsule","chrome-line","techno-sans","balanced","active","inflated","#d7e5ec","#4be6ff","orb-controls",["Web","Desktop"]],
  ["Frutiger Aero","OS","organic-round","glass-line","humanist-sans","spacious","active","glossy","#d9f4ff","#21a7df","nature-gloss",["Web","Desktop"]],
  ["Corporate 2000s","Professional","square","business-rule","humanist-sans","compact","subtle","flat","#eef1f5","#1f4e79","office-tabs",["Web","Desktop"]],
  ["Roblox Classic","Game","square","stud-outline","gotham-sans","compact","off","blocky","#2d2d2d","#e2231a","studs",["Roblox"]],
  ["Roblox Modern","Game","soft-rectangle","clean-line","gotham-sans","balanced","subtle","layered","#1b1d22","#00a2ff","clean-icons",["Roblox"]],
  ["Roblox Simulator","Game","chunky-round","thick-outline","display-sans","spacious","active","extruded","#3345a5","#ffcf33","badges",["Roblox"]],
  ["Roblox Tycoon","Game","panel-grid","industrial-line","display-sans","balanced","subtle","stacked","#1e3b2f","#38d66b","cash-panels",["Roblox"]],
  ["Roblox Horror","Dark","irregular-square","distressed-line","condensed-horror","compact","off","deep","#120d12","#bd1e3c","scratches",["Roblox"]],
  ["Arcade","Game","cabinet-angle","neon-outline","arcade-display","balanced","active","extruded","#171025","#ff3ed1","marquee",["Roblox","Desktop"]],
  ["Retro Arcade","Game","pixel-step","pixel-outline","pixel-display","compact","off","pixel-depth","#10082a","#ffcc33","pixel-corners",["Roblox","Desktop"]],
  ["Pixel RPG","Game","pixel-step","pixel-double","pixel-serif","compact","off","pixel-depth","#261b2c","#e6c87c","ornate-pixels",["Roblox"]],
  ["JRPG","Game","ornate-curve","ornate-line","elegant-serif","balanced","subtle","layered","#17233f","#72b7ff","corner-flourish",["Desktop","Roblox"]],
  ["MMORPG","Game","stone-ornate","metal-ridge","fantasy-serif","compact","subtle","carved","#2b241d","#d3a33b","runes",["Desktop","Roblox"]],
  ["Fighting Game","Game","sharp-slice","impact-outline","impact-sans","compact","active","explosive","#1d1016","#ff394d","slashes",["Desktop","Roblox"]],
  ["Racing Game","Game","speed-angle","thin-tech","condensed-sans","compact","active","layered","#10151d","#ff3b24","speed-lines",["Desktop","Roblox"]],
  ["Rhythm Game","Game","pulse-round","luminous-line","geometric-sans","balanced","active","floating","#170d2b","#b964ff","beat-bars",["Desktop","Roblox"]],
  ["Platformer","Game","chunky-round","cartoon-outline","friendly-display","spacious","subtle","popped","#2e77b6","#ffd23f","platform-tabs",["Roblox"]],
  ["Survival","Game","utility-square","worn-line","condensed-sans","compact","off","rugged","#20251e","#c6a15b","wear-marks",["Desktop","Roblox"]],
  ["Boss Fight","Game","wide-bracket","heavy-outline","impact-sans","compact","subtle","dramatic","#220b12","#e52b45","boss-brackets",["Desktop","Roblox"]],
  ["Tower Defense","Game","tile-panel","map-line","clean-sans","compact","subtle","stacked","#183a35","#f0c44f","grid-markers",["Roblox"]],
  ["Strategy","Game","command-grid","thin-rule","clean-sans","compact","off","layered","#19242d","#4ea3c8","data-dividers",["Desktop","Roblox"]],
  ["Inventory RPG","Game","slot-grid","ornate-ridge","fantasy-serif","compact","off","carved","#2b2119","#d6a95c","slot-insets",["Desktop","Roblox"]],
  ["Visual Novel UI","Game","dialogue-panel","soft-line","readable-serif","spacious","subtle","overlay","#f5eef4","#b64c83","speaker-tag",["Desktop","Mobile"]],
  ["VHS","Retro","screen-square","tape-edge","mono-display","compact","off","screen-depth","#15121b","#ea4ba7","tracking-noise",["Desktop"]],
  ["Analog Broadcast","Media","broadcast-safe","signal-line","broadcast-sans","compact","off","layered","#20202a","#ff394d","safe-area",["Desktop"]],
  ["80s Television","Media","tube-round","chrome-ridge","display-sans","balanced","active","tube-depth","#21192c","#ff4fd8","scan-glow",["Desktop"]],
  ["90s Television","Media","tube-square","plastic-bevel","broadcast-sans","compact","subtle","tube-depth","#30313a","#25b8ef","lower-thirds",["Desktop"]],
  ["2000s Television","Media","wide-panel","glass-rule","broadcast-sans","balanced","active","glossy","#173052","#f7941d","ticker-bars",["Desktop"]],
  ["Game Show","Media","marquee-arch","bulb-border","show-display","spacious","active","stage-depth","#31124f","#ffd43b","light-bulbs",["Desktop","Roblox"]],
  ["News Broadcast","Media","lower-third","broadcast-rule","broadcast-sans","compact","active","layered","#10233d","#db2335","ticker",["Desktop"]],
  ["CRT Monitor","Technology","bezel-round","screen-inset","mono-terminal","compact","off","deep-bezel","#252722","#85d696","vent-lines",["Desktop","Roblox"]],
  ["Security Camera","Media","monitor-grid","thin-monitor","mono-sans","compact","off","screen-depth","#11151a","#d8e4e8","timestamp",["Desktop"]],
  ["Public Access TV","Media","mixed-card","video-rule","display-sans","balanced","active","flat","#27173b","#ffeb3b","crawl-text",["Desktop"]],
  ["Cyberpunk","Technology","chamfered","neon-tech","condensed-tech","compact","active","layered","#10151d","#f4e839","circuit-notches",["Desktop","Roblox"]],
  ["Sci-Fi","Technology","angular-panel","thin-tech","geometric-sans","balanced","subtle","floating","#0e1a26","#55c7ff","corner-glyphs",["Desktop","Roblox"]],
  ["Holographic","Technology","chamfered","emissive-line","geometric-sans","balanced","active","floating","#0a1724","#55e8ff","light-ticks",["Desktop","Roblox"]],
  ["Neon","Technology","rounded-tube","neon-tube","display-sans","spacious","active","glowing","#100b1f","#ff3bd4","tube-glow",["Desktop"]],
  ["Digital System","Technology","data-grid","thin-rule","mono-sans","compact","subtle","layered","#111821","#31aeea","data-ticks",["Desktop","Web"]],
  ["Computer Virus","Dark","corrupted-grid","broken-line","mono-terminal","compact","off","unstable","#080d08","#63ff56","corrupt-glyphs",["Desktop"]],
  ["Glitch","Dark","offset-block","split-line","mono-display","compact","off","offset","#130f1c","#ff2d75","rgb-splits",["Desktop","Roblox"]],
  ["Hacker Terminal","Technology","terminal-grid","single-line","mono-terminal","compact","off","screen-depth","#020806","#27ff6e","cursor-block",["Desktop"]],
  ["Circuit Board","Technology","trace-panel","trace-line","mono-sans","compact","off","etched","#09231b","#68d68e","circuit-traces",["Desktop"]],
  ["AI System","Technology","modular-round","luminous-rule","geometric-sans","balanced","active","floating","#11172c","#8a7cff","node-links",["Desktop","Web"]],
  ["Security System","Technology","secure-grid","warning-line","condensed-sans","compact","off","recessed","#182028","#f4b942","lock-markers",["Desktop"]],
  ["Surveillance","Technology","monitor-grid","camera-rule","mono-sans","compact","off","screen-depth","#101417","#8ce0c0","camera-labels",["Desktop"]],
  ["Industrial Computer","Technology","bolted-panel","heavy-ridge","industrial-sans","compact","off","recessed","#343b3c","#f0a629","rivets",["Desktop","Roblox"]],
  ["Futuristic HUD","Technology","bracket-panel","hairline","condensed-tech","compact","subtle","floating","#0b1820","#35d4ff","hud-brackets",["Desktop","Roblox"]],
  ["Hologram HUD","Technology","floating-bracket","emissive-line","condensed-tech","balanced","active","multi-depth","#07141c","#47ecff","depth-ticks",["Desktop","Roblox"]],
  ["Forest","Environment","organic-panel","wood-line","humanist-sans","balanced","off","carved","#193124","#7fc75b","leaf-corners",["Roblox","Mobile"]],
  ["Jungle","Environment","vine-panel","woven-line","display-sans","balanced","subtle","layered","#153427","#c9dd52","vine-wrap",["Roblox"]],
  ["Desert","Environment","sandstone-panel","etched-line","serif-display","spacious","subtle","carved","#8a5a32","#f2c36b","sand-notches",["Roblox"]],
  ["Arctic","Environment","ice-facet","frost-line","geometric-sans","spacious","active","crystalline","#dceff7","#58b8df","ice-chips",["Roblox"]],
  ["Ocean","Environment","wave-round","water-line","humanist-sans","spacious","active","layered","#103d61","#3bd6c6","wave-tabs",["Roblox","Mobile"]],
  ["Underwater","Environment","porthole","pressure-ridge","rounded-sans","balanced","active","deep","#082b3a","#57d8d3","bubbles",["Roblox"]],
  ["Volcano","Environment","cracked-panel","lava-line","impact-sans","compact","active","deep","#2a0d08","#ff5a24","cracks",["Roblox"]],
  ["Space","Environment","orbital-panel","thin-tech","geometric-sans","balanced","subtle","floating","#090d1a","#86a8ff","star-ticks",["Desktop","Roblox"]],
  ["Galaxy","Environment","nebula-curve","luminous-line","elegant-sans","spacious","active","floating","#160d2a","#c86cff","starfield",["Desktop"]],
  ["Cave","Environment","rock-panel","rough-line","display-serif","compact","off","carved","#29241e","#d8a85c","rock-chips",["Roblox"]],
  ["Factory","Environment","machine-panel","bolted-line","industrial-sans","compact","off","recessed","#34393a","#f3b02e","bolts",["Roblox"]],
  ["Office","Professional","clean-panel","business-rule","humanist-sans","balanced","off","flat","#eef1f4","#2c70b7","section-tabs",["Web","Desktop"]],
  ["School","Environment","notebook-panel","pencil-line","friendly-sans","spacious","off","flat","#f4f0df","#2b6cb0","ruled-lines",["Web","Mobile"]],
  ["Mall","Environment","sign-panel","chrome-line","display-sans","spacious","active","glossy","#f0e8f2","#d4388a","wayfinding",["Desktop"]],
  ["Laboratory","Environment","instrument-panel","precision-rule","mono-sans","compact","off","recessed","#e7eef0","#15a39a","measurement-ticks",["Desktop"]],
  ["Egyptian","Historical","monument-panel","gold-ridge","carved-serif","spacious","off","carved","#5f4022","#d4ad4f","glyph-band",["Roblox"]],
  ["Ancient Stone","Historical","stone-slab","chiseled-line","carved-serif","spacious","off","carved","#57534b","#c6ad7a","cracks",["Roblox"]],
  ["Medieval","Historical","shield-panel","iron-ridge","blackletter-serif","balanced","off","forged","#352d27","#b79454","studs",["Roblox"]],
  ["Castle","Historical","arch-panel","stone-ridge","carved-serif","spacious","off","carved","#4e5050","#c3a35a","battlements",["Roblox"]],
  ["Fantasy RPG","Historical","ornate-panel","gold-ridge","fantasy-serif","balanced","subtle","layered","#2b2136","#d5af58","runes",["Desktop","Roblox"]],
  ["Magical","Historical","crystal-curve","luminous-line","elegant-serif","spacious","active","floating","#27184b","#a879ff","spark-glyphs",["Desktop","Roblox"]],
  ["Steampunk","Historical","brass-panel","riveted-ridge","industrial-serif","compact","subtle","machined","#3b2a21","#c58a3a","gears",["Desktop","Roblox"]],
  ["Cartoon","Art","chunky-round","ink-outline","cartoon-sans","spacious","subtle","popped","#4d8dde","#ffd738","bounce-marks",["Web","Roblox"]],
  ["Comic","Art","angled-panel","ink-outline","comic-display","compact","off","popped","#f5e6bf","#e63946","halftone",["Web"]],
  ["Doodle","Art","hand-panel","scribble-line","handwritten","spacious","off","flat","#faf6e8","#315b96","sketch-marks",["Web"]],
  ["Paper","Art","sheet-panel","paper-edge","readable-serif","spacious","off","stacked","#f3ead2","#9a463d","paper-tabs",["Web","Mobile"]],
  ["Notebook","Art","ruled-panel","ink-line","handwritten","spacious","off","flat","#fffaf0","#356aa0","margin-rule",["Web","Mobile"]],
  ["Graffiti","Art","spray-panel","paint-outline","street-display","compact","active","layered","#1b1820","#ff4aa2","spray-marks",["Desktop"]],
  ["Brutalist","Art","raw-block","heavy-rule","grotesk-sans","compact","off","flat","#e8e5dc","#ff3b18","offset-labels",["Web"]],
  ["Glass","Art","glass-round","glass-line","clean-sans","spacious","active","floating","#182236","#8dd8ff","glass-highlight",["Web","Desktop"]],
  ["Chrome","Art","metal-curve","chrome-ridge","display-sans","balanced","active","inflated","#868d99","#ecf4ff","specular-lines",["Desktop"]],
  ["Metallic","Art","machined-panel","metal-ridge","industrial-sans","compact","subtle","machined","#434b52","#c2d0d8","screws",["Desktop","Roblox"]],
  ["Liminal","Dark","empty-frame","thin-rule","plain-sans","spacious","off","flat","#d8d2bd","#8093a3","misaligned-labels",["Desktop"]],
  ["Weirdcore","Dark","asymmetric-panel","mixed-line","mixed-display","balanced","active","offset","#20162b","#85ffb4","odd-symbols",["Desktop"]],
  ["Dreamcore","Dark","soft-portal","soft-line","serif-display","spacious","active","floating","#a7b7d8","#ffd6f2","haze-labels",["Desktop"]],
  ["Roblox 2012-style","Game","square","classic-outline","gotham-sans","compact","off","blocky","#343a40","#00a2ff","legacy-tabs",["Roblox"]],
  ["Roblox RPG","Game","slot-grid","ornate-ridge","fantasy-serif","compact","off","carved","#2a2032","#d6a95c","quest-tabs",["Roblox"]],
  ["Roblox Arcade","Game","pixel-step","neon-outline","pixel-display","compact","active","pixel-depth","#130c28","#38e8ff","score-lights",["Roblox"]],
  ["Roblox Cartoony","Game","chunky-round","cartoon-outline","friendly-display","spacious","active","popped","#3d8ee8","#ffcf33","icon-tabs",["Roblox"]],
  ["Roblox Shop","Game","chunky-round","double-outline","display-sans","spacious","active","extruded","#f7f8ff","#21d6bf","product-grid",["Roblox"]],
  ["Roblox Premium Shop","Game","angled-panel","gold-ridge","display-sans","balanced","subtle","layered","#08090d","#f4bd36","premium-cards",["Roblox"]],
  ["Roblox Inventory","Game","slot-grid","thick-outline","display-sans","balanced","subtle","stacked","#253c88","#6ad8ff","inventory-slots",["Roblox"]],
  ["Roblox Character Select","Game","wide-panel","thick-outline","display-sans","spacious","active","layered","#222d4d","#7eeb76","character-cards",["Roblox"]],
  ["Roblox Killer Select","Dark","sharp-slice","distressed-line","condensed-horror","balanced","off","dramatic","#140b10","#e52b45","killer-cards",["Roblox"]],
  ["Roblox HUD","Game","bracket-panel","clean-line","gotham-sans","compact","subtle","floating","#172030","#38bdf8","hud-modules",["Roblox"]],
  ["Roblox Boss HUD","Game","wide-bracket","heavy-outline","impact-sans","compact","subtle","dramatic","#210b10","#ef334d","boss-health",["Roblox"]],
  ["Roblox Dialogue","Game","soft-rectangle","thick-outline","friendly-display","balanced","subtle","popped","#232748","#ffd85a","speaker-panel",["Roblox"]],
  ["Roblox Game Show","Media","marquee-arch","bulb-border","show-display","spacious","active","stage-depth","#30104f","#ffd43b","answer-grid",["Roblox"]],
  ["Roblox Retro","Game","pixel-step","pixel-double","pixel-display","compact","off","pixel-depth","#13092d","#ffcc33","pixel-tabs",["Roblox"]],
  ["Roblox Windows 98","OS","square","four-edge-bevel","compact-system","compact","off","hard-bevel","#c0c0c0","#000080","roblox-desktop",["Roblox"]],
  ["Roblox Cyberpunk","Technology","chamfered","neon-tech","condensed-tech","compact","active","layered","#0d121c","#f4e839","game-circuit-tabs",["Roblox"]],
  ["Roblox Sci-Fi","Technology","angular-panel","thin-tech","geometric-sans","balanced","subtle","floating","#0b1724","#55c7ff","game-corner-glyphs",["Roblox"]],
];

const fonts: Record<string,string> = { "mono-terminal":"Courier New", "pixel-display":"Courier New", "pixel-serif":"Georgia", "elegant-serif":"Georgia", "fantasy-serif":"Georgia", "readable-serif":"Georgia", "carved-serif":"Georgia", "blackletter-serif":"Georgia", "serif-display":"Georgia", "handwritten":"Trebuchet MS", "impact-sans":"Impact", "arcade-display":"Impact", "show-display":"Impact", "comic-display":"Impact", "street-display":"Impact", "condensed-horror":"Impact" };
const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const makePreset = (seed: Seed): SystemPreset => { const [name,category,shape,border,type,spacing,gradient,depth,surface,accent,decoration,platforms] = seed; const compact = spacing === "compact", spacious = spacing === "spacious"; const hard = /(bevel|ridge|outline|double|heavy|bolted|chiseled)/.test(border); const luminous = /(neon|emissive|luminous|phosphor)/.test(border); return {
  id: slug(name), name, category, description: `${shape} geometry with ${border} construction, ${type} typography, and ${decoration}.`,
  geometry: { shape, cornerStyle: shape.includes("round") || shape.includes("curve") ? "rounded" : shape.includes("chamfer") || shape.includes("angle") ? "chamfered" : "square", radius: shape.includes("round") ? 18 : shape.includes("soft") ? 7 : 0, density: spacing, borderLayers: hard ? 3 : luminous ? 2 : 1 },
  colors: { surface, surfaceAlt: category === "OS" && surface === "#c0c0c0" ? "#ffffff" : surface, accent, text: /^#(d|e|f)/i.test(surface) ? "#111318" : "#f4f7fb", highlight: luminous ? accent : "#ffffff", shadow: "#111318", strategy: category === "Environment" ? "material-derived" : category === "Historical" ? "artifact-derived" : "system-constrained" },
  typography: { family: fonts[type] ?? "Inter", character: type, weight: type.includes("display") ? 700 : 600, alignment: type.includes("display") ? "center" : "left", scale: compact ? "compact" : spacious ? "display" : "standard" },
  spacing: { unit: compact ? 4 : spacious ? 10 : 6, padding: compact ? 8 : spacious ? 18 : 12, gap: compact ? 6 : spacious ? 14 : 10 },
  borders: { construction: border, width: hard ? 3 : luminous ? 2 : 1, highlightSide: "top-left", shadowSide: "bottom-right" },
  gradients: { default: gradient, type: gradient === "off" ? "none" : luminous ? "linear" : "radial", angle: luminous ? 145 : 180 },
  effects: { shadow: hard ? "3px 3px 0 rgba(0,0,0,.65)" : luminous ? `0 0 28px ${accent}55` : depth === "flat" ? "none" : "0 10px 28px rgba(0,0,0,.35)", blur: depth === "glass-depth" || depth === "floating" ? 8 : 0, glow: luminous ? 70 : 0, decoration },
  depth: { mode: depth, amount: depth === "flat" ? 0 : hard ? 3 : 10, perspective: depth.includes("floating") || depth.includes("multi") ? 850 : 1000 },
  button: { shape: shape.includes("round") ? "rounded" : "rectangular", construction: hard ? "raised-resting" : luminous ? "emissive-stroke" : "surface-and-rule", pressed: hard ? "reverse-bevel" : "translate-1px" },
  window: { construction: `${shape}-${border}`, titleBar: compact ? "compact-horizontal" : decoration.includes("marquee") ? "display-marquee" : "integrated-header", contentInset: hard ? 4 : compact ? 6 : 12 },
  spatial: { enabled: depth.includes("floating") || depth.includes("multi"), tilt: depth.includes("multi") ? 12 : depth.includes("floating") ? 5 : 0, layers: depth.includes("multi") ? 3 : depth === "flat" ? 1 : 2 }, platforms,
  aiRules: { prefer: [shape,border,type,decoration], avoid: gradient === "off" ? ["automatic gradients","soft SaaS shadow","large generic radius"] : ["generic SaaS card","unrelated visual metaphors"] },
}; };

export const SYSTEM_PRESETS = seeds.map(makePreset);
export const PRESET_BY_ID = Object.fromEntries(SYSTEM_PRESETS.map((preset) => [preset.id,preset]));
export function searchPresets(query: string) { const value = query.trim().toLowerCase(); return SYSTEM_PRESETS.filter((preset) => !value || `${preset.name} ${preset.category} ${preset.description} ${preset.aiRules.prefer.join(" ")}`.toLowerCase().includes(value)); }
export function matchPresets(text: string) { const value = text.toLowerCase(); return SYSTEM_PRESETS.filter((preset) => value.includes(preset.name.toLowerCase()) || preset.name.toLowerCase().split(/\s+/).every((part) => value.includes(part))).slice(0,4); }
