import { createElement } from "../editor/project.ts";
import type { EditorElement, EditorProject, ElementType } from "@/lib/editor/types";
import { PRESET_BY_ID } from "../design-intelligence/system-presets.ts";
import { validateAIProject } from "./validator.ts";
import { findTool, validateToolArguments } from "./tool-registry.ts";

type ToolState={project:EditorProject;operations:string[];createdIds:string[]};
const assertRecord=(value:unknown):Record<string,unknown>=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Tool arguments must be an object.");return value as Record<string,unknown>;};
const idsFrom=(value:unknown)=>{if(!Array.isArray(value)||!value.every((id)=>typeof id==="string"))throw new Error("ids must be a string array.");return value as string[];};
const elementById=(state:ToolState,id:string)=>{const element=state.project.elements.find((item)=>item.id===id);if(!element)throw new Error(`Unknown element ${id}.`);return element;};
const result=(message:string,ids:string[]=[])=>({success:true,message,ids});
const setNullable=<K extends keyof EditorElement>(element:EditorElement,args:Record<string,unknown>,key:K)=>{const value=args[key as string];if(value!==null&&value!==undefined)(element[key] as unknown)=value;};

function descendants(project:EditorProject,roots:string[]){const ids=new Set(roots);let changed=true;while(changed){changed=false;project.elements.forEach((item)=>{if(item.parentId&&ids.has(item.parentId)&&!ids.has(item.id)){ids.add(item.id);changed=true;}});}return ids;}
function applyPreset(element:EditorElement,presetId:string){const preset=PRESET_BY_ID[presetId];if(!preset)throw new Error(`Unknown CreatorMake preset ${presetId}.`);element.fill=element.type==="text"?"transparent":preset.colors.surface;element.borderColor=preset.colors.accent;element.borderWidth=preset.borders.width;element.cornerRadius=preset.geometry.radius;element.corners={tl:preset.geometry.radius,tr:preset.geometry.radius,br:preset.geometry.radius,bl:preset.geometry.radius};element.textColor=preset.colors.text;element.fontWeight=preset.typography.weight;element.padding=preset.spacing.padding;element.gap=preset.spacing.gap;element.shadow=preset.effects.shadow;element.gradientType=preset.gradients.default==="off"?"none":preset.gradients.type;element.gradientAngle=preset.gradients.angle;}

export function createToolState(project:EditorProject):ToolState{return {project:structuredClone(project),operations:[],createdIds:[]};}
export function executeCreatorMakeTool(state:ToolState,name:string,rawArguments:unknown){const tool=findTool(name);if(!tool)throw new Error(`Tool ${name} is not registered.`);const args=validateToolArguments(tool,assertRecord(rawArguments));let output:{success:boolean;message:string;ids:string[]};
  if(name==="inspection_inspect_document")output=result(`Canvas ${state.project.screen.width}×${state.project.screen.height}; ${state.project.elements.length} editable elements.`,state.project.elements.map((item)=>item.id));
  else if(name==="inspection_inspect_selection"){const ids=descendants(state.project,state.project.selectedIds);output=result(`${ids.size} selected or descendant elements inspected.`,[...ids]);}
  else if(name==="create_element"){
    const type=String(args.type) as ElementType,element=createElement(type,state.project.elements.length);Object.assign(element,{name:String(args.name),parentId:args.parentId as string|null,x:Number(args.x),y:Number(args.y),width:Number(args.width),height:Number(args.height),text:args.text===null?"":String(args.text),fill:String(args.fill),borderColor:String(args.borderColor),borderWidth:Number(args.borderWidth),cornerRadius:Number(args.cornerRadius),corners:{tl:Number(args.cornerRadius),tr:Number(args.cornerRadius),br:Number(args.cornerRadius),bl:Number(args.cornerRadius)},fontSize:Number(args.fontSize),fontWeight:Number(args.fontWeight),textColor:String(args.textColor),textAlign:args.textAlign});if(element.parentId)elementById(state,element.parentId);state.project.elements.push(element);state.createdIds.push(element.id);output=result(`Created ${element.type} ${element.name}.`,[element.id]);
  }else if(name==="create_grid"){
    const parent=createElement("frame",state.project.elements.length);Object.assign(parent,{name:String(args.name),parentId:args.parentId as string|null,x:Number(args.x),y:Number(args.y),width:Number(args.width),height:Number(args.height),layoutMode:"grid",gridColumns:Number(args.columns),gap:Number(args.gap),rowGap:Number(args.gap),columnGap:Number(args.gap),padding:Number(args.gap),fill:"transparent",borderColor:"transparent",borderWidth:0});if(parent.parentId)elementById(state,parent.parentId);state.project.elements.push(parent);const count=Number(args.count),columns=Math.max(1,Number(args.columns)),gap=Number(args.gap),rows=Math.ceil(count/columns),cellWidth=(parent.width-gap*(columns-1))/columns,cellHeight=(parent.height-gap*(rows-1))/rows,ids=[parent.id];for(let index=0;index<count;index++){const child=createElement(String(args.childType) as ElementType,state.project.elements.length);Object.assign(child,{name:`${String(args.labelPrefix)}${String(index+1).padStart(2,"0")}`,parentId:parent.id,x:parent.x+(index%columns)*(cellWidth+gap),y:parent.y+Math.floor(index/columns)*(cellHeight+gap),width:cellWidth,height:cellHeight,fill:String(args.fill)});state.project.elements.push(child);ids.push(child.id);}state.createdIds.push(...ids);output=result(`Created ${count}-item deterministic grid ${parent.name}.`,ids);
  }else if(name==="transform_update_elements"){
    const ids=idsFrom(args.ids);ids.forEach((id)=>{const item=elementById(state,id);(["x","y","width","height","rotation","skewX","skewY","rotateX","rotateY","perspective"] as const).forEach((key)=>setNullable(item,args,key));item.width=Math.max(1,item.width);item.height=Math.max(1,item.height);});output=result(`Updated geometry for ${ids.length} element(s).`,ids);
  }else if(name==="style_update_elements"){
    const ids=idsFrom(args.ids);ids.forEach((id)=>{const item=elementById(state,id);(["fill","borderColor","borderWidth","cornerRadius","opacity","shadow","gradientType","gradientAngle"] as const).forEach((key)=>setNullable(item,args,key));if(args.cornerRadius!==null)item.corners={tl:item.cornerRadius,tr:item.cornerRadius,br:item.cornerRadius,bl:item.cornerRadius};});output=result(`Updated style for ${ids.length} element(s).`,ids);
  }else if(name==="text_update"){
    const ids=idsFrom(args.ids);ids.forEach((id)=>{const item=elementById(state,id);if(item.type!=="text"&&item.type!=="button")throw new Error(`${item.name} is not text-editable.`);if(args.content!==null)item.text=String(args.content);if(args.fontFamily!==null)item.fontFamily=String(args.fontFamily);if(args.fontSize!==null)item.fontSize=Number(args.fontSize);if(args.fontWeight!==null)item.fontWeight=Number(args.fontWeight);if(args.color!==null)item.textColor=String(args.color);if(args.alignment!==null)item.textAlign=args.alignment as EditorElement["textAlign"];if(args.autoFit!==null)item.autoFit=Boolean(args.autoFit);});output=result(`Updated text properties for ${ids.length} element(s).`,ids);
  }else if(name==="layout_set_auto_layout"){
    const item=elementById(state,String(args.id));item.layoutMode=args.mode as EditorElement["layoutMode"];item.gap=Number(args.gap);item.rowGap=Number(args.gap);item.columnGap=Number(args.gap);item.padding=Number(args.padding);item.layoutPadding={top:item.padding,right:item.padding,bottom:item.padding,left:item.padding};item.gridColumns=Number(args.columns);item.layoutWrap=Boolean(args.wrap);output=result(`Configured ${item.layoutMode} layout on ${item.name}.`,[item.id]);
  }else if(name==="hierarchy_reparent"){
    const item=elementById(state,String(args.id)),parentId=args.parentId as string|null;if(parentId){elementById(state,parentId);if(descendants(state.project,[item.id]).has(parentId))throw new Error("Reparent would create a hierarchy cycle.");}item.parentId=parentId;output=result(`Reparented ${item.name}.`,[item.id]);
  }else if(name==="system_apply_preset"){
    const roots=idsFrom(args.ids),ids=Boolean(args.recursive)?[...descendants(state.project,roots)]:roots,presetId=String(args.presetId);ids.forEach((id)=>applyPreset(elementById(state,id),presetId));output=result(`Applied ${PRESET_BY_ID[presetId]?.name??presetId} visual recipes without changing content.`,ids);
  }else if(name==="validation_run"){
    const validation=validateAIProject(state.project);output=result(validation.passed?"Deterministic validation passed.":`Validation found ${validation.issues.length} issue(s).`,validation.issues.map((issue)=>issue.elementId).filter((id):id is string=>Boolean(id)));
  }else throw new Error(`Tool ${name} has no executor.`);
  state.operations.push(`${tool.id}: ${output.message}`);return output;
}
export type { ToolState };
