type JsonSchema=Record<string,unknown>;
export type CreatorMakeTool={id:string;category:string;name:string;description:string;parameters:JsonSchema;outputSchema:JsonSchema};
const successSchema={type:"object",additionalProperties:false,properties:{success:{type:"boolean"},message:{type:"string"},ids:{type:"array",items:{type:"string"}}},required:["success","message","ids"]};
const nullableNumber={type:["number","null"]};const nullableString={type:["string","null"]};
export const CREATORMAKE_TOOLS:CreatorMakeTool[]=[
  {id:"inspection.inspectDocument",category:"inspection",name:"inspection_inspect_document",description:"Inspect the compact CreatorMake document, canvas bounds, editable hierarchy, and current element count before deciding what to create. This tool does not mutate the project.",parameters:{type:"object",additionalProperties:false,properties:{},required:[]},outputSchema:successSchema},
  {id:"inspection.inspectSelection",category:"inspection",name:"inspection_inspect_selection",description:"Inspect selected editable objects and their descendants. Use before REFINE, RESTYLE, FIX, or MODIFY so unrelated objects and existing text remain unchanged.",parameters:{type:"object",additionalProperties:false,properties:{},required:[]},outputSchema:successSchema},
  {id:"create.element",category:"create",name:"create_element",description:"Create one editable CreatorMake element. Use frames, containers, or scrolling-frame for panels, text only for literal UI copy, and buttons for interactive controls. Geometry is in CreatorMake canvas coordinates. Returns the generated stable element ID.",parameters:{type:"object",additionalProperties:false,properties:{type:{type:"string",enum:["frame","container","scrolling-frame","text","rectangle","roundRect","ellipse","line","polygon","star","button"]},name:{type:"string"},parentId:nullableString,x:{type:"number"},y:{type:"number"},width:{type:"number",minimum:1},height:{type:"number",minimum:1},text:nullableString,fill:{type:"string"},borderColor:{type:"string"},borderWidth:{type:"number",minimum:0},cornerRadius:{type:"number",minimum:0},fontSize:{type:"number",minimum:6},fontWeight:{type:"integer",minimum:100,maximum:900},textColor:{type:"string"},textAlign:{type:"string",enum:["left","center","right"]}},required:["type","name","parentId","x","y","width","height","text","fill","borderColor","borderWidth","cornerRadius","fontSize","fontWeight","textColor","textAlign"]},outputSchema:successSchema},
  {id:"create.grid",category:"create",name:"create_grid",description:"Create an editable grid parent plus repeated editable children using deterministic equal cell geometry. Use for inventories, product cards, selectors, and repeated controls instead of issuing one call per identical item.",parameters:{type:"object",additionalProperties:false,properties:{name:{type:"string"},parentId:nullableString,x:{type:"number"},y:{type:"number"},width:{type:"number",minimum:1},height:{type:"number",minimum:1},count:{type:"integer",minimum:1,maximum:100},columns:{type:"integer",minimum:1,maximum:20},gap:{type:"number",minimum:0},childType:{type:"string",enum:["frame","container","rectangle","roundRect","ellipse","button"]},labelPrefix:{type:"string"},fill:{type:"string"}},required:["name","parentId","x","y","width","height","count","columns","gap","childType","labelPrefix","fill"]},outputSchema:successSchema},
  {id:"transform.update",category:"transform",name:"transform_update_elements",description:"Move, resize, rotate, skew, or apply perspective to existing editable elements. Pass null for every property that must remain unchanged; this preserves unrelated geometry.",parameters:{type:"object",additionalProperties:false,properties:{ids:{type:"array",items:{type:"string"},minItems:1},x:nullableNumber,y:nullableNumber,width:nullableNumber,height:nullableNumber,rotation:nullableNumber,skewX:nullableNumber,skewY:nullableNumber,rotateX:nullableNumber,rotateY:nullableNumber,perspective:nullableNumber},required:["ids","x","y","width","height","rotation","skewX","skewY","rotateX","rotateY","perspective"]},outputSchema:successSchema},
  {id:"style.update",category:"style",name:"style_update_elements",description:"Change visual styling on existing editable objects without replacing their content or hierarchy. Pass null for fields that should be preserved.",parameters:{type:"object",additionalProperties:false,properties:{ids:{type:"array",items:{type:"string"},minItems:1},fill:nullableString,borderColor:nullableString,borderWidth:nullableNumber,cornerRadius:nullableNumber,opacity:nullableNumber,shadow:nullableString,gradientType:{type:["string","null"],enum:["none","linear","radial","conic","diamond","four-corner","freeform",null]},gradientAngle:nullableNumber},required:["ids","fill","borderColor","borderWidth","cornerRadius","opacity","shadow","gradientType","gradientAngle"]},outputSchema:successSchema},
  {id:"text.update",category:"text",name:"text_update",description:"Update text properties on existing Text or Button elements. Only set content from the approved literalUICopy; never place instructional prompt language into the canvas.",parameters:{type:"object",additionalProperties:false,properties:{ids:{type:"array",items:{type:"string"},minItems:1},content:nullableString,fontFamily:nullableString,fontSize:nullableNumber,fontWeight:nullableNumber,color:nullableString,alignment:{type:["string","null"],enum:["left","center","right",null]},autoFit:{type:["boolean","null"]}},required:["ids","content","fontFamily","fontSize","fontWeight","color","alignment","autoFit"]},outputSchema:successSchema},
  {id:"layout.autoLayout",category:"layout",name:"layout_set_auto_layout",description:"Configure deterministic horizontal, vertical, or grid Auto Layout on an existing parent. The CreatorMake layout engine calculates exact child geometry after the transaction commits.",parameters:{type:"object",additionalProperties:false,properties:{id:{type:"string"},mode:{type:"string",enum:["none","horizontal","vertical","grid"]},gap:{type:"number",minimum:0},padding:{type:"number",minimum:0},columns:{type:"integer",minimum:1,maximum:20},wrap:{type:"boolean"}},required:["id","mode","gap","padding","columns","wrap"]},outputSchema:successSchema},
  {id:"hierarchy.reparent",category:"hierarchy",name:"hierarchy_reparent",description:"Reparent one existing editable element while preserving its stable ID and all properties. Parent may be null for a canvas root.",parameters:{type:"object",additionalProperties:false,properties:{id:{type:"string"},parentId:nullableString},required:["id","parentId"]},outputSchema:successSchema},
  {id:"system.applyPreset",category:"system",name:"system_apply_preset",description:"Apply only the visual recipes of a named CreatorMake System Preset to existing targets. This changes HOW objects look and never substitutes a preset example or changes visible copy.",parameters:{type:"object",additionalProperties:false,properties:{ids:{type:"array",items:{type:"string"},minItems:1},presetId:{type:"string"},recursive:{type:"boolean"}},required:["ids","presetId","recursive"]},outputSchema:successSchema},
  {id:"validation.run",category:"validation",name:"validation_run",description:"Run deterministic hierarchy, dimensions, containment, text-fit, and prompt-count checks against the current transaction. Use before finishing.",parameters:{type:"object",additionalProperties:false,properties:{},required:[]},outputSchema:successSchema},
];

export function toolsForTask(action:string,platform:string){const categories=new Set(["inspection","create","transform","style","text","layout","hierarchy","system","validation"]);if(action==="MODIFY")categories.delete("system");if(platform==="ROBLOX")categories.add("layout");return CREATORMAKE_TOOLS.filter((tool)=>categories.has(tool.category));}
export function toOpenAITool(tool:CreatorMakeTool){return {type:"function",name:tool.name,description:tool.description,parameters:tool.parameters,strict:true};}
export function findTool(name:string){return CREATORMAKE_TOOLS.find((tool)=>tool.name===name);}
export function validateToolArguments(tool:CreatorMakeTool,value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))throw new Error(`${tool.id} arguments must be an object.`);const input=value as Record<string,unknown>,schema=tool.parameters as {properties?:Record<string,Record<string,unknown>>;required?:string[];additionalProperties?:boolean};for(const key of schema.required??[]){if(!(key in input))throw new Error(`${tool.id} is missing required field ${key}.`);}if(schema.additionalProperties===false)for(const key of Object.keys(input)){if(!schema.properties?.[key])throw new Error(`${tool.id} received unknown field ${key}.`);}for(const [key,property] of Object.entries(schema.properties??{})){const candidate=input[key];if(candidate===null){const types=Array.isArray(property.type)?property.type:[property.type];if(!types.includes("null"))throw new Error(`${tool.id}.${key} cannot be null.`);continue;}const types=Array.isArray(property.type)?property.type:[property.type];const actual=Array.isArray(candidate)?"array":Number.isInteger(candidate)&&types.includes("integer")?"integer":typeof candidate;if(!types.includes(actual))throw new Error(`${tool.id}.${key} must be ${types.join(" or ")}.`);if(Array.isArray(property.enum)&&!property.enum.includes(candidate))throw new Error(`${tool.id}.${key} is not an allowed value.`);if(typeof candidate==="number"&&typeof property.minimum==="number"&&candidate<property.minimum)throw new Error(`${tool.id}.${key} is below its minimum.`);if(Array.isArray(candidate)&&typeof property.minItems==="number"&&candidate.length<property.minItems)throw new Error(`${tool.id}.${key} needs at least ${property.minItems} item(s).`);if(Array.isArray(candidate)&&property.items&&typeof property.items==="object"){const itemType=(property.items as {type?:string}).type;if(itemType&&candidate.some((item)=>typeof item!==itemType))throw new Error(`${tool.id}.${key} contains an invalid item.`);}}return input;}
