import { getRobloxFontCompatibility } from "./fonts.ts";
import { geometryKindForElement } from "../editor/geometry.ts";
import { classifyRobloxElement, classifyRobloxElements, classifyTextExport, hasVisibleTextBackground } from "./classification.ts";
import { planPixelAccurateAssets } from "./render-assets.ts";
import type { EditorElement, EditorProject } from "../editor/types.ts";
import type { RobloxCompatibilityIssue, RobloxExportOptions, RobloxImageManifestEntry, RobloxManifest, RobloxManifestNode, RobloxPropertyValue, RobloxRenderAsset } from "./types.ts";

const round=(value:number,places=4)=>Number(value.toFixed(places));
const quote=(value:string)=>JSON.stringify(value.replace(/\r\n/g,"\n"));
const varName=(value:string,index:number)=>{const safe=value.replace(/[^a-zA-Z0-9_]/g,"_").replace(/^[^a-zA-Z_]/,"_$&")||"instance";return`${safe.charAt(0).toLowerCase()}${safe.slice(1)}_${index+1}`;};
const rgb=(value:string)=>{const match=value.match(/^#([0-9a-f]{6})$/i);if(!match)return[255,255,255]as const;const parsed=Number.parseInt(match[1],16);return[(parsed>>16)&255,(parsed>>8)&255,parsed&255]as const;};
const colorValue=(value:string)=>{const[r,g,b]=rgb(value);return{kind:"Color3",r,g,b}as const;};
const transparent=(value:string)=>{const normalized=value.replaceAll(" ","").toLowerCase();if(normalized==="transparent"||normalized==="#00000000")return true;const rgba=normalized.match(/^rgba\([^,]+,[^,]+,[^,]+,([\d.]+)\)$/);return rgba?Number(rgba[1])===0:false;};
const nativeClassFor=(element:EditorElement)=>element.type==="image"?"ImageLabel":element.type==="image-button"?"ImageButton":element.type==="text"||element.type==="button"?classifyTextExport(element).className:element.roblox?.className??(element.type==="scrolling-frame"?"ScrollingFrame":"Frame");
const enumValue=(enumType:string,item:string)=>({kind:"Enum",enumType,item}as const);
const axis=(value:number,total:number,mode:RobloxExportOptions["sizingMode"],isSize=false)=>{if(mode==="OFFSET")return[0,round(value,2)]as const;if(mode==="SCALE")return[round(value/Math.max(1,total)),0]as const;if(mode==="HYBRID"||mode==="AUTO")return isSize?[0,round(value,2)]as const:[round(value/Math.max(1,total)),0]as const;return[0,round(value,2)]as const;};
const udim2=(x:number,y:number,width:number,height:number,mode:RobloxExportOptions["sizingMode"],isSize=false)=>{const[xScale,xOffset]=axis(x,width,mode,isSize),[yScale,yOffset]=axis(y,height,mode,isSize);return{kind:"UDim2",xScale,xOffset,yScale,yOffset}as const;};
const fontValue=(family:string,weight:number,style:"normal"|"italic")=>{const compatibility=getRobloxFontCompatibility(family),robloxWeight=weight>=800?"Heavy":weight>=700?"Bold":weight>=600?"SemiBold":weight>=500?"Medium":weight<=300?"Light":"Regular";return{kind:"Font",family:compatibility.family??null,enumName:compatibility.enumName??"Gotham",weight:robloxWeight,style:style==="italic"?"Italic":"Normal"}as const;};
const textX=(value:EditorElement["textAlign"])=>value==="center"?"Center":value==="right"?"Right":"Left";
const textY=(value:EditorElement["verticalAlign"])=>value==="top"?"Top":value==="bottom"?"Bottom":"Center";
const PIXEL_VIEWPORT_ID="__creatormake_viewport";
const pixelContentId=(sourceId:string)=>`${sourceId}::content`;
const pixelScrollId=(sourceId:string)=>`${sourceId}::scroll-area`;
export const calculateCreatorMakeFitScale=(referenceWidth:number,referenceHeight:number,viewportWidth:number,viewportHeight:number)=>Math.min(viewportWidth/Math.max(1,referenceWidth),viewportHeight/Math.max(1,referenceHeight));
const offsetUdim2=(x:number,y:number)=>({kind:"UDim2",xScale:0,xOffset:round(x,4),yScale:0,yOffset:round(y,4)}as const);
const scaleUdim2=(x:number,y:number)=>({kind:"UDim2",xScale:round(x,8),xOffset:0,yScale:round(y,8),yOffset:0}as const);
const aspectDecorator=(element:EditorElement):RobloxManifestNode["decorators"][number]=>({className:"UIAspectRatioConstraint",name:"CreatorMakeAspectRatio",properties:{AspectRatio:round(element.width/Math.max(1,element.height),6),AspectType:enumValue("AspectType","ScaleWithParentSize"),DominantAxis:enumValue("DominantAxis","Width")}});
const alignHorizontal=(value:EditorElement["crossAlign"])=>value==="center"?"Center":value==="end"?"Right":"Left";
const alignVertical=(value:EditorElement["crossAlign"])=>value==="center"?"Center":value==="end"?"Bottom":"Top";
function layoutDecorators(element:EditorElement,children:EditorElement[]=[]):RobloxManifestNode["decorators"]{
  const decorators:RobloxManifestNode["decorators"]=[],padding=element.layoutPadding;
  if(element.padding>0||Object.values(padding).some((value)=>value>0))decorators.push({className:"UIPadding",name:"UIPadding",properties:{PaddingTop:{kind:"UDim",scale:0,offset:round(padding.top||element.padding,2)},PaddingRight:{kind:"UDim",scale:0,offset:round(padding.right||element.padding,2)},PaddingBottom:{kind:"UDim",scale:0,offset:round(padding.bottom||element.padding,2)},PaddingLeft:{kind:"UDim",scale:0,offset:round(padding.left||element.padding,2)}}});
  const layout=element.layoutMode!=="none"?element.layoutMode:element.roblox?.layout;if(!layout)return decorators;
  if(layout==="grid"){
    const first=children.find((child)=>!child.hidden),columns=Math.max(1,element.gridColumns),availableWidth=Math.max(1,element.width-padding.left-padding.right-(columns-1)*element.columnGap),cellWidth=first?.width??availableWidth/columns,cellHeight=first?.height??92;
    decorators.push({className:"UIGridLayout",name:"UIGridLayout",properties:{CellPadding:{kind:"UDim2",xScale:0,xOffset:round(element.columnGap,2),yScale:0,yOffset:round(element.rowGap,2)},CellSize:{kind:"UDim2",xScale:0,xOffset:round(cellWidth,2),yScale:0,yOffset:round(cellHeight,2)},FillDirection:enumValue("FillDirection","Horizontal"),FillDirectionMaxCells:columns,HorizontalAlignment:enumValue("HorizontalAlignment",alignHorizontal(element.crossAlign)),VerticalAlignment:enumValue("VerticalAlignment",alignVertical(element.crossAlign)),SortOrder:enumValue("SortOrder","LayoutOrder"),StartCorner:enumValue("StartCorner","TopLeft")}});
  }else decorators.push({className:"UIListLayout",name:"UIListLayout",properties:{FillDirection:enumValue("FillDirection",layout==="horizontal"?"Horizontal":"Vertical"),Padding:{kind:"UDim",scale:0,offset:round(element.gap,2)},HorizontalAlignment:enumValue("HorizontalAlignment",alignHorizontal(element.crossAlign)),VerticalAlignment:enumValue("VerticalAlignment",alignVertical(element.crossAlign)),SortOrder:enumValue("SortOrder","LayoutOrder"),Wraps:element.layoutWrap}});
  return decorators;
}
const scrollingProperties=(element:EditorElement):RobloxManifestNode["properties"]=>({CanvasSize:offsetUdim2(element.canvasSizeX,element.canvasSizeY),CanvasPosition:{kind:"Vector2",x:round(element.canvasPositionX,2),y:round(element.canvasPositionY,2)},AutomaticCanvasSize:enumValue("AutomaticSize",element.automaticCanvasSize),ScrollingDirection:enumValue("ScrollingDirection",element.scrollingDirection),ScrollBarThickness:round(element.scrollBarThickness,2),ScrollBarImageColor3:colorValue(element.scrollBarImageColor),ScrollBarImageTransparency:round(element.scrollBarImageTransparency,4),ElasticBehavior:enumValue("ElasticBehavior",element.elasticBehavior),ScrollingEnabled:element.scrollingEnabled,VerticalScrollBarPosition:enumValue("VerticalScrollBarPosition",element.verticalScrollBarPosition),VerticalScrollBarInset:enumValue("ScrollBarInset",element.scrollBarInset),HorizontalScrollBarInset:enumValue("ScrollBarInset",element.scrollBarInset)});
const viewportNode=(project:EditorProject):RobloxManifestNode=>({sourceId:PIXEL_VIEWPORT_ID,name:"CreatorMakeViewport",className:"Frame",parentSourceId:null,properties:{Position:{kind:"UDim2",xScale:.5,xOffset:0,yScale:.5,yOffset:0},Size:offsetUdim2(project.screen.width,project.screen.height),AnchorPoint:{kind:"Vector2",x:.5,y:.5},Rotation:0,Visible:true,ZIndex:1,LayoutOrder:0,ClipsDescendants:false,BackgroundTransparency:1,Active:false},attributes:{CreatorMakeRole:"Viewport",CreatorMakeReferenceWidth:project.screen.width,CreatorMakeReferenceHeight:project.screen.height,CreatorMakeScaleMode:"FIT"},decorators:[{className:"UIScale",name:"CreatorMakeGlobalScale",properties:{Scale:1}}]});

export function checkRobloxCompatibility(elements:EditorElement[]):RobloxCompatibilityIssue[]{
  const issues:RobloxCompatibilityIssue[]=[];
  const add=(element:EditorElement,level:RobloxCompatibilityIssue["level"],feature:string,message:string)=>issues.push({elementId:element.id,elementName:element.name,level,feature,message});
  elements.forEach((element)=>{
    if(element.booleanOperation)add(element,"unsupported","Non-destructive Boolean",`${element.booleanOperation} remains editable in CreatorMake, but Roblox has no native Boolean UI geometry. Use Pixel Accurate export for visual fidelity.`);
    if(element.type==="vector")add(element,"unsupported","Custom vector geometry",`${geometryKindForElement(element)} remains editable in CreatorMake, but Roblox has no native equivalent. Use Pixel Accurate export or map an image asset.`);
    if(element.type==="polygon"||element.type==="star")add(element,"approximation","Vector shape","Native export uses a rectangular Frame. Pixel Accurate export preserves the real silhouette.");
    const cornerTypes=Object.values(element.cornerTypes);if(cornerTypes.some((type)=>type!=="round"&&type!=="square"))add(element,"unsupported","Advanced corners","Chamfer, inset, notch, concave, and scoop corners have no native Roblox UICorner representation.");else if(new Set(Object.values(element.corners)).size>1)add(element,"approximation","Per-corner radius","Roblox UICorner uses one uniform radius; native export uses the largest corner value.");
    if(element.shadow&&element.shadow!=="none")add(element,"approximation","Shadow","CSS shadows have no direct Roblox UI property. Pixel Accurate export preserves the rendered effect.");
    if(element.gradientType!=="none"&&element.gradientType!=="linear")add(element,"approximation","Gradient",`${element.gradientType} gradients are converted to a linear UIGradient in Native mode.`);
    if(element.rotateX||element.rotateY||element.z)add(element,"unsupported","3D transform","Roblox 2D UI cannot preserve perspective or 3D transforms natively. Pixel Accurate mode bakes the visual transform.");
    if((element.type==="text"||element.type==="button")&&element.textStrokeWidth>1)add(element,"approximation","Text stroke width","Roblox native text does not preserve arbitrary CSS stroke width exactly.");
    if(element.type==="text"||element.type==="button"){
      const font=getRobloxFontCompatibility(element.fontFamily);
      if(font.level==="close")add(element,"approximation","Font",`Custom font: ${element.fontFamily} has no exact Roblox native match. Native text uses ${font.matchName}; choose PIXEL TEXT when exact glyph fidelity matters.`);
      if(font.level==="unsupported")add(element,"approximation","Font",`Custom font: ${element.fontFamily} has no exact Roblox native match. AUTO and NATIVE TEXT keep the text editable with a declared Gotham fallback; choose PIXEL TEXT for exact glyphs.`);
    }
    if((element.roblox?.className==="ImageLabel"||element.roblox?.className==="ImageButton")&&!/^rbxassetid:\/\/\d+$/.test(element.roblox.imageAssetId??""))add(element,"unsupported","Image asset","IMAGE NEEDS ROBLOX ASSET ID. Assign a valid rbxassetid:// number before native export.");
  });
  return issues;
}

function layoutProperties(element:EditorElement,project:EditorProject,options:RobloxExportOptions,byId:Map<string,EditorElement>,bounds={x:0,y:0,width:element.width,height:element.height}){
  const parent=element.parentId?byId.get(element.parentId):undefined,parentWidth=parent?.width??project.screen.width,parentHeight=parent?.height??project.screen.height;
  const localX=element.x-(parent?.x??0),localY=element.y-(parent?.y??0),positionX=localX+element.width*element.anchorX,positionY=localY+element.height*element.anchorY;
  const anchorX=(element.width*element.anchorX-bounds.x)/Math.max(1,bounds.width),anchorY=(element.height*element.anchorY-bounds.y)/Math.max(1,bounds.height);
  return{Position:udim2(positionX,positionY,parentWidth,parentHeight,options.sizingMode),Size:udim2(bounds.width,bounds.height,parentWidth,parentHeight,options.sizingMode,true),AnchorPoint:{kind:"Vector2",x:round(anchorX),y:round(anchorY)},Rotation:round(element.rotation,2),Visible:!element.hidden,ZIndex:Math.max(1,element.zIndex*2+1),LayoutOrder:Math.max(1,element.zIndex),ClipsDescendants:element.clipContent} satisfies RobloxManifestNode["properties"];
}

function pixelLayoutProperties(element:EditorElement,project:EditorProject,byId:Map<string,EditorElement>,visibleIds:ReadonlySet<string>):RobloxManifestNode["properties"]{
  const parent=element.parentId&&visibleIds.has(element.parentId)?byId.get(element.parentId):undefined,localX=element.x-(parent?.x??0),localY=element.y-(parent?.y??0);
  return{Position:offsetUdim2(localX+element.width*element.anchorX,localY+element.height*element.anchorY),Size:offsetUdim2(element.width,element.height),AnchorPoint:{kind:"Vector2",x:round(element.anchorX,6),y:round(element.anchorY,6)},Rotation:round(element.rotation,2),Visible:!element.hidden,ZIndex:Math.max(2,element.zIndex*2+2),LayoutOrder:Math.max(1,element.zIndex),ClipsDescendants:element.clipContent};
}

function nativeNodeFor(element:EditorElement,project:EditorProject,options:RobloxExportOptions,byId:Map<string,EditorElement>):RobloxManifestNode{
  const properties:RobloxManifestNode["properties"]={...layoutProperties(element,project,options,byId),BackgroundColor3:colorValue(element.fill),BackgroundTransparency:transparent(element.fill)?1:round(1-element.opacity/100)};
  const className=nativeClassFor(element);
  if(className==="ScrollingFrame")Object.assign(properties,scrollingProperties(element),{ClipsDescendants:true});
  if(className==="TextLabel"||className==="TextButton"||className==="TextBox")Object.assign(properties,{Text:element.text,TextColor3:colorValue(element.textColor),TextTransparency:round(1-element.opacity/100),TextSize:round(element.fontSize,2),TextScaled:element.autoFit,TextWrapped:element.textBoxMode!=="auto-width",RichText:element.richText,AutomaticSize:enumValue("AutomaticSize",element.textBoxMode==="auto-width"?"X":element.textBoxMode==="auto-height"?"Y":"None"),TextXAlignment:enumValue("TextXAlignment",textX(element.textAlign)),TextYAlignment:enumValue("TextYAlignment",textY(element.verticalAlign)),TextStrokeColor3:colorValue(element.textStrokeColor),TextStrokeTransparency:element.textStrokeWidth>0?round(1-element.textStrokeOpacity/100):1,LineHeight:round(element.lineHeight,4),FontFace:fontValue(element.fontFamily,element.fontWeight,element.fontStyle),Active:className==="TextButton"||className==="TextBox",Selectable:className!=="TextLabel",...(className==="TextBox"?{ClearTextOnFocus:false,TextEditable:true}:{})});
  if(className==="ImageLabel"||className==="ImageButton")Object.assign(properties,{Image:element.roblox?.imageAssetId??"",ImageColor3:colorValue("#ffffff"),ImageTransparency:round(1-element.opacity/100),ScaleType:enumValue("ScaleType",element.sliceCenter?"Slice":element.imageFit==="fill"?"Crop":element.imageFit==="tile"?"Tile":element.imageFit==="stretch"?"Stretch":"Fit"),Active:className==="ImageButton",Selectable:className==="ImageButton",...(element.imageFit==="tile"?{TileSize:{kind:"UDim2",xScale:0,xOffset:Math.max(1,element.width),yScale:0,yOffset:Math.max(1,element.height)}}:{}),...(element.sliceCenter?{SliceCenter:{kind:"Rect",minX:element.sliceCenter.left,minY:element.sliceCenter.top,maxX:element.sliceCenter.right,maxY:element.sliceCenter.bottom},SliceScale:element.sliceScale}: {})});
  const decorators:RobloxManifestNode["decorators"]=[];
  if(options.includeStroke&&element.borderWidth>0&&!transparent(element.borderColor))decorators.push({className:"UIStroke",name:"UIStroke",properties:{Color:colorValue(element.borderColor),Thickness:round(element.borderWidth,2),Transparency:0}});
  const radius=Math.max(element.corners.tl,element.corners.tr,element.corners.br,element.corners.bl,element.cornerRadius);if(options.includeCorners&&radius>0)decorators.push({className:"UICorner",name:"UICorner",properties:{CornerRadius:{kind:"UDim",scale:0,offset:round(radius,2)}}});
  if(options.includeGradients&&element.gradientType!=="none"&&element.gradientStops.length>=2){const stops=element.gradientStops.slice(0,6);decorators.push({className:"UIGradient",name:"UIGradient",properties:{Color:{kind:"ColorSequence",keypoints:stops.map((stop)=>({time:round(stop.position/100),color:colorValue(stop.color)}))},Transparency:{kind:"NumberSequence",keypoints:stops.map((stop)=>({time:round(stop.position/100),value:round(1-stop.opacity/100)}))},Rotation:round(element.gradientAngle,2)}});}
  if(options.includeLayouts)decorators.push(...layoutDecorators(element,project.elements.filter((child)=>child.parentId===element.id)));
  if(options.includeConstraints&&element.scaleX===element.scaleY&&element.scaleX!==1)decorators.push({className:"UIScale",name:"UIScale",properties:{Scale:round(element.scaleX)}});
  if(options.includeConstraints&&element.constraints.horizontal==="scale"&&element.constraints.vertical==="scale")decorators.push({className:"UIAspectRatioConstraint",name:"UIAspectRatioConstraint",properties:{AspectRatio:round(element.width/Math.max(1,element.height),4),DominantAxis:enumValue("DominantAxis","Width")}});
  if(options.includeConstraints&&(element.minWidth!==null||element.maxWidth!==null||element.minHeight!==null||element.maxHeight!==null))decorators.push({className:"UISizeConstraint",name:"UISizeConstraint",properties:{MinSize:{kind:"Vector2",x:round(element.minWidth??0,2),y:round(element.minHeight??0,2)},MaxSize:{kind:"Vector2",x:round(element.maxWidth??100000,2),y:round(element.maxHeight??100000,2)}}});
  const textDecision=element.type==="text"||element.type==="button"?classifyTextExport(element):undefined;
  return{sourceId:element.id,name:element.name,className,parentSourceId:element.parentId,properties,attributes:{CreatorMakeSourceId:element.id,CreatorMakeRole:"Native",CreatorMakeElementType:element.type,...(textDecision?{CreatorMakeTextExportMode:textDecision.mode,CreatorMakeFontExact:textDecision.fontExact,CreatorMakeTextDynamic:element.dynamicText}:{})},decorators};
}

function orderedVisible(elements:EditorElement[]){const visible=elements.filter((element)=>!element.hidden),ordered:EditorElement[]=[],pending=new Map(visible.map((element)=>[element.id,element]));while(pending.size){let progressed=false;for(const[id,element]of pending){if(!element.parentId||!pending.has(element.parentId)){ordered.push(element);pending.delete(id);progressed=true;}}if(!progressed){ordered.push(...pending.values());break;}}return ordered;}

const assetElementId=(asset:RobloxRenderAsset)=>asset.sourceElementId??asset.sourceId;
const assetLookup=(assets:RobloxRenderAsset[])=>new Map(assets.map((asset)=>[`${assetElementId(asset)}:${asset.visualPart??"full"}`,asset]));
const textContentRect=(element:EditorElement)=>{const inset=Math.max(0,element.padding),width=Math.max(1,element.width-inset*2),height=Math.max(1,element.height-inset*2);return{x:inset,y:inset,width,height};};
const textProperties=(element:EditorElement,zIndex:number,className:"TextLabel"|"TextBox"):RobloxManifestNode["properties"]=>{const rect=textContentRect(element),textBox=className==="TextBox";return{Position:offsetUdim2(rect.x,rect.y),Size:offsetUdim2(rect.width,rect.height),AnchorPoint:{kind:"Vector2",x:0,y:0},Rotation:0,Visible:!element.hidden,ZIndex:zIndex,LayoutOrder:Math.max(1,element.zIndex),ClipsDescendants:false,BackgroundTransparency:1,Text:element.text,TextColor3:colorValue(element.textColor),TextTransparency:round(1-element.opacity/100),TextSize:round(element.fontSize,2),TextScaled:element.autoFit,TextWrapped:element.textBoxMode!=="auto-width",RichText:element.richText,AutomaticSize:enumValue("AutomaticSize",element.textBoxMode==="auto-width"?"X":element.textBoxMode==="auto-height"?"Y":"None"),TextXAlignment:enumValue("TextXAlignment",textX(element.textAlign)),TextYAlignment:enumValue("TextYAlignment",textY(element.verticalAlign)),TextStrokeColor3:colorValue(element.textStrokeColor),TextStrokeTransparency:element.textStrokeWidth>0?round(1-element.textStrokeOpacity/100):1,LineHeight:round(element.lineHeight,4),FontFace:fontValue(element.fontFamily,element.fontWeight,element.fontStyle),Active:textBox,Selectable:textBox,...(textBox?{ClearTextOnFocus:false,TextEditable:true}:{})};};
const textAttributes=(element:EditorElement)=>{const decision=classifyTextExport(element);return{CreatorMakeSourceElementId:element.id,CreatorMakeRole:decision.className==="TextBox"?"EditableTextBox":"EditableText",CreatorMakeTextExportMode:decision.mode,CreatorMakeFontExact:decision.fontExact,CreatorMakeTextDynamic:element.dynamicText,CreatorMakeFontFidelity:decision.fontExact?"Exact Roblox native match":"No exact Roblox native match",CreatorMakeTextFidelityWarning:decision.reasons.join(" · ")};};

export function createNativeTextLabel(element:EditorElement,parentSourceId:string,zIndex:number):RobloxManifestNode{
  const className=element.textInput?"TextBox":"TextLabel";
  return{sourceId:`${element.id}::text`,name:className,parentSourceId,className,properties:textProperties(element,zIndex,className),attributes:textAttributes(element),decorators:[]};
}

function splitTextNodes(element:EditorElement,parentSourceId:string,layout:RobloxManifestNode["properties"],backgroundAsset:RobloxRenderAsset|undefined,textAsset:RobloxRenderAsset|undefined,zStep:2|3):RobloxManifestNode[]{
  const decision=classifyTextExport(element),button=element.type==="button",rootClass=button?"ImageButton":"Frame",backgroundZ=Math.max(1,element.zIndex*zStep+(zStep===3?3:1)),textZ=backgroundZ+1,rootProperties:RobloxManifestNode["properties"]={...layout,Rotation:round(element.rotation,2),ClipsDescendants:false,BackgroundTransparency:1,Active:button,Selectable:button,...(button?{Image:"",ImageTransparency:1,AutoButtonColor:false}:{})},nodes:RobloxManifestNode[]=[{sourceId:element.id,name:element.name,className:rootClass,parentSourceId,properties:rootProperties,attributes:{CreatorMakeLayoutSourceId:element.id,CreatorMakeRole:button?"HitTarget":"TextContainer",CreatorMakeTextExportMode:decision.mode,CreatorMakeFontExact:decision.fontExact,CreatorMakeBackgroundSeparated:true,CreatorMakeVisualHash:backgroundAsset?.visualHash??""},decorators:[aspectDecorator(element)]}];
  if(backgroundAsset)nodes.push({sourceId:backgroundAsset.sourceId,name:"_Background",className:"ImageLabel",parentSourceId:element.id,properties:{Position:offsetUdim2(backgroundAsset.visualBounds.x,backgroundAsset.visualBounds.y),Size:offsetUdim2(backgroundAsset.visualBounds.width,backgroundAsset.visualBounds.height),AnchorPoint:{kind:"Vector2",x:0,y:0},Rotation:0,Visible:true,ZIndex:backgroundZ,LayoutOrder:0,ClipsDescendants:false,BackgroundTransparency:1,Image:backgroundAsset.robloxAssetId??"",ImageColor3:colorValue("#ffffff"),ImageTransparency:0,ScaleType:enumValue("ScaleType","Stretch"),Active:false,Selectable:false},attributes:{CreatorMakeSourceId:backgroundAsset.sourceId,CreatorMakeSourceElementId:element.id,CreatorMakeRole:"Background",CreatorMakeVisualHash:backgroundAsset.visualHash,CreatorMakeAssetStatus:backgroundAsset.status,CreatorMakePixelEncoding:backgroundAsset.pixelEncoding,CreatorMakeVisualPart:"background"},decorators:[]});
  if(decision.mode==="NATIVE"){
    nodes.push(createNativeTextLabel(element,element.id,textZ));
  }else if(textAsset)nodes.push({sourceId:textAsset.sourceId,name:"_PixelText",className:"ImageLabel",parentSourceId:element.id,properties:{Position:offsetUdim2(textAsset.visualBounds.x,textAsset.visualBounds.y),Size:offsetUdim2(textAsset.visualBounds.width,textAsset.visualBounds.height),AnchorPoint:{kind:"Vector2",x:0,y:0},Rotation:0,Visible:true,ZIndex:textZ,LayoutOrder:1,ClipsDescendants:false,BackgroundTransparency:1,Image:textAsset.robloxAssetId??"",ImageColor3:colorValue("#ffffff"),ImageTransparency:0,ScaleType:enumValue("ScaleType","Stretch"),Active:false,Selectable:false},attributes:{CreatorMakeSourceId:textAsset.sourceId,CreatorMakeSourceElementId:element.id,CreatorMakeRole:"PixelText",CreatorMakeVisualHash:textAsset.visualHash,CreatorMakeAssetStatus:textAsset.status,CreatorMakePixelEncoding:textAsset.pixelEncoding,CreatorMakeVisualPart:"text",CreatorMakeTextEditable:false},decorators:[]});
  return nodes;
}

function adaptiveNodes(project:EditorProject,options:RobloxExportOptions,assets:RobloxRenderAsset[]){
  const byId=new Map(project.elements.map((element)=>[element.id,element])),visibleElements=project.elements.filter((element)=>!element.hidden),visibleIds=new Set(visibleElements.map((element)=>element.id)),assetsByPart=assetLookup(assets),nodes:RobloxManifestNode[]=[viewportNode(project)];
  for(const element of orderedVisible(project.elements)){
    const classification=classifyRobloxElement(element),sourceParent=element.parentId&&visibleIds.has(element.parentId)?byId.get(element.parentId):undefined,parentSourceId=sourceParent?(sourceParent.type==="scrolling-frame"&&classifyRobloxElement(sourceParent).classification!=="NATIVE"?pixelScrollId(sourceParent.id):sourceParent.id):PIXEL_VIEWPORT_ID,baseLayout=pixelLayoutProperties(element,project,byId,visibleIds),layout={...baseLayout,Rotation:0},backgroundAsset=assetsByPart.get(`${element.id}:background`),textAsset=assetsByPart.get(`${element.id}:text`),asset=assetsByPart.get(`${element.id}:${classification.rasterPart??"full"}`),diagnosticAsset=backgroundAsset??textAsset??asset,visualBounds=diagnosticAsset?.visualBounds??{x:0,y:0,width:element.width,height:element.height},debug={CreatorMakeElementType:element.type,CreatorMakeGeometryType:geometryKindForElement(element),CreatorMakeExportClassification:classification.classification,CreatorMakeRenderStrategy:classification.classification==="NATIVE"?"Native Roblox":"Transparent PNG",CreatorMakeLayoutX:round(element.x-(element.parentId&&visibleIds.has(element.parentId)?byId.get(element.parentId)?.x??0:0),3),CreatorMakeLayoutY:round(element.y-(element.parentId&&visibleIds.has(element.parentId)?byId.get(element.parentId)?.y??0:0),3),CreatorMakeLayoutWidth:round(element.width,3),CreatorMakeLayoutHeight:round(element.height,3),CreatorMakeLayoutAspect:round(element.width/Math.max(1,element.height),6),CreatorMakeVisualOffsetX:round(visualBounds.x,3),CreatorMakeVisualOffsetY:round(visualBounds.y,3),CreatorMakeVisualWidth:round(visualBounds.width,3),CreatorMakeVisualHeight:round(visualBounds.height,3),CreatorMakeRenderPixelWidth:diagnosticAsset?.renderPixelWidth??0,CreatorMakeRenderPixelHeight:diagnosticAsset?.renderPixelHeight??0,CreatorMakeAlphaEdgeSafety:diagnosticAsset?.fidelity?.alphaEdgeSafety??false};
    if(classification.classification==="NATIVE"){
      const node=nativeNodeFor(element,project,{...options,sizingMode:"SCALE"},byId);
      nodes.push({...node,parentSourceId,properties:{...node.properties,...layout},attributes:{...node.attributes,...debug,CreatorMakeRole:"Native"}});
      continue;
    }
    if(element.type==="text"||element.type==="button"){
      const split=splitTextNodes(element,parentSourceId,baseLayout,backgroundAsset,textAsset,3);
      split[0]={...split[0],attributes:{...split[0].attributes,...debug}};
      nodes.push(...split);
      continue;
    }
    if(element.type==="scrolling-frame"){
      const image=asset?.robloxAssetId??"";
      nodes.push({sourceId:element.id,name:element.name,className:"Frame",parentSourceId,properties:{...layout,BackgroundTransparency:1,Active:false},attributes:{CreatorMakeLayoutSourceId:element.id,CreatorMakeRole:"ScrollingContainer",CreatorMakeVisualHash:asset?.visualHash??"",...debug},decorators:[aspectDecorator(element)]});
      if(asset)nodes.push({sourceId:`${element.id}::visual`,name:"_BackgroundImage",className:"ImageLabel",parentSourceId:element.id,properties:{Position:offsetUdim2(visualBounds.x,visualBounds.y),Size:offsetUdim2(visualBounds.width,visualBounds.height),AnchorPoint:{kind:"Vector2",x:0,y:0},Rotation:0,Visible:true,ZIndex:Math.max(2,element.zIndex*3+3),LayoutOrder:0,ClipsDescendants:false,BackgroundTransparency:1,Image:image,ImageColor3:colorValue("#ffffff"),ImageTransparency:0,ScaleType:enumValue("ScaleType","Stretch"),Active:false},attributes:{CreatorMakeSourceId:element.id,CreatorMakeRole:"BackgroundImage",CreatorMakeVisualHash:asset.visualHash,CreatorMakeAssetStatus:asset.status,CreatorMakePixelEncoding:asset.pixelEncoding,CreatorMakeVisualPart:classification.rasterPart??"full",...debug},decorators:[]});
      nodes.push({sourceId:pixelScrollId(element.id),name:"_ScrollArea",className:"ScrollingFrame",parentSourceId:element.id,properties:{Position:scaleUdim2(0,0),Size:scaleUdim2(1,1),AnchorPoint:{kind:"Vector2",x:0,y:0},Rotation:0,Visible:true,ZIndex:Math.max(3,element.zIndex*3+4),LayoutOrder:1,ClipsDescendants:true,BackgroundTransparency:1,Active:true,Selectable:false,...scrollingProperties(element)},attributes:{CreatorMakeSourceId:element.id,CreatorMakeRole:"ScrollArea",CreatorMakeLogicalParentId:element.id},decorators:options.includeLayouts?layoutDecorators(element,visibleElements.filter((child)=>child.parentId===element.id)):[]});
      continue;
    }
    const image=asset?.robloxAssetId??"",rootProperties:RobloxManifestNode["properties"]={...layout,Rotation:0,BackgroundTransparency:1,Active:false,Selectable:false};
    nodes.push({sourceId:element.id,name:element.name,className:"Frame",parentSourceId,properties:rootProperties,attributes:{CreatorMakeLayoutSourceId:element.id,CreatorMakeRole:"Container",CreatorMakeVisualHash:asset?.visualHash??"",...debug},decorators:[aspectDecorator(element)]});
    if(asset)nodes.push({sourceId:`${element.id}::visual`,name:classification.rasterPart==="background"?"_BackgroundImage":"_Visual",className:"ImageLabel",parentSourceId:element.id,properties:{Position:offsetUdim2(visualBounds.x,visualBounds.y),Size:offsetUdim2(visualBounds.width,visualBounds.height),AnchorPoint:{kind:"Vector2",x:0,y:0},Rotation:0,Visible:true,ZIndex:Math.max(2,element.zIndex*3+3),LayoutOrder:0,ClipsDescendants:false,BackgroundTransparency:1,Image:image,ImageColor3:colorValue("#ffffff"),ImageTransparency:0,ScaleType:enumValue("ScaleType","Stretch"),Active:false},attributes:{CreatorMakeSourceId:element.id,CreatorMakeRole:classification.rasterPart==="background"?"BackgroundImage":"Visual",CreatorMakeVisualHash:asset.visualHash,CreatorMakeAssetStatus:asset.status,CreatorMakePixelEncoding:asset.pixelEncoding,CreatorMakeVisualPart:classification.rasterPart??"full",...debug},decorators:[]});
  }
  return nodes;
}

function createImageManifest(project:EditorProject,assets:RobloxRenderAsset[]):RobloxImageManifestEntry[]{
  const byId=new Map(project.elements.map((element)=>[element.id,element]));
  return assets.flatMap((asset):RobloxImageManifestEntry[]=>{const element=byId.get(assetElementId(asset));if(!element)return[];const classification=asset.classification==="HYBRID"?"HYBRID":"RASTERIZED",part=asset.visualPart??"full",filename=`${element.name.replace(/[^a-z0-9_-]+/gi,"-").replace(/(^-|-$)/g,"").toLowerCase()||"visual"}-${part}-${asset.visualHash}.png`,layoutAspectRatio=round(element.width/Math.max(1,element.height),8),visualAspectRatio=round(asset.visualBounds.width/Math.max(1,asset.visualBounds.height),8);return[{sourceId:asset.sourceId,sourceElementId:element.id,elementName:element.name,assetFilename:filename,visualHash:asset.visualHash,classification,visualPart:part,sourceDimensions:{width:element.width,height:element.height},croppedPixelDimensions:{width:asset.renderPixelWidth,height:asset.renderPixelHeight},visualBounds:asset.visualBounds,layoutAspectRatio,visualAspectRatio,aspectRatio:layoutAspectRatio,position:{x:element.x,y:element.y},size:{width:element.width,height:element.height},parentId:element.parentId,zIndex:element.zIndex,anchorPoint:{x:element.anchorX,y:element.anchorY},intendedRobloxClass:asset.intendedRobloxClass??(element.type==="button"?"ImageButton":"ImageLabel"),interactionEnabled:asset.interactionEnabled??element.type==="button"}];});
}

function pixelNodes(project:EditorProject,options:RobloxExportOptions,assets:RobloxRenderAsset[]){
  const byId=new Map(project.elements.map((element)=>[element.id,element])),visibleElements=project.elements.filter((element)=>!element.hidden),visibleIds=new Set(visibleElements.map((element)=>element.id)),parentsWithVisibleChildren=new Set(visibleElements.flatMap((element)=>element.parentId&&visibleIds.has(element.parentId)?[element.parentId]:[])),assetsByPart=assetLookup(assets),nodes:RobloxManifestNode[]=[viewportNode(project)];
  for(const element of orderedVisible(project.elements)){
    const backgroundAsset=assetsByPart.get(`${element.id}:background`),textAsset=assetsByPart.get(`${element.id}:text`),asset=assetsByPart.get(`${element.id}:full`),diagnosticAsset=backgroundAsset??textAsset??asset,image=asset?.robloxAssetId??"",container=element.type==="frame"||element.type==="container"||element.type==="scrolling-frame",sourceParent=element.parentId&&visibleIds.has(element.parentId)?byId.get(element.parentId):undefined,parentSourceId=sourceParent?(sourceParent.type==="scrolling-frame"?pixelScrollId(sourceParent.id):sourceParent.clipContent?pixelContentId(sourceParent.id):sourceParent.id):PIXEL_VIEWPORT_ID,baseLayout=pixelLayoutProperties(element,project,byId,visibleIds),layout={...baseLayout,Rotation:0,ClipsDescendants:false},visualBounds=diagnosticAsset?.visualBounds??diagnosticAsset?.bounds??{x:0,y:0,width:element.width,height:element.height},padded=Math.abs(visualBounds.x)>.001||Math.abs(visualBounds.y)>.001||Math.abs(visualBounds.width-element.width)>.001||Math.abs(visualBounds.height-element.height)>.001,needsContentClip=element.type!=="scrolling-frame"&&element.clipContent&&parentsWithVisibleChildren.has(element.id);
    const debugAttributes={CreatorMakeElementType:element.type,CreatorMakeGeometryType:geometryKindForElement(element),CreatorMakeRenderStrategy:"Canonical Vector",CreatorMakeLayoutX:round(element.x-(sourceParent?.x??0),3),CreatorMakeLayoutY:round(element.y-(sourceParent?.y??0),3),CreatorMakeLayoutWidth:round(element.width,3),CreatorMakeLayoutHeight:round(element.height,3),CreatorMakeLayoutAspect:round(element.width/Math.max(1,element.height),6),CreatorMakeVisualOffsetX:round(visualBounds.x,3),CreatorMakeVisualOffsetY:round(visualBounds.y,3),CreatorMakeVisualWidth:round(visualBounds.width,3),CreatorMakeVisualHeight:round(visualBounds.height,3),CreatorMakeRenderPixelWidth:diagnosticAsset?.renderPixelWidth??diagnosticAsset?.width??0,CreatorMakeRenderPixelHeight:diagnosticAsset?.renderPixelHeight??diagnosticAsset?.height??0,CreatorMakeAlphaEdgeSafety:diagnosticAsset?.fidelity?.alphaEdgeSafety??false};
    const visualProperties:RobloxManifestNode["properties"]={Position:offsetUdim2(visualBounds.x,visualBounds.y),Size:offsetUdim2(visualBounds.width,visualBounds.height),AnchorPoint:{kind:"Vector2",x:0,y:0},Rotation:0,Visible:true,ZIndex:Math.max(1,element.zIndex*2+1),LayoutOrder:0,ClipsDescendants:false,BackgroundTransparency:1,Image:image,ImageColor3:colorValue("#ffffff"),ImageTransparency:0,ScaleType:enumValue("ScaleType","Stretch"),Active:false};
    if(element.type==="text"||element.type==="button"){
      const decision=classifyTextExport(element);
      if(element.type==="text"&&!hasVisibleTextBackground(element)&&decision.mode==="NATIVE"){
        const node=nativeNodeFor(element,project,{...options,sizingMode:"OFFSET"},byId);
        nodes.push({...node,parentSourceId,properties:{...node.properties,...baseLayout,BackgroundTransparency:1},attributes:{...node.attributes,...debugAttributes,CreatorMakeRole:element.textInput?"EditableTextBox":"EditableText"}});
      }else{
        const split=splitTextNodes(element,parentSourceId,baseLayout,backgroundAsset,textAsset,2);
        split[0]={...split[0],attributes:{...split[0].attributes,...debugAttributes}};
        nodes.push(...split);
      }
      continue;
    }
    if(element.type==="scrolling-frame"){
      nodes.push({sourceId:element.id,name:element.name,className:"Frame",parentSourceId,properties:{...layout,BackgroundTransparency:1,Active:false},attributes:{CreatorMakeSourceId:element.id,CreatorMakeRole:"ScrollingContainer",CreatorMakeVisualHash:asset?.visualHash??"",...debugAttributes},decorators:[aspectDecorator(element)]});
      if(asset)nodes.push({sourceId:`${element.id}::visual`,name:"_Visual",className:"ImageLabel",parentSourceId:element.id,properties:padded?visualProperties:{...visualProperties,Position:offsetUdim2(0,0),Size:scaleUdim2(1,1)},attributes:{CreatorMakeSourceId:element.id,CreatorMakeRole:"Visual",CreatorMakeVisualHash:asset.visualHash,CreatorMakeAssetStatus:asset.status,CreatorMakePixelEncoding:asset.pixelEncoding},decorators:[]});
      nodes.push({sourceId:pixelScrollId(element.id),name:"_ScrollArea",className:"ScrollingFrame",parentSourceId:element.id,properties:{Position:scaleUdim2(0,0),Size:scaleUdim2(1,1),AnchorPoint:{kind:"Vector2",x:0,y:0},Rotation:0,Visible:true,ZIndex:Math.max(2,element.zIndex*2+2),LayoutOrder:1,ClipsDescendants:true,BackgroundTransparency:1,Active:true,Selectable:false,...scrollingProperties(element)},attributes:{CreatorMakeSourceId:element.id,CreatorMakeRole:"ScrollArea",CreatorMakeLogicalParentId:element.id,CreatorMakeLayoutWidth:round(element.width,3),CreatorMakeLayoutHeight:round(element.height,3)},decorators:options.includeLayouts?layoutDecorators(element,visibleElements.filter((child)=>child.parentId===element.id)):[]});
      continue;
    }
    if(container){
      nodes.push({sourceId:element.id,name:element.name,className:"Frame",parentSourceId,properties:{...layout,BackgroundTransparency:1,Active:false},attributes:{CreatorMakeSourceId:element.id,CreatorMakeRole:"Container",CreatorMakeVisualHash:asset?.visualHash??"",...debugAttributes},decorators:[aspectDecorator(element)]});
      if(asset)nodes.push({sourceId:`${element.id}::visual`,name:"_Visual",className:"ImageLabel",parentSourceId:element.id,properties:padded?visualProperties:{...visualProperties,Position:offsetUdim2(0,0),Size:{kind:"UDim2",xScale:1,xOffset:0,yScale:1,yOffset:0}},attributes:{CreatorMakeSourceId:element.id,CreatorMakeRole:"Visual",CreatorMakeVisualHash:asset.visualHash,CreatorMakeAssetStatus:asset.status,CreatorMakePixelEncoding:asset.pixelEncoding},decorators:[]});
      if(needsContentClip)nodes.push({sourceId:pixelContentId(element.id),name:"_ContentClip",className:"Frame",parentSourceId:element.id,properties:{Position:scaleUdim2(0,0),Size:scaleUdim2(1,1),AnchorPoint:{kind:"Vector2",x:0,y:0},Rotation:0,Visible:true,ZIndex:Math.max(2,element.zIndex*2+2),LayoutOrder:0,ClipsDescendants:true,BackgroundTransparency:1,Active:false,Selectable:false},attributes:{CreatorMakeRole:"ContentClip",CreatorMakeLogicalParentId:element.id,CreatorMakeLayoutWidth:round(element.width,3),CreatorMakeLayoutHeight:round(element.height,3)},decorators:[]});
      continue;
    }
    const className=padded?"Frame":"ImageLabel",rootProperties:RobloxManifestNode["properties"]={...layout,BackgroundTransparency:1,Active:false,Selectable:false,...(className==="ImageLabel"?{Image:image,ImageColor3:colorValue("#ffffff"),ImageTransparency:0,ScaleType:enumValue("ScaleType","Stretch")}:{})};
    nodes.push({sourceId:element.id,name:element.name,className,parentSourceId,properties:rootProperties,attributes:{...(padded?{CreatorMakeLayoutSourceId:element.id}:{CreatorMakeSourceId:element.id}),CreatorMakeRole:padded?"Container":"Visual",CreatorMakeVisualHash:asset?.visualHash??"",CreatorMakeLayoutHash:asset?.layoutHash??"",CreatorMakeAssetStatus:asset?.status??"needs-render",CreatorMakePixelEncoding:asset?.pixelEncoding??"RGBA8_STRAIGHT_ALPHA",...debugAttributes},decorators:[aspectDecorator(element)]});
    if(padded)nodes.push({sourceId:`${element.id}::visual`,name:"_Visual",className:"ImageLabel",parentSourceId:element.id,properties:visualProperties,attributes:{CreatorMakeSourceId:element.id,CreatorMakeRole:"Visual",CreatorMakeVisualHash:asset?.visualHash??"",CreatorMakeAssetStatus:asset?.status??"needs-render",CreatorMakePixelEncoding:asset?.pixelEncoding??"RGBA8_STRAIGHT_ALPHA"},decorators:[]});
    if(needsContentClip)nodes.push({sourceId:pixelContentId(element.id),name:"_ContentClip",className:"Frame",parentSourceId:element.id,properties:{Position:scaleUdim2(0,0),Size:scaleUdim2(1,1),AnchorPoint:{kind:"Vector2",x:0,y:0},Rotation:0,Visible:true,ZIndex:Math.max(2,element.zIndex*2+2),LayoutOrder:0,ClipsDescendants:true,BackgroundTransparency:1,Active:false,Selectable:false},attributes:{CreatorMakeRole:"ContentClip",CreatorMakeLogicalParentId:element.id,CreatorMakeLayoutWidth:round(element.width,3),CreatorMakeLayoutHeight:round(element.height,3)},decorators:[]});
  }
  return nodes;
}

export type RobloxLayoutDiagnostic={
  name:string;
  sourceId:string;
  creatorMake:{parent:string|null;x:number;y:number;width:number;height:number};
  robloxDesign:{parent:string|null;x:number;y:number;width:number;height:number};
  visual:{offsetX:number;offsetY:number;width:number;height:number};
  raster:{scale:number;pixelWidth:number;pixelHeight:number};
  globalScaleAtReference:number;
};

const udim2Property=(value:RobloxPropertyValue|undefined)=>typeof value==="object"&&value!==null&&"kind"in value&&value.kind==="UDim2"?value:undefined;
const vector2Property=(value:RobloxPropertyValue|undefined)=>typeof value==="object"&&value!==null&&"kind"in value&&value.kind==="Vector2"?value:undefined;
const closeEnough=(left:number,right:number,tolerance=.011)=>Number.isFinite(left)&&Number.isFinite(right)&&Math.abs(left-right)<=tolerance;
const layoutAssetLookup=(assets:RobloxRenderAsset[])=>{const result=new Map<string,RobloxRenderAsset>();for(const asset of assets){const elementId=assetElementId(asset),current=result.get(elementId);if(!current||asset.visualPart==="background"||asset.visualPart==="full")result.set(elementId,asset);}return result;};

export function createRenderedLayoutDiagnostics(project:EditorProject,nodes:RobloxManifestNode[],assets:RobloxRenderAsset[]):RobloxLayoutDiagnostic[]{
  const visible=project.elements.filter((element)=>!element.hidden),visibleIds=new Set(visible.map((element)=>element.id)),byElement=new Map(project.elements.map((element)=>[element.id,element])),byNode=new Map(nodes.map((node)=>[node.sourceId,node])),byAsset=layoutAssetLookup(assets);
  return visible.flatMap((element):RobloxLayoutDiagnostic[]=>{
    const node=byNode.get(element.id),position=udim2Property(node?.properties.Position),size=udim2Property(node?.properties.Size),anchor=vector2Property(node?.properties.AnchorPoint);if(!node||!position||!size||!anchor)return[];
    const parent=element.parentId&&visibleIds.has(element.parentId)?byElement.get(element.parentId):undefined,parentWidth=parent?.width??project.screen.width,parentHeight=parent?.height??project.screen.height,width=size.xScale*parentWidth+size.xOffset,height=size.yScale*parentHeight+size.yOffset,x=position.xScale*parentWidth+position.xOffset-anchor.x*width,y=position.yScale*parentHeight+position.yOffset-anchor.y*height,asset=byAsset.get(element.id),visual=asset?.visualBounds??{x:0,y:0,width:element.width,height:element.height};
    const physicalParent=node.parentSourceId===PIXEL_VIEWPORT_ID?null:node.parentSourceId,logicalParent=physicalParent?.endsWith("::content")?physicalParent.slice(0,-"::content".length):physicalParent?.endsWith("::scroll-area")?physicalParent.slice(0,-"::scroll-area".length):physicalParent;
    return[{name:element.name,sourceId:element.id,creatorMake:{parent:parent?.id??null,x:element.x-(parent?.x??0),y:element.y-(parent?.y??0),width:element.width,height:element.height},robloxDesign:{parent:logicalParent,x,y,width,height},visual:{offsetX:visual.x,offsetY:visual.y,width:visual.width,height:visual.height},raster:{scale:asset?.scale??0,pixelWidth:asset?.renderPixelWidth??0,pixelHeight:asset?.renderPixelHeight??0},globalScaleAtReference:1}];
  });
}

export function assertRenderedLayoutFidelity(project:EditorProject,nodes:RobloxManifestNode[],assets:RobloxRenderAsset[]){
  const diagnostics=createRenderedLayoutDiagnostics(project,nodes,assets),byNode=new Map(nodes.map((node)=>[node.sourceId,node])),byAsset=layoutAssetLookup(assets),problems:string[]=[];
  for(const row of diagnostics){
    const node=byNode.get(row.sourceId)!,asset=byAsset.get(row.sourceId),expectedParent=row.creatorMake.parent,actualParent=row.robloxDesign.parent;
    if(expectedParent!==actualParent)problems.push(`${row.name}: parent ${String(actualParent)} != ${String(expectedParent)}`);
    for(const field of ["x","y","width","height"] as const)if(!closeEnough(row.robloxDesign[field],row.creatorMake[field]))problems.push(`${row.name}: Roblox ${field} ${row.robloxDesign[field]} != CreatorMake ${row.creatorMake[field]}`);
    if(asset){
      if(!closeEnough(asset.layoutWidth,row.creatorMake.width)||!closeEnough(asset.layoutBounds.width,row.creatorMake.width))problems.push(`${row.name}: raster plan replaced layout width`);
      if(!closeEnough(asset.layoutHeight,row.creatorMake.height)||!closeEnough(asset.layoutBounds.height,row.creatorMake.height))problems.push(`${row.name}: raster plan replaced layout height`);
      const visualNode=nodes.find((candidate)=>candidate.parentSourceId===row.sourceId&&["Visual","BackgroundImage","Background","PixelText"].includes(String(candidate.attributes?.CreatorMakeRole)));
      if(visualNode){const position=udim2Property(visualNode.properties.Position),size=udim2Property(visualNode.properties.Size);if(!position||!size)problems.push(`${row.name}: inner visual is missing offset layout`);else{const visualX=position.xScale*row.robloxDesign.width+position.xOffset,visualY=position.yScale*row.robloxDesign.height+position.yOffset,visualWidth=size.xScale*row.robloxDesign.width+size.xOffset,visualHeight=size.yScale*row.robloxDesign.height+size.yOffset;if(!closeEnough(visualX,row.visual.offsetX)||!closeEnough(visualY,row.visual.offsetY)||!closeEnough(visualWidth,row.visual.width)||!closeEnough(visualHeight,row.visual.height))problems.push(`${row.name}: inner visual does not match visual bounds`);}}
      else if(!closeEnough(row.visual.offsetX,0)||!closeEnough(row.visual.offsetY,0)||!closeEnough(row.visual.width,row.creatorMake.width)||!closeEnough(row.visual.height,row.creatorMake.height))problems.push(`${row.name}: visual overflow has no inner visual`);
    }
    const aspect=node.decorators.find((decorator)=>decorator.className==="UIAspectRatioConstraint")?.properties.AspectRatio;if(typeof aspect==="number"&&!closeEnough(aspect,row.creatorMake.width/Math.max(1,row.creatorMake.height),.000002))problems.push(`${row.name}: aspect ratio came from non-layout bounds`);
  }
  if(problems.length)throw new Error(`ROBLOX_LAYOUT_FIDELITY_FAILURE:\n${problems.join("\n")}`);
  return diagnostics;
}

function luaValue(value:RobloxPropertyValue):string{if(typeof value==="string")return quote(value);if(typeof value!=="object")return String(value);if(value.kind==="Color3")return`Color3.fromRGB(${value.r}, ${value.g}, ${value.b})`;if(value.kind==="Vector2")return`Vector2.new(${value.x}, ${value.y})`;if(value.kind==="UDim")return`UDim.new(${value.scale}, ${value.offset})`;if(value.kind==="UDim2")return`UDim2.new(${value.xScale}, ${value.xOffset}, ${value.yScale}, ${value.yOffset})`;if(value.kind==="Rect")return`Rect.new(${value.minX}, ${value.minY}, ${value.maxX}, ${value.maxY})`;if(value.kind==="Enum")return`Enum.${value.enumType}.${value.item}`;if(value.kind==="ColorSequence")return`ColorSequence.new({${value.keypoints.map((point)=>`ColorSequenceKeypoint.new(${point.time}, Color3.fromRGB(${point.color.r}, ${point.color.g}, ${point.color.b}))`).join(", ")}})`;if(value.kind==="NumberSequence")return`NumberSequence.new({${value.keypoints.map((point)=>`NumberSequenceKeypoint.new(${point.time}, ${point.value})`).join(", ")}})`;if(value.family)return`Font.new(${quote(value.family)}, Enum.FontWeight.${value.weight}, Enum.FontStyle.${value.style})`;return`Font.fromEnum(Enum.Font.${value.enumName})`;}
const writeProperty=(target:string,key:string,value:RobloxPropertyValue)=>`${target}.${key} = ${luaValue(value)}`;
const attributeValue=(value:string|number|boolean)=>typeof value==="string"?quote(value):String(value);

export function createRobloxExport(project:EditorProject,options:RobloxExportOptions,renderAssets?:RobloxRenderAsset[]){
  const byId=new Map(project.elements.map((element)=>[element.id,element])),renderedMode=options.visualMode!=="NATIVE",pixel=options.visualMode==="PIXEL_ACCURATE",adaptive=options.visualMode==="ADAPTIVE",assets=renderedMode?(renderAssets??planPixelAccurateAssets(project,options)):[],nodes=pixel?pixelNodes(project,options,assets):adaptive?adaptiveNodes(project,options,assets):orderedVisible(project.elements).map((element)=>nativeNodeFor(element,project,options,byId)),imageManifest=createImageManifest(project,assets);
  const manifestAssets=assets.map((asset)=>{const manifestAsset={...asset};delete manifestAsset.sourceDataUrl;delete manifestAsset.differenceDataUrl;return manifestAsset;});
  const projectId=project.id||options.screenGuiName,projectName=project.name||options.screenGuiName,projectObjectIds=project.elements.map((element)=>element.id),exportedProjectObjectCount=project.elements.filter((element)=>!element.hidden).length;
  const manifest:RobloxManifest={kind:"project",messageType:"PROJECT_MANIFEST",schema:"creatormake.roblox-manifest",version:2,textExportArchitecture:2,projectId,projectName,manifestVersion:`${projectId}:${project.updatedAt??0}:${project.elements.length}`,projectObjectIds,exportDiagnostics:{projectObjectCount:project.elements.length,exportedProjectObjectCount,exportNodeCount:nodes.length,presetsExported:0,presetDefinitionsIncluded:false},screenGuiName:options.screenGuiName,deployTarget:"STARTER_GUI",screenGuiSettings:{enabled:true,displayOrder:0,ignoreGuiInset:renderedMode,resetOnSpawn:options.resetOnSpawn,zIndexBehavior:"Global"},referenceResolution:{width:renderedMode?project.screen.width:options.resolution.width,height:renderedMode?project.screen.height:options.resolution.height},sizingMode:renderedMode?"OFFSET":options.sizingMode,visualMode:options.visualMode,renderScale:options.renderScale,viewportScaleMode:renderedMode?"FIT":undefined,assets:manifestAssets,imageManifest,nodes};
  const layoutDiagnostics=renderedMode?assertRenderedLayoutFidelity(project,nodes,assets):[];
  if(renderedMode&&typeof window!=="undefined"&&typeof console.table==="function")console.table(layoutDiagnostics.map((row)=>({name:row.name,creatorParent:row.creatorMake.parent??"CreatorMakeViewport",creatorX:row.creatorMake.x,creatorY:row.creatorMake.y,creatorW:row.creatorMake.width,creatorH:row.creatorMake.height,robloxParent:row.robloxDesign.parent??"CreatorMakeViewport",robloxX:row.robloxDesign.x,robloxY:row.robloxDesign.y,robloxW:row.robloxDesign.width,robloxH:row.robloxDesign.height,visualX:row.visual.offsetX,visualY:row.visual.offsetY,visualW:row.visual.width,visualH:row.visual.height,rasterW:row.raster.pixelWidth,rasterH:row.raster.pixelHeight,globalScaleAtReference:row.globalScaleAtReference})));
  const variables=new Map<string,string>();nodes.forEach((node,index)=>variables.set(node.sourceId,varName(node.name,index)));
  const lines=["-- Generated by CreatorMake",`-- Visual mode: ${options.visualMode}`,"-- Permanent CreatorMake ScreenGuis are installed in StarterGui so Roblox copies them to every player's PlayerGui.","local StarterGui = game:GetService(\"StarterGui\")","","local screenGui = Instance.new(\"ScreenGui\")",`screenGui.Name = ${quote(options.screenGuiName)}`,`screenGui.ResetOnSpawn = ${options.resetOnSpawn}`,`screenGui.IgnoreGuiInset = ${renderedMode?"true":"false"}`,"screenGui.Enabled = true","screenGui.DisplayOrder = 0","screenGui.ZIndexBehavior = Enum.ZIndexBehavior.Global",`screenGui:SetAttribute("CreatorMakeManaged", true)`,`screenGui:SetAttribute("CreatorMakeProjectId", ${quote(projectId)})`,`screenGui:SetAttribute("CreatorMakeDeployTarget", "StarterGui")`,"screenGui.Parent = StarterGui",""];
  nodes.forEach((node)=>{const variable=variables.get(node.sourceId)!;lines.push(`local ${variable} = Instance.new(${quote(node.className)})`,`${variable}.Name = ${quote(node.name)}`,`${variable}:SetAttribute("CreatorMakeId", ${quote(node.sourceId)})`);Object.entries(node.attributes??{}).forEach(([key,value])=>lines.push(`${variable}:SetAttribute(${quote(key)}, ${attributeValue(value)})`));Object.entries(node.properties).forEach(([key,value])=>lines.push(writeProperty(variable,key,value)));lines.push(`${variable}.Parent = ${node.parentSourceId?variables.get(node.parentSourceId)??"screenGui":"screenGui"}`);node.decorators.forEach((decorator,decoratorIndex)=>{const decoratorVar=`${variable}_${decorator.className.charAt(0).toLowerCase()}${decorator.className.slice(1)}_${decoratorIndex+1}`;lines.push(`local ${decoratorVar} = Instance.new(${quote(decorator.className)})`,`${decoratorVar}.Name = ${quote(decorator.name)}`);Object.entries(decorator.properties).forEach(([key,value])=>lines.push(writeProperty(decoratorVar,key,value)));lines.push(`${decoratorVar}.Parent = ${variable}`);});lines.push("");});
  if(renderedMode){const viewport=variables.get(PIXEL_VIEWPORT_ID)!;lines.push(
    "local creatorMakeViewportConnection = nil",
    "local function updateCreatorMakeScale()",
    "  local camera = workspace.CurrentCamera",
    "  if not camera then return end",
    "  local viewportSize = camera.ViewportSize",
    `  ${viewport}.CreatorMakeGlobalScale.Scale = math.min(viewportSize.X / ${round(project.screen.width,3)}, viewportSize.Y / ${round(project.screen.height,3)})`,
    "end",
    "local function bindCreatorMakeCamera()",
    "  if creatorMakeViewportConnection then creatorMakeViewportConnection:Disconnect(); creatorMakeViewportConnection = nil end",
    "  local camera = workspace.CurrentCamera",
    "  if camera then creatorMakeViewportConnection = camera:GetPropertyChangedSignal(\"ViewportSize\"):Connect(updateCreatorMakeScale) end",
    "  updateCreatorMakeScale()",
    "end",
    "bindCreatorMakeCamera()",
    "workspace:GetPropertyChangedSignal(\"CurrentCamera\"):Connect(bindCreatorMakeCamera)",
    "",
  );}
  lines.push("return screenGui");
  const classifications=classifyRobloxElements(project.elements),assetCompatibility=renderedMode?assets.flatMap((asset):RobloxCompatibilityIssue[]=>{const elementId=assetElementId(asset),classification=classifications.get(elementId);return asset.status==="error"?[{elementId,elementName:asset.elementName,level:"unsupported",feature:"Transparent PNG render",message:asset.error??"The visual could not be rendered."}]:adaptive?[{elementId,elementName:asset.elementName,level:"approximation",feature:`${classification?.classification??"RASTERIZED"} export`,message:`${classification?.reasons.join(", ")||"This visual needs exact raster output"}. CreatorMake keeps ${asset.visualPart==="text"?"the pixel-text fallback":"the visual background"} as a separate transparent image.`}]:!asset.robloxAssetId?[{elementId,elementName:asset.elementName,level:"approximation",feature:"Studio Preview",message:"PNG is staged for instant EditableImage preview. Publish explicitly through CreatorMake when a permanent Roblox asset ID is needed."}]:[];}):[],compatibility=[...checkRobloxCompatibility(project.elements),...assetCompatibility];
  return{lua:lines.join("\n"),manifest,compatibility,hierarchy:createHierarchyText(options.screenGuiName,nodes),assets,layoutDiagnostics};
}

function createHierarchyText(screenGuiName:string,nodes:RobloxManifestNode[]){const children=new Map<string|null,RobloxManifestNode[]>();nodes.forEach((node)=>{const key=node.parentSourceId&&nodes.some((item)=>item.sourceId===node.parentSourceId)?node.parentSourceId:null,list=children.get(key)??[];list.push(node);children.set(key,list);});const lines=[`${screenGuiName} [ScreenGui]`],walk=(parent:string|null,depth:number)=>{(children.get(parent)??[]).forEach((node)=>{lines.push(`${"  ".repeat(depth)}${node.name} [${node.className}]`);node.decorators.forEach((item)=>lines.push(`${"  ".repeat(depth+1)}${item.name} [${item.className}]`));walk(node.sourceId,depth+1);});};walk(null,1);return lines.join("\n");}

export function verifyGeneratedLua(lua:string){const errors:string[]=[];if(lua.includes("undefined")||lua.includes("NaN"))errors.push("Output contains an invalid JavaScript value.");if(!lua.includes('Instance.new("ScreenGui")'))errors.push("ScreenGui root is missing.");if(!lua.trim().endsWith("return screenGui"))errors.push("Generated script does not return the ScreenGui.");let depth=0;for(const char of lua){if(char==="(")depth++;if(char===")")depth--;if(depth<0){errors.push("Closing parenthesis appears before an opening parenthesis.");break;}}if(depth!==0)errors.push("Parentheses are unbalanced.");return{valid:errors.length===0,errors};}
