import * as clippingModule from "polygon-clipping";
import { geometryPresentation } from "./geometry.ts";
import { createId } from "./project.ts";
import type { BooleanOperation, EditorElement, EditorProject } from "./types.ts";
import type { MultiPolygon, Pair, Polygon } from "polygon-clipping";

const clipping=((clippingModule as unknown as {default?:typeof clippingModule}).default??clippingModule);

const BOOLEAN_TYPES=new Set(["vector","rectangle","roundRect","ellipse","polygon","star"]);
const EPSILON=.0001;
type Point={x:number;y:number};
export type BooleanBuild={removeIds:string[];elements:EditorElement[];selectedIds:string[];operation:BooleanOperation};

const closeRing=(points:Point[])=>{const filtered=points.filter((point,index)=>index===0||Math.hypot(point.x-points[index-1].x,point.y-points[index-1].y)>EPSILON);if(filtered.length<3)return[];const first=filtered[0],last=filtered.at(-1)!;if(Math.hypot(first.x-last.x,first.y-last.y)>EPSILON)filtered.push({...first});return filtered;};
const signedArea=(ring:Point[])=>ring.slice(0,-1).reduce((sum,point,index)=>{const next=ring[(index+1)%(ring.length-1)];return sum+point.x*next.y-next.x*point.y;},0)/2;
const pointInRing=(point:Point,ring:Point[])=>{let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j],cross=(a.y>point.y)!==(b.y>point.y)&&point.x<(b.x-a.x)*(point.y-a.y)/(b.y-a.y||EPSILON)+a.x;if(cross)inside=!inside;}return inside;};
const cubic=(a:number,b:number,c:number,d:number,t:number)=>{const u=1-t;return u*u*u*a+3*u*u*t*b+3*u*t*t*c+t*t*t*d;};
const quadratic=(a:number,b:number,c:number,t:number)=>{const u=1-t;return u*u*a+2*u*t*b+t*t*c;};

function arcPoints(from:Point,rxValue:number,ryValue:number,rotation:number,largeArc:number,sweep:number,to:Point){
  let rx=Math.abs(rxValue),ry=Math.abs(ryValue);if(rx<EPSILON||ry<EPSILON)return[to];const phi=rotation*Math.PI/180,cos=Math.cos(phi),sin=Math.sin(phi),dx=(from.x-to.x)/2,dy=(from.y-to.y)/2,xp=cos*dx+sin*dy,yp=-sin*dx+cos*dy,ratio=xp*xp/(rx*rx)+yp*yp/(ry*ry);if(ratio>1){const scale=Math.sqrt(ratio);rx*=scale;ry*=scale;}const numerator=Math.max(0,rx*rx*ry*ry-rx*rx*yp*yp-ry*ry*xp*xp),denominator=Math.max(EPSILON,rx*rx*yp*yp+ry*ry*xp*xp),sign=largeArc===sweep?-1:1,factor=sign*Math.sqrt(numerator/denominator),cxp=factor*rx*yp/ry,cyp=-factor*ry*xp/rx,cx=cos*cxp-sin*cyp+(from.x+to.x)/2,cy=sin*cxp+cos*cyp+(from.y+to.y)/2,angle=(ux:number,uy:number,vx:number,vy:number)=>Math.atan2(ux*vy-uy*vx,ux*vx+uy*vy),ux=(xp-cxp)/rx,uy=(yp-cyp)/ry,vx=(-xp-cxp)/rx,vy=(-yp-cyp)/ry,start=Math.atan2(uy,ux);let delta=angle(ux,uy,vx,vy);if(!sweep&&delta>0)delta-=Math.PI*2;if(sweep&&delta<0)delta+=Math.PI*2;const steps=Math.max(4,Math.ceil(Math.abs(delta)/(Math.PI/16)));return Array.from({length:steps},(_,index)=>{const theta=start+delta*(index+1)/steps;return{x:cx+cos*rx*Math.cos(theta)-sin*ry*Math.sin(theta),y:cy+sin*rx*Math.cos(theta)+cos*ry*Math.sin(theta)};});
}

export function flattenSvgPath(path:string){
  const tokens=path.match(/[a-zA-Z]|[-+]?(?:\d*\.\d+|\d+\.?)(?:e[-+]?\d+)?/gi)??[],rings:Point[][]=[];let index=0,command="",current={x:0,y:0},start={x:0,y:0},ring:Point[]=[];const isCommand=(token:string|undefined)=>Boolean(token&&/^[a-zA-Z]$/.test(token)),number=()=>Number(tokens[index++]),point=(x:number,y:number,relative:boolean)=>({x:relative?current.x+x:x,y:relative?current.y+y:y}),push=(next:Point)=>{ring.push(next);current=next;};const finish=()=>{const closed=closeRing(ring);if(closed.length)rings.push(closed);ring=[];};
  while(index<tokens.length){if(isCommand(tokens[index]))command=tokens[index++];if(!command)break;const lower=command.toLowerCase(),relative=command===lower;if(lower==="z"){if(ring.length)push({...start});finish();current={...start};command="";continue;}if(lower==="m"){const next=point(number(),number(),relative);if(ring.length)finish();push(next);start={...next};command=relative?"l":"L";continue;}if(lower==="l"){push(point(number(),number(),relative));continue;}if(lower==="h"){const value=number();push({x:relative?current.x+value:value,y:current.y});continue;}if(lower==="v"){const value=number();push({x:current.x,y:relative?current.y+value:value});continue;}if(lower==="q"){const control=point(number(),number(),relative),to=point(number(),number(),relative),from={...current};for(let step=1;step<=8;step++){const t=step/8;push({x:quadratic(from.x,control.x,to.x,t),y:quadratic(from.y,control.y,to.y,t)});}continue;}if(lower==="c"){const c1=point(number(),number(),relative),c2=point(number(),number(),relative),to=point(number(),number(),relative),from={...current};for(let step=1;step<=12;step++){const t=step/12;push({x:cubic(from.x,c1.x,c2.x,to.x,t),y:cubic(from.y,c1.y,c2.y,to.y,t)});}continue;}if(lower==="a"){const rx=number(),ry=number(),rotation=number(),large=number(),sweep=number(),to=point(number(),number(),relative);arcPoints(current,rx,ry,rotation,large,sweep,to).forEach(push);continue;}throw new Error(`Boolean geometry cannot parse SVG command ${command}.`);}
  if(ring.length)finish();return rings;
}

function transformPoint(point:Point,element:EditorElement){const ox=element.width*element.originX/100,oy=element.height*element.originY/100,sx=(point.x-ox)*element.scaleX,sy=(point.y-oy)*element.scaleY,skewedX=sx+Math.tan(element.skewX*Math.PI/180)*sy,skewedY=sy+Math.tan(element.skewY*Math.PI/180)*sx,radians=element.rotation*Math.PI/180;return{x:element.x+ox+skewedX*Math.cos(radians)-skewedY*Math.sin(radians),y:element.y+oy+skewedX*Math.sin(radians)+skewedY*Math.cos(radians)};}
function ringsToMultiPolygon(rings:Point[][]):MultiPolygon{const sorted=[...rings].sort((a,b)=>Math.abs(signedArea(b))-Math.abs(signedArea(a))),polygons:Point[][][]=[];for(const ring of sorted){const parent=polygons.find((polygon)=>pointInRing(ring[0],polygon[0]));if(parent)parent.push(ring);else polygons.push([ring]);}return polygons.map((polygon)=>polygon.map((ring)=>ring.map((point)=>[point.x,point.y] as Pair)) as Polygon);}
export function elementToBooleanGeometry(element:EditorElement):MultiPolygon{if(!BOOLEAN_TYPES.has(element.type))throw new Error(`${element.name} is not a filled vector shape.`);if(element.hidden||element.locked)throw new Error(`${element.name} must be visible and unlocked.`);if(element.rotateX||element.rotateY)throw new Error(`${element.name} uses 3D rotation. Reset Rotate X/Y before Boolean operations.`);const presentation=geometryPresentation(element),isRawCustom=element.geometry.kind==="custom-path"&&!element.geometry.nodes.length&&Boolean(presentation.transform);if(presentation.open)throw new Error(`${element.name} is an open path. Close it before Boolean operations.`);const rings=flattenSvgPath(presentation.path).map((ring)=>ring.map((point)=>transformPoint(isRawCustom?{x:point.x*element.width/100,y:point.y*element.height/100}:point,element)));const result=ringsToMultiPolygon(rings);if(!result.length)throw new Error(`${element.name} has no closed Boolean geometry.`);return result;}

const polygonArea=(multi:MultiPolygon)=>multi.reduce((sum,polygon)=>sum+polygon.reduce((value,ring,index)=>value+(index? -1:1)*Math.abs(ring.reduce((area,point,pointIndex)=>{const next=ring[(pointIndex+1)%ring.length];return area+point[0]*next[1]-next[0]*point[1];},0)/2),0),0);
function multiPolygonPath(multi:MultiPolygon){const points=multi.flat(2);if(!points.length)throw new Error("Boolean operation produced no visible geometry.");const minX=Math.min(...points.map((point)=>point[0])),minY=Math.min(...points.map((point)=>point[1])),maxX=Math.max(...points.map((point)=>point[0])),maxY=Math.max(...points.map((point)=>point[1])),width=Math.max(EPSILON,maxX-minX),height=Math.max(EPSILON,maxY-minY),n=(value:number)=>Number(value.toFixed(4)),path=multi.flatMap((polygon)=>polygon.map((ring)=>{const unique=ring.length>1&&Math.hypot(ring[0][0]-ring.at(-1)![0],ring[0][1]-ring.at(-1)![1])<EPSILON?ring.slice(0,-1):ring;return unique.map((point,index)=>`${index?"L":"M"} ${n((point[0]-minX)/width*100)} ${n((point[1]-minY)/height*100)}`).join(" ")+" Z";})).join(" ");return{x:minX,y:minY,width,height,path};}

function operationGeometry(inputs:MultiPolygon[],operation:Exclude<BooleanOperation,"divide">){if(operation==="union")return clipping.union(inputs[0],...inputs.slice(1));if(operation==="intersect")return clipping.intersection(inputs[0],...inputs.slice(1));if(operation==="exclude")return clipping.xor(inputs[0],...inputs.slice(1));return clipping.difference(inputs[0],...inputs.slice(1));}
function resultElement(source:EditorElement,multi:MultiPolygon,name:string,index:number,operation:BooleanOperation|null,operands:EditorElement[]){const bounds=multiPolygonPath(multi),result=structuredClone(source);result.id=createId("boolean");result.type="vector";result.name=name;result.parentId=operands.every((item)=>item.parentId===operands[0].parentId)?operands[0].parentId:null;result.x=bounds.x;result.y=bounds.y;result.width=bounds.width;result.height=bounds.height;result.rotation=0;result.scaleX=1;result.scaleY=1;result.originX=50;result.originY=50;result.skewX=0;result.skewY=0;result.rotateX=0;result.rotateY=0;result.translateZ=0;result.zIndex=Math.max(...operands.map((item)=>item.zIndex))+index;result.geometry={...result.geometry,kind:"custom-path",pathData:bounds.path,nodes:[],closed:true};result.corners={tl:0,tr:0,br:0,bl:0};result.cornerRadius=0;result.cornerTypes={tl:"square",tr:"square",br:"square",bl:"square"};result.booleanOperation=operation;result.booleanOperands=operation?structuredClone(operands):[];return result;}

function selectedBooleanSources(project:EditorProject){const selected=project.selectedIds.map((id)=>project.elements.find((item)=>item.id===id)).filter((item):item is EditorElement=>Boolean(item));if(selected.length<2)throw new Error("Select at least two filled vector shapes.");if(selected.some((item)=>project.elements.some((candidate)=>candidate.parentId===item.id)))throw new Error("Boolean operands cannot contain child layers. Select leaf vector shapes.");if(!selected.every((item)=>item.parentId===selected[0].parentId))throw new Error("Boolean operands must share the same parent.");return selected;}
export function buildBooleanSelection(project:EditorProject,operation:BooleanOperation):BooleanBuild{const sources=selectedBooleanSources(project),inputs=sources.map(elementToBooleanGeometry),removeIds=sources.map((item)=>item.id);if(operation==="divide"){if(sources.length!==2)throw new Error("Divide currently requires exactly two vector shapes.");const pieces=[clipping.difference(inputs[0],inputs[1]),clipping.intersection(inputs[0],inputs[1]),clipping.difference(inputs[1],inputs[0])].filter((multi)=>multi.length&&polygonArea(multi)>EPSILON),elements=pieces.map((multi,index)=>resultElement(index===2?sources[1]:sources[0],multi,`Divide Piece ${index+1}`,index+1,null,sources));if(!elements.length)throw new Error("Divide produced no visible regions.");return{removeIds,elements,selectedIds:elements.map((item)=>item.id),operation};}const multi=operationGeometry(inputs,operation);if(!multi.length||polygonArea(multi)<EPSILON)throw new Error(`${operation} produced no visible geometry.`);const label=operation[0].toUpperCase()+operation.slice(1),element=resultElement(sources[0],multi,`${label} Boolean`,1,operation,sources);return{removeIds,elements:[element],selectedIds:[element.id],operation};}
export function applyBooleanBuild(project:EditorProject,build:BooleanBuild){const ids=new Set(build.removeIds);project.elements=project.elements.filter((item)=>!ids.has(item.id));project.elements.push(...build.elements);project.selectedIds=[...build.selectedIds];}
export function rebuildBooleanElement(element:EditorElement,operation:Exclude<BooleanOperation,"divide">){if(!element.booleanOperands.length)throw new Error("This Boolean result has no editable operands.");const multi=operationGeometry(element.booleanOperands.map(elementToBooleanGeometry),operation);if(!multi.length||polygonArea(multi)<EPSILON)throw new Error(`${operation} produced no visible geometry.`);const rebuilt=resultElement(element,multi,`${operation[0].toUpperCase()+operation.slice(1)} Boolean`,1,operation,element.booleanOperands);rebuilt.id=element.id;return rebuilt;}
export function releaseBoolean(project:EditorProject,id:string){const element=project.elements.find((item)=>item.id===id);if(!element?.booleanOperands.length)return;const sources=structuredClone(element.booleanOperands);project.elements=project.elements.filter((item)=>item.id!==id);project.elements.push(...sources);project.selectedIds=sources.map((item)=>item.id);}
export function flattenBoolean(project:EditorProject,id:string){const element=project.elements.find((item)=>item.id===id);if(!element)return;element.booleanOperation=null;element.booleanOperands=[];element.name=element.name.replace(/ Boolean$/,"");}
