export type ElementType = "frame" | "container" | "scrolling-frame" | "text" | "rectangle" | "roundRect" | "ellipse" | "line" | "polygon" | "star" | "button" | "image" | "image-button" | "vector";

export type ImageFitMode = "fit" | "fill" | "stretch" | "original" | "tile";
export type ImageState = "default" | "hover" | "pressed" | "disabled" | "selected";
export type TextRobloxExportMode = "AUTO" | "NATIVE_TEXT" | "PIXEL_ACCURATE" | "NATIVE" | "PIXEL";
export type TextSizingMode = "fixed" | "responsive";
export type EditorAsset = {
  id:string;
  name:string;
  originalName:string;
  kind:"image" | "texture";
  folder:string;
  mimeType:"image/png" | "image/jpeg" | "image/webp" | "image/gif" | "image/svg+xml";
  format:"PNG" | "JPEG" | "WEBP" | "GIF" | "SVG";
  width:number;
  height:number;
  fileSize:number;
  contentHash:string;
  dataUrl:string;
  thumbnailDataUrl:string;
  createdAt:number;
  animated:boolean;
  warning:string | null;
  favorite:boolean;
};

export type ProjectKind="blank"|"commission";
export type CommissionBrief={
  clientLabel:string;
  gameName:string;
  targetDevices:string[];
  requestedStyle:string;
  colorPalette:string;
  fonts:string;
  deliverables:string;
  notes:string;
};

export type GeometryKind = "rectangle" | "rounded-rectangle" | "ellipse" | "circle" | "line" | "triangle" | "polygon" | "star" | "diamond" | "trapezoid" | "parallelogram" | "chevron" | "arrow" | "capsule" | "ring" | "arc" | "pie" | "notched-rectangle" | "cut-corner-rectangle" | "ticket" | "bracket" | "tab" | "banner" | "plaque" | "ribbon" | "custom-path";
export type CornerType = "square" | "round" | "chamfer" | "inset" | "notch" | "concave" | "scoop";
export type CornerKey = "tl" | "tr" | "br" | "bl";
export type PathNodeType = "corner" | "smooth" | "symmetric";
export type PathNode = { id:string;x:number;y:number;type:PathNodeType;inX:number;inY:number;outX:number;outY:number };
export type BooleanOperation = "union" | "subtract" | "intersect" | "exclude" | "divide";
export type VectorGeometry = {
  kind: GeometryKind;
  sides: number;
  points: number;
  innerRadius: number;
  inset: number;
  thickness: number;
  skew: number;
  arcStart: number;
  arcEnd: number;
  pathData: string;
  nodes: PathNode[];
  closed: boolean;
};

export type GradientType = "none" | "linear" | "radial" | "conic" | "diamond" | "four-corner" | "freeform";
export type GradientStop = { id: string; color: string; position: number; opacity: number };
export type GradientPoint = { id:string;color:string;x:number;y:number;opacity:number;radius:number };
export type BlendMode = "normal" | "multiply" | "screen" | "overlay" | "darken" | "lighten" | "difference" | "exclusion";
export type LayoutMode = "none" | "horizontal" | "vertical" | "grid";
export type LayoutSizing = "fixed" | "hug" | "fill";
export type LayoutAlignment = "start" | "center" | "end" | "space-between";
export type CrossAlignment = "start" | "center" | "end" | "stretch";
export type HorizontalConstraint = "left" | "right" | "left-right" | "center" | "scale";
export type VerticalConstraint = "top" | "bottom" | "top-bottom" | "center" | "scale";
export type EdgeInsets = { top: number; right: number; bottom: number; left: number };
export type AutomaticCanvasSize = "None" | "X" | "Y" | "XY";
export type ScrollingDirection = "X" | "Y" | "XY";
export type ElasticBehavior = "WhenScrollable" | "Always" | "Never";
export type VerticalScrollBarPosition = "Left" | "Right";
export type ScrollBarInset = "None" | "ScrollBar" | "Always";

export type EditorElement = {
  id: string;
  type: ElementType;
  name: string;
  parentId: string | null;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  scaleX: number;
  scaleY: number;
  originX: number;
  originY: number;
  anchorX: number;
  anchorY: number;
  zIndex: number;
  layoutMode: LayoutMode;
  layoutWrap: boolean;
  gap: number;
  rowGap: number;
  columnGap: number;
  layoutPadding: EdgeInsets;
  primaryAlign: LayoutAlignment;
  crossAlign: CrossAlignment;
  gridColumns: number;
  sizingX: LayoutSizing;
  sizingY: LayoutSizing;
  minWidth: number | null;
  maxWidth: number | null;
  minHeight: number | null;
  maxHeight: number | null;
  constraints: { horizontal: HorizontalConstraint; vertical: VerticalConstraint };
  clipContent: boolean;
  canvasSizeX: number;
  canvasSizeY: number;
  automaticCanvasSize: AutomaticCanvasSize;
  canvasPositionX: number;
  canvasPositionY: number;
  scrollingDirection: ScrollingDirection;
  scrollBarThickness: number;
  scrollBarImageColor: string;
  scrollBarImageTransparency: number;
  elasticBehavior: ElasticBehavior;
  scrollingEnabled: boolean;
  verticalScrollBarPosition: VerticalScrollBarPosition;
  scrollBarInset: ScrollBarInset;
  frameType: "frame" | "window" | "card" | "header" | "toolbar" | "navigation" | "content" | "modal" | "hud" | "grid" | "group";
  fill: string;
  opacity: number;
  borderColor: string;
  borderWidth: number;
  cornerRadius: number;
  corners: { tl: number; tr: number; br: number; bl: number };
  cornerTypes: Record<CornerKey, CornerType>;
  geometry: VectorGeometry;
  booleanOperation: BooleanOperation | null;
  booleanOperands: EditorElement[];
  gradientType: GradientType;
  gradientAngle: number;
  gradientStops: GradientStop[];
  gradientPoints: GradientPoint[];
  fourCornerColors: {tl:string;tr:string;bl:string;br:string};
  blendMode: BlendMode;
  shadow: string;
  text: string;
  textColor: string;
  fontId: string;
  fontFamily: string;
  fontSize: number;
  fontSizeDesign: number;
  fontWeight: number;
  fontStyle: "normal" | "italic";
  lineHeight: number;
  letterSpacing: number;
  wordSpacing: number;
  paragraphSpacing: number;
  verticalAlign: "top" | "center" | "bottom";
  textTransform: "none" | "uppercase" | "lowercase" | "capitalize";
  textDecoration: "none" | "underline" | "line-through";
  textStrokeColor: string;
  textStrokeWidth: number;
  textStrokeOpacity: number;
  textStrokePosition: "inside" | "center" | "outside";
  textShadows: string[];
  textBoxMode: "auto-width" | "auto-height" | "fixed";
  autoFit: boolean;
  textSizingMode: TextSizingMode;
  responsiveMinTextSize: number;
  responsiveMaxTextSize: number;
  textAlign: "left" | "center" | "right";
  padding: number;
  textPadding: EdgeInsets;
  z: number;
  rotateX: number;
  rotateY: number;
  perspective: number;
  perspectiveOriginX: number;
  perspectiveOriginY: number;
  translateZ: number;
  skewX: number;
  skewY: number;
  locked: boolean;
  hidden: boolean;
  imageAssetId: string | null;
  imageFit: ImageFitMode;
  imageCrop: { x:number;y:number;width:number;height:number };
  imageOffsetX: number;
  imageOffsetY: number;
  imageScale: number;
  imageScaleX: number;
  imageScaleY: number;
  imageRotation: number;
  imageOpacity: number;
  imageFlipX: boolean;
  imageFlipY: boolean;
  imageTileWidth: number;
  imageTileHeight: number;
  imageBrightness: number;
  imageContrast: number;
  imageSaturation: number;
  imageHue: number;
  imageBlur: number;
  imageTint: string;
  imageTintOpacity: number;
  imageStateAssetIds: Record<ImageState,string | null>;
  imagePreviewState: ImageState;
  sliceCenter: { left:number;top:number;right:number;bottom:number } | null;
  sliceScale: number;
  textRobloxExportMode: TextRobloxExportMode;
  dynamicText: boolean;
  richText: boolean;
  textInput: boolean;
  roblox?: {
    className?: "Frame" | "TextLabel" | "TextButton" | "ImageLabel" | "ImageButton" | "ScrollingFrame" | "ViewportFrame";
    layout?: "horizontal" | "vertical" | "grid";
    imageAssetId?: string;
  };
};

export type Screen = {
  id: string;
  name: string;
  width: number;
  height: number;
  background: string;
  x: number;
  y: number;
};

export type EditorProject = {
  schemaVersion: 9;
  id: string;
  name: string;
  createdAt: number;
  updatedAt: number;
  platform: "Roblox" | "Generic UI";
  status: "Draft" | "In Progress" | "Client Review" | "Final";
  tags: string[];
  archived: boolean;
  projectKind:ProjectKind;
  commissionBrief:CommissionBrief;
  screen: Screen;
  elements: EditorElement[];
  assets: EditorAsset[];
  assetFolders: string[];
  selectedIds: string[];
  references: EditorReference[];
  activePresetIds: string[];
  favoritePresetIds: string[];
  favoriteFontIds: string[];
  recentFontIds: string[];
  customFrameRecipes: FrameRecipe[];
  researchCache: Record<string, ResearchResult>;
  generationHistory: GenerationHistoryEntry[];
  projectFonts: Array<{ fontId: string; weights: number[]; styles: Array<"normal" | "italic"> }>;
  fontPolicy: { allowSyntheticWeight: boolean; allowSyntheticItalic: boolean };
};

export type EditorHistoryCommand = {
  id:string;
  label:string;
  before:EditorProject;
  after:EditorProject;
  createdAt:number;
  estimatedBytes:number;
};

export type RecoverySnapshot = {
  id: string;
  projectId: string;
  projectName: string;
  savedAt: number;
  project: EditorProject;
};

export type GenerationHistoryEntry = {
  id: string; prompt: string; researchQuery: string; plan?: DesignPlan; aiPlan?: import("@/lib/ai/types").CreatorMakeAIPlan; engine?: import("@/lib/ai/types").GenerationEngine; provider?: string; model?: string; operations: string[]; resultIds: string[]; time: number;
  validation?: { passed: boolean; repaired: number; issues: string[] };
  before: { elements: EditorElement[]; selectedIds: string[] };
};

export type ProjectSummary = Pick<EditorProject, "id" | "name" | "createdAt" | "updatedAt" | "platform" | "status" | "tags" | "archived" | "projectKind"> & {
  thumbnail: string;
  width: number;
  height: number;
  frameCount: number;
};

export type ResizeCorner = "nw" | "ne" | "sw" | "se";
export type InspectorMode = "basic" | "advanced" | "expert" | "master";
export type Alignment = "left" | "hcenter" | "right" | "top" | "vcenter" | "bottom";
export type AlignmentTarget = "selection" | "parent" | "frame" | "canvas" | "key-object";
export type ViewAction = "fit-selection" | "fit-frame" | "fit-all" | "actual" | "zoom-in" | "zoom-out";
import type { DesignPlan, EditorReference, FrameRecipe, ResearchResult } from "@/lib/design-intelligence/types";
